MODULE PurchaseLedgerFashion;

REQUIRE PurchaseLedgerArticle, ItemFashion;

NAMESPACE PurchaseLedger;

nameCollectionItemPurchaseLedger 'Коллекция' (ledger) = nameCollectionItem(skuPurchaseLedger(ledger));

seasonYearItemPurchaseLedger 'Год (артикула) ' (ledger) = ABSTRACT SeasonYear(PurchaseLedger);
nameSeasonYearItemPurchaseLedger 'Год (артикула) ' (ledger) = nameSeasonYear(seasonYearItemPurchaseLedger(ledger));

seasonItemPurchaseLedger 'Сезон (артикула)' (ledger) = ABSTRACT Season(PurchaseLedger);
nameSeasonItemPurchaseLedger 'Сезон (артикула)' (ledger) = nameSeason(seasonItemPurchaseLedger(ledger));

EXTEND FORM purchaseLedger
    PROPERTIES(s) READONLY BEFORE nameSkuPurchaseLedger(s) nameCollectionItemPurchaseLedger, nameSeasonYearItemPurchaseLedger, nameSeasonItemPurchaseLedger
;
