MODULE PurchaseShipmentGestori;

REQUIRE PurchaseShipment;

NAMESPACE Purchase;

deliveryDateChanged (Order order) = shipmentDate(order) AND date(order) AND shipmentDate(order) != date(order);

countDeliveryDateChanged (LegalEntity supplier, DATE dateFrom, DATE dateTo) =
    GROUP SUM 1 IF deliveryDateChanged(Order order)
        AND date(order) >= dateFrom
        AND date(order) <= dateTo
        AND isPosted(order)
    BY supplier(order);

countDeliveryDateChangedZ 'Число изменений даты поставки' (LegalEntity s, DATE dFrom, DATE dTo) =
    OVERRIDE countDeliveryDateChanged(s, dFrom, dTo), 0;

EXTEND FORM executionSupplierOrder
    PROPERTIES READONLY countDeliveryDateChangedZ(s, dFrom, dTo)
;

codeSupplier 'Код поставщика' (LegalEntity l) = id(l);

quantityOrder (LegalEntity supplier, DATE dateFrom, DATE dateTo) =
    GROUP SUM quantityOrderDetail(Purchase.Order order)
        IF date(order) >= dateFrom AND date(order) <= dateTo AND isPosted(order)
    BY supplier(order);

quantityShipped (LegalEntity supplier, DATE dateFrom, DATE dateTo) =
    GROUP SUM shippedShipmentDetail(Purchase.Order order)
        IF date(order) >= dateFrom AND date(order) <= dateTo AND isPosted(order)
    BY supplier(order);

sumOrder (LegalEntity supplier, DATE dateFrom, DATE dateTo) =
    GROUP SUM sumOrderDetail(Purchase.Order order)
        IF date(order) >= dateFrom AND date(order) <= dateTo AND isPosted(order)
    BY supplier(order);

quantityOrderZ 'Количество (заказ)' (LegalEntity s, DATE dFrom, DATE dTo) =
    OVERRIDE quantityOrder(s, dFrom, dTo), 0.0;

quantityShippedZ 'Количество (приход)' (LegalEntity s, DATE dFrom, DATE dTo) =
    OVERRIDE quantityShipped(s, dFrom, dTo), 0.0;

sumOrderZ 'Сумма (заказ)' (LegalEntity s, DATE dFrom, DATE dTo) =
    OVERRIDE sumOrder(s, dFrom, dTo), 0.0;

sumShippedZ 'Сумма (приход)' (LegalEntity s, DATE dFrom, DATE dTo) =
    OVERRIDE sumShipped(s, dFrom, dTo), 0.0;

percentQuantityExecutionZ '% исполнения (кол-во)' (LegalEntity s, DATE dFrom, DATE dTo) =
    OVERRIDE percentQuantityExecution(s, dFrom, dTo), 0.0;

percentSumExecutionZ '% исполнения (сумма)' (LegalEntity s, DATE dFrom, DATE dTo) =
    OVERRIDE percentSumExecution(s, dFrom, dTo), 0.0;

FORM execSupplierReportPrint 'Отчет по исполнению заказов поставщиками'
    OBJECTS dFrom = DATE, dTo = DATE
    OBJECTS s = LegalEntity
    PROPERTIES(s) READONLY codeSupplier, name
    PROPERTIES(s, dFrom, dTo) READONLY
    quantityOrderZ, quantityShippedZ, percentQuantityExecutionZ,
        sumOrderZ, sumShippedZ, percentSumExecutionZ,
        countDeliveryDateChangedZ
    FILTERS isSupplier(s),
        quantityOrder(s, dFrom, dTo) OR quantityShipped(s, dFrom, dTo)
;

execSupplierReportPrint 'Отчет' (DATE dFrom, DATE dTo) {
    PRINT execSupplierReportPrint OBJECTS dFrom = dFrom, dTo = dTo XLSX;
} IMAGE 'print.png';

EXTEND FORM executionSupplierOrder
    PROPERTIES execSupplierReportPrint(dFrom, dTo)
;

DESIGN executionSupplierOrder {
    dates{ MOVE PROPERTY (execSupplierReportPrint(dFrom, dTo)); }
}