MODULE PurchaseAgreement;

REQUIRE Agreement, Purchase;

NAMESPACE  Purchase;

// ----------------------------------------------- Виды цен --------------------------------- //

purchasePriceListType = DATA PriceListType ();
namePurchasePriceListType 'Вид цены (закупка) по умолчанию для соглашения' = namePriceListType(purchasePriceListType());

EXTEND FORM options PROPERTIES() namePurchasePriceListType;
DESIGN options {
    purchase {
        MOVE PROPERTY(namePurchasePriceListType());        
    }    
}

WHEN SESSION FORMS agreement, legalEntity
    SET(isPurchaseAgreement(a)) DO {
        priceListTypeAgreement (a) <- purchasePriceListType();
    } 