MODULE ImportTNVED;

REQUIRE Import, DefaultData;


//---------------------------------------------- Импорт ТНВЭД -----------------------------------------------------//

GROUP tnved 'ТНВЭД' : public;

importTNVEDClassifierAction 'Импортировать справочник' = ACTION CUSTOM 'lsfusion.erp.region.by.certificate.declaration.ImportTNVEDClassifierActionProperty' IN tnved;
generateTNVEDClassifierAction 'Сгенерировать файл импорта справочника' = ACTION CUSTOM 'lsfusion.erp.region.by.certificate.declaration.GenerateTNVEDClassifierActionProperty' IN tnved;
importTNVEDCustomsRatesAction 'Импортировать платежи' = ACTION CUSTOM 'lsfusion.erp.region.by.certificate.declaration.ImportTNVEDCustomsRatesActionProperty' IN tnved;
importTNVEDCustomsExceptionsAction 'Импортировать льготы' = ACTION CUSTOM 'lsfusion.erp.region.by.certificate.declaration.ImportTNVEDCustomsExceptionsActionProperty' IN tnved;

EXTEND FORM defaultData
    PROPERTIES() generateTNVEDClassifierAction, importTNVEDClassifierAction,
                 importTNVEDCustomsRatesAction, importTNVEDCustomsExceptionsAction
;

EXTEND DESIGN defaultData {
    pane {
        NEW customs {
            caption = 'ТН ВЭД';

            ADD PROPERTY(generateTNVEDClassifierAction);
            ADD PROPERTY(importTNVEDClassifierAction);
            ADD PROPERTY(importTNVEDCustomsRatesAction);
            ADD PROPERTY(importTNVEDCustomsExceptionsAction);
        }
    }
}
