MODULE PurchaseDemandSimple;

REQUIRE PurchaseDemand;

NAMESPACE Purchase;


recQuantity (Sku sku, UserOrder userOrder) =    totalReserve(customerStock(userOrder), sku, date(userOrder)) (+) 
                                                                            quantitySold(sku, userOrder) (-)
                                                                            prevCurrentReservePurchase(sku, customerStock(userOrder)) (-) 
                                                                            (prevCurrentBalance(sku, customerStock(userOrder)) IF prevCurrentBalance(sku, customerStock(userOrder)) > 0.0) ; 

recommendedQuantity (Sku sku, UserOrder userOrder) += round1(recQuantity(sku, userOrder)) IF recQuantity(sku, userOrder) > 0;
