MODULE PurchaseReturnOrderTerminal;

REQUIRE PurchaseReturnOrder, Terminal;

NAMESPACE PurchaseReturn;

@defineAddDetailDialogTerminal(userOrder, sku, customerStock);

EXTEND FORM userOrder
    PROPERTIES(o) addDetailDialogTerminalUserOrderDetail
;
DESIGN userOrder {
    import {
        NEW importTSD {
            caption = 'ТСД';
            type = CONTAINERV;
            MOVE PROPERTY(addDetailDialogTerminalUserOrderDetail(o));
        }
    }
}