MODULE Section;

REQUIRE Sku, CashRegister;

CLASS Section 'Секция';
TABLE Section (Section);

@defineExternalizable(section, VARSTRING[100]);

name 'Наименование' = DATA VARSTRING[255](Section) MINCHARWIDTH 10 PREFCHARWIDTH 20;
inactive 'Неактивный' = DATA BOOLEAN (Section);
active 'Активный' (Section section) = section IS Section AND NOT inactive(section);

dataIn 'Отм' = ABSTRACT BOOLEAN (Section, Sku);

defaultSection = GROUP MIN Section s IF s IS Section AND NOT inactive(s); 

FORM sections 'Секции' 
    OBJECTS s = Section
    PROPERTIES(s) id, name, inactive, NEW , DELETE 
;

NAVIGATOR {
    cashRegisterNavigator {
        NEW sections;
    }
}

FORM sectionsDialog 'Секции'
    OBJECTS s = Section
    PROPERTIES(s) READONLY id, name
    LIST Section OBJECT s
;