MODULE CashBookPrint;

REQUIRE CashBookIncome, CashBookOutcome;

NAMESPACE CashOperation;

countDocument(CashBookList l) = countIncome(l) (+) countOutcome(l);
FORM printCashBookList 'Кассовая книга'
    OBJECTS l = CashBookList PANEL
    PROPERTIES(l) listNumber, date, time, nameDepartmentStore, 
                  startBalance, endBalance,
                  sumIncome, sumOutcome,
                  countIncome, countOutcome, countDocument,
                  nameEmployee
    
    OBJECTS d = CashDocument
    PROPERTIES(d) dateTime, seriesNumber, subject, corrAccount
    PROPERTIES    sumIncome 'Приход' = sumCash[IncomeCashOrder](d),
                  sumOutcome 'Расход' = sumCash[OutcomeCashOrder](d)
    ORDERS dateTime(d)
    FILTERS cashBookList(d) = l
;

print 'Печать' (CashBookList l) {
    PRINT printCashBookList OBJECTS l = l;
}

EXTEND FORM cashBooks
    PROPERTIES(l) print TOOLBAR
;
