MODULE WBOrdersDBS;

REQUIRE WBStockMapping, WBItemMapping, SaleInternetOrder, WBPriceTransaction, WBOrdersFBS;

NAMESPACE WB;

// --------------------------------------Cборочные заказы DBS----------------------------------------------
//DBS (Direct by Seller):
//- Поставщик самостоятельно организует доставку заказов покупателям.
//- Wildberries предоставляет платформу для продаж, но логистика полностью на стороне поставщика.
//- Подходит для поставщиков, которые хотят контролировать весь процесс доставки.

isWBOrderDBS 'DBS' = DATA BOOLEAN (InternetOrder);

finalPrice = DATA LOCAL NUMERIC(INTEGER);
convertedFinalPrice = DATA LOCAL NUMERIC(INTEGER);

FORM importWBOrders

    OBJECTS orders = INTEGER

    PROPERTIES(orders) cargoType, groupId, nmId, finalPrice, rid, createdAt, isZeroOrder, price, convertedCurrencyCode,
        id, salePrice, article, convertedFinalPrice, convertedPrice, orderUid, warehouseId, comment, colorCode,
        chrtId, currencyCode

    OBJECTS skus = INTEGER
    PROPERTIES(skus) skus EXTID 'value'
    FILTERS imported(skus)
    FILTERS ordersSkus(skus) == orders
    PROPERTIES(orders) IN options isB2b
    FILTERS imported(orders)
    PROPERTIES(orders) IN address latitude, fullAddress, longitude

    OBJECTS requiredMeta = INTEGER
    PROPERTIES(requiredMeta) requiredMeta EXTID 'value'
    FILTERS imported(requiredMeta)
    FILTERS ordersRequiredMeta(requiredMeta) == orders
;

// https://marketplace-api.wildberries.ru/api/v3/dbs/orders/new
getOrdersDBSNew 'Получить список новых сборочных заданий' () {
    NEWSESSION {
        setHttpHeadersIS();
        LOCAL messageOrder = STRING ();
        LOCAL response = FILE();
        LOCAL error = STRING ();
        LOCAL statusText = STRING ();
        LOCAL status = STRING ();

        logToFile('WB', 'GET: ' + url(CategoryRequest.marketplace) + '/api/v3/dbs/orders/new');
        TRY {
            EXTERNAL HTTP GET url(CategoryRequest.marketplace) + '/api/v3/dbs/orders/new' HEADERS httpHeaders TO response;
            fileToString(response());
            logToFile('WB', resultString());
            IMPORT importWBOrders JSON FROM response();

            FOR INTEGER i = [GROUP MAX INTEGER i1 BY id(i1)](STRING number) AND NOT (GROUP MAX InternetOrder o IF number(o) == number AND carrier(o) == carrier('Own'))
                AND NOT (GROUP MAX InternetOrder o IF orderRidID(o) == rid(i) AND carrier(o) == carrier('Own')) INLINE DO NEW order = InternetOrder {
                number(order) <- number;
                orderRidID(order) <- rid(i);
                orderUID(order) <- orderUid(i);
                groupId(order) <- groupId(i);
                date(order) <- currentDate();
                isWBOrderDBS(order) <- TRUE;
                carrier(order) <- carrier('Own');
                status(order) <- StatusInternetOrder.new;

                IF NOT warehouse(warehouseId(i)) THEN messageOrder() <- 'В справочнике системы не найден warehouseId: ' + warehouseId(i);

                supplierStock(order) <- supplierStockWB(order);
                addressInternetCustomer(order) <- fullAddress(i);
                currency(order) <- GROUP MAX Currency c IF sid(c) == currencyCode(i);

                FOR INTEGER ii = [GROUP MAX INTEGER j BY rid(j)](STRING rid) AND Size size == size(chrtId(ii))
                    AND Item item == itemNM(nmId(ii)) AND itemWB(size) == item AND orderRidID(order) == rid INLINE DO NEW detail = InternetOrderDetail {
                    internetOrder(detail) <- order;
                    sku(detail) <- item(size);
                    price(detail) <- finalPrice(ii) / 100.0;
                }

            }
            messageOrder() <- (OVERRIDE messageOrder() + '\n', '') + messageStatusHTTP(STRING(statusHttp()));
        } CATCH {
            logToFile('WB', messageCaughtException());
            IF statusHttp() == 403 THEN {
                IMPORT importError JSON FROM response();
                extraDescriptionStatusHTTP() <- 'Список новых сборочных заданий не получен: ' + message();
            }
            messageOrder() <- CONCAT '\n', messageStatusHTTP(STRING(statusHttp())), messageCaughtException();
        } FINALLY {
            afterSendRequestIS();
            MESSAGE messageOrder() NOWAIT;
            APPLY;
        }
    }
}

firstName = DATA LOCAL STRING(INTEGER);
orderID = DATA LOCAL STRING (INTEGER);
phone = DATA LOCAL STRING(INTEGER);
phoneCode = DATA LOCAL NUMERIC(INTEGER);
replacementPhone = DATA LOCAL STRING(INTEGER);
additionalPhoneCodes = DATA LOCAL STRING(INTEGER);
ordersAdditionalPhoneCodes = DATA LOCAL INTEGER(INTEGER);

FORM importInfCustomer

    OBJECTS orders = INTEGER
    PROPERTIES(orders) firstName, orderID, phone, fullName, phoneCode, replacementPhone
    FILTERS imported(orders)

    OBJECTS additionalPhoneCodes = INTEGER
    PROPERTIES(additionalPhoneCodes) additionalPhoneCodes EXTID 'value'
    FILTERS imported(additionalPhoneCodes)
    FILTERS ordersAdditionalPhoneCodes(additionalPhoneCodes) == orders;

// https://marketplace-api.wildberries.ru/api/v3/dbs/orders/client
postInfCustomer 'Получить информацию о клиенте сборочных заданий' () {
    NEWSESSION {
        IF NOT (GROUP SUM 1 IF isSelected(InternetOrder order) AND isWBOrderDBS(order) AND carrier(order) == carrier('Own')) THEN {
            MESSAGE 'Заказ DBS не выбран.';
            RETURN ;
        }
        IF (GROUP SUM 1 IF isWBOrderDBS(InternetOrder order) AND order IS InternetOrder AND carrier(order) == carrier('Own')) THEN {
            setHttpHeadersIS();
            LOCAL messageOrder = STRING ();
            LOCAL response = FILE();
            LOCAL error = STRING ();
            LOCAL statusText = STRING ();
            LOCAL status = STRING ();

            logToFile('WB', 'POST: ' + url(CategoryRequest.marketplace) + '/api/v3/dbs/orders/client');

            EXPORT JSON FROM 'value' = INTEGER(number(InternetOrder order)) WHERE isSelected(order) AND isWBOrderDBS(order) AND carrier(order) == carrier('Own');
            fileToString(exportFile(), 'UTF-8');
            stringToFile('\{"orders":' + replace(resultString(), '\n', '') + '\}', 'UTF-8', 'json');
            TRY {
                EXTERNAL HTTP POST url(CategoryRequest.marketplace) + '/api/v3/dbs/orders/client' HEADERS httpHeaders PARAMS resultFile() TO response;
                fileToString(response());
                logToFile('WB', resultString());
                IMPORT importInfCustomer JSON FROM response();

                FOR INTEGER i = [GROUP MAX INTEGER i1 BY orderID(i1)](STRING number) AND InternetOrder order = (GROUP MAX InternetOrder o IF number(o) == number
                    AND carrier(o) == carrier('Own')) INLINE DO {
                    nameInternetCustomer(order) <- fullName(i);
                    phoneInternetCustomer(order) <- phone(i);
                }
                messageOrder() <- messageStatusHTTP(STRING(statusHttp()));
            } CATCH {
                logToFile('WB', messageCaughtException());
                IF statusHttp() == 400 OR statusHttp() == 403 OR statusHttp() == 404 THEN {
                    IMPORT importError JSON FROM response();
                    extraDescriptionStatusHTTP() <- 'Информация о клиентах сборочных заданий не получена: ' + message();
                }
                messageOrder() <- CONCAT '\n', messageStatusHTTP(STRING(statusHttp())), messageCaughtException();
            } FINALLY {
                afterSendRequestIS();
                MESSAGE messageOrder() NOWAIT;
                APPLY;
            }
        } ELSE {
            MESSAGE 'В списке нет сборочных заданий WB';
        }
    }
}

FORM statusInfoResponseDBS

    OBJECTS orders = INTEGER
    PROPERTIES(orders) orderId, supplierStatus, wbStatus

    OBJECTS errors = INTEGER
    PROPERTIES(errors) errors EXTID 'value'
    FILTERS ordersErrors(errors) == orders;

// https://marketplace-api.wildberries.ru/api/marketplace/v3/dbs/orders/status/info
getWbStatuses 'Получить статусы заказов' () {
    NEWSESSION NESTED LOCAL {
        IF NOT (GROUP SUM 1 IF isSelected(InternetOrder order) AND isWBOrderDBS(order) AND carrier(order) == carrier('Own')) THEN {
            MESSAGE 'Заказ DBS не выбран.';
            RETURN ;
        }

        setHttpHeadersIS();
        LOCAL messageOrder = STRING ();
        LOCAL response = FILE();
        LOCAL error = STRING ();
        LOCAL statusText = STRING ();
        LOCAL status = STRING ();

        logToFile('WB', 'POST: ' + url(CategoryRequest.marketplace) + '/api/marketplace/v3/dbs/orders/status/info');

        EXPORT JSON FROM 'value' = INTEGER(number(InternetOrder order)) WHERE isSelected(order) AND isWBOrderDBS(order) AND carrier(order) == carrier('Own');
        fileToString(exportFile(), 'UTF-8');
        stringToFile('\{"ordersIds":' + replace(resultString(), '\n', '') + '\}', 'UTF-8', 'json');
        fileToString(resultFile(), 'UTF-8');
        logToFile('WB', 'ordersIds: ' + resultString());

        TRY {
            EXTERNAL HTTP POST url(CategoryRequest.marketplace) + '/api/marketplace/v3/dbs/orders/status/info' HEADERS httpHeaders PARAMS resultFile() TO response;
            fileToString(response());
            logToFile('WB', resultString());
            messageOrder() <- messageStatusHTTP(STRING(statusHttp()));
            IF statusHttp() == 200 THEN {
                IMPORT statusInfoResponseDBS JSON FROM response();

                FOR orderId(INTEGER i) AND InternetOrder o == orderByNumber(orderId(i))
                    AND WbStatus ws = wbStatus(supplierStatus(i)) AND WbSystemStatus wss = wbSystemStatus(wbStatus(i)) DO {
                    IF wss = WbSystemStatus.declined_by_client AND status(o) = StatusInternetOrder.new AND subtractSeconds(dateTime(o), currentDateTime()) <= 3600 THEN {
                        IF customCancelOrder() THEN {
                            overCancelOrder(o);
                        } ELSE {
                            status(o) <- OVERRIDE customCancelOrderStatus(), StatusInternetOrder.closed;
                        }
                    }
                    wbStatus(o) <- ws;
                    wbSystemStatus(o) <- wss;
                    status(o) <- statusInternetOrder(ws);
                }
                APPLY NESTED LOCAL ;
            }
        } CATCH {
            logToFile('WB', messageCaughtException());
            IF statusHttp() == 400 OR statusHttp() == 403 OR statusHttp() == 404 OR statusHttp() == 409 THEN {
                IMPORT importError JSON FROM response();
                extraDescriptionStatusHTTP() <- 'Статус сборочного задания не получен: ' + message();
            }
            messageOrder() <- CONCAT '\n', messageStatusHTTP(STRING(statusHttp())), messageCaughtException();
        } FINALLY {
            afterSendRequestIS();
            //MESSAGE messageOrder() NOWAIT;
        }
    }
}

getWbStatus 'Получить статус заказа' (InternetOrder order) {
    IF NOT GROUP SUM 1 IF isSelected(InternetOrder order1) THEN {
        isSelected(order) <- TRUE ;
    }
    getWbStatuses();
}

requestId = DATA LOCAL STRING();
isError = DATA LOCAL BOOLEAN (INTEGER);
resultsErrors = DATA LOCAL INTEGER(INTEGER);
code = DATA LOCAL NUMERIC(INTEGER);
detail = DATA LOCAL STRING(INTEGER);

FORM changeStatusResponse
    PROPERTIES() requestId

    OBJECTS results = INTEGER
    PROPERTIES(results) isError, orderId
    FILTERS imported(results)

    OBJECTS errors = INTEGER
    FILTERS resultsErrors(errors) == results
    PROPERTIES(errors) code, detail
    FILTERS imported(errors);

wbCode = DATA STRING[10] (InternetOrder);

WHEN SET(isWBOrderDBS(InternetOrder o) AND isWBOrderDBS(o)) DO {
    wbCode(o) <- STRING[10](randInt(999999));
}

requestBody = DATA LOCAL NESTED FILE();

composeRequestBody(StatusInternetOrder status){
    IF status == StatusInternetOrder.cancel OR status == StatusInternetOrder.agreed OR status == StatusInternetOrder.delivery THEN
        {
            EXPORT JSON FROM 'value' = INTEGER(number(InternetOrder order)) WHERE isSelected(order) AND isWBOrderDBS(order) AND carrier(order) == carrier('Own') AND NOT status(order) == status;
            fileToString(exportFile(), 'UTF-8');
            stringToFile('\{"ordersIds":' + replace(resultString(), '\n', '') + '\}', 'UTF-8', 'json');
            fileToString(resultFile(), 'UTF-8');
            logToFile('WB', 'ordersIds: ' + resultString());
            requestBody() <- resultFile();
        }
    ELSE IF status == StatusInternetOrder.delivered OR status == StatusInternetOrder.closed THEN
        {

            EXPORT JSON FROM 'orders' = JSON FROM 'orderId' = INTEGER(number(InternetOrder order)), 'code' = wbCode(order) WHERE isSelected(order) AND isWBOrderDBS(order) AND carrier(order) == carrier('Own') AND NOT status(order) == status;
            fileToString(exportFile(), 'UTF-8');
            logToFile('WB', 'body: ' + resultString());
            requestBody() <- exportFile();

        }
}
customFilterChangeOrdersDBSStatus = ABSTRACT BOOLEAN (WbStatus, InternetOrder);
changeOrdersDBSStatusCondition (WbStatus ws, InternetOrder o) = 
    CASE WHEN ws = WbStatus.confirm AND wbStatus(o) = WbStatus.new AND NOT customFilterChangeOrdersDBSStatus(ws, o) THEN TRUE
         WHEN ws = WbStatus.deliver AND wbStatus(o) = WbStatus.confirm AND NOT customFilterChangeOrdersDBSStatus(ws, o) THEN TRUE
         WHEN ws = WbStatus.receive AND wbStatus(o) = WbStatus.deliver AND NOT customFilterChangeOrdersDBSStatus(ws, o) THEN TRUE
         WHEN ws = WbStatus.reject AND wbStatus(o) = WbStatus.deliver AND NOT customFilterChangeOrdersDBSStatus(ws, o) THEN TRUE
         WHEN ws = WbStatus.cancel AND (wbStatus(o) = WbStatus.new OR wbStatus(o) = WbStatus.confirm) AND NOT customFilterChangeOrdersDBSStatus(ws, o) THEN TRUE
;

changeOrdersDBSStatus (WbStatus wbStatus) {
    getWbStatuses();
    NEWSESSION NESTED LOCAL {
        LOCAL status = StatusInternetOrder ();
        LOCAL statusName = STRING ();
        LOCAL statusCaption = STRING ();
        status() <- statusInternetOrder(wbStatus);
        statusName() <- getWord(name(wbStatus), '.', 2);
        statusCaption() <- caption(wbStatus);
        
        IF NOT (GROUP SUM 1 IF isSelected(InternetOrder order) AND isWBOrderDBS(order) AND carrier(order) == carrier('Own')) THEN {
            MESSAGE 'Заказ DBS не выбран.';
            RETURN;
        }

        IF GROUP SUM 1 IF isSelected(InternetOrder order) AND status(order) == status() THEN {
            MESSAGE 'Один из выбранных заказов уже в статусе ' + statusCaption();
            RETURN;
        }

        IF GROUP SUM 1 IF isSelected(InternetOrder order) AND NOT changeOrdersDBSStatusCondition(wbStatus, order) THEN {
            MESSAGE 'Для одного из выбранных заказов не соблюдены условия перевода.';
            RETURN;
        }
        
        setHttpHeadersIS();
        LOCAL messageOrder = STRING ();
        LOCAL response = FILE();

        logToFile('WB', 'POST: ' + url(CategoryRequest.marketplace) + '/api/marketplace/v3/dbs/orders/status/' + statusName());

        composeRequestBody(status());

        TRY {
            EXTERNAL HTTP POST url(CategoryRequest.marketplace) + '/api/marketplace/v3/dbs/orders/status/' + statusName() HEADERS httpHeaders PARAMS requestBody() TO response;
            fileToString(response());
            logToFile('WB', resultString());
            messageOrder() <- messageStatusHTTP(STRING(statusHttp()));
            IF statusHttp() == 200 THEN {
                IMPORT changeStatusResponse JSON FROM response();
                FOR InternetOrder o = orderByNumber(orderId(INTEGER i)) DO{
                    IF NOT isError(i) THEN {
                        status(o) <- status();
                    wbStatus(o) <- wbStatus;
                } ELSE {
                        MESSAGE CONCAT ' ', 'Ошибка при обновлении статуса заказа', orderId(i), ':', detail(0);
                        messageOrder() <- messageStatusHTTP(STRING(code(0)));
                    }
                }
                APPLY NESTED LOCAL ;
            }
        } CATCH {
            logToFile('WB', messageCaughtException());
            IF statusHttp() == 400 OR statusHttp() == 403 OR statusHttp() == 404 OR statusHttp() == 409 THEN {
                IMPORT importError JSON FROM response();
                extraDescriptionStatusHTTP() <- 'Статус сборочного задания НЕ изменен: ' + message();
            }
            messageOrder() <- CONCAT '\n', messageStatusHTTP(STRING(statusHttp())), messageCaughtException();
        } FINALLY {
            afterSendRequestIS();
            MESSAGE messageOrder() NOWAIT;
        }
    }
}

// https://marketplace-api.wildberries.ru/api/marketplace/v3/dbs/orders/status/confirm
confirmOrdersDBS 'Перевести сборочные задания на сборку' () {
    changeOrdersDBSStatus(WbStatus.confirm);
}

confirmOrderDBS 'Перевести сборочное задание на сборку' (InternetOrder order) {
    IF NOT GROUP SUM 1 IF isSelected(InternetOrder order1) THEN {
        isSelected(order) <- TRUE ;
    }
    confirmOrdersDBS();
}

// https://marketplace-api.wildberries.ru/api/marketplace/v3/dbs/orders/status/cancel
cancelOrdersDBS 'Отменить сборочные задания' () {
    changeOrdersDBSStatus(WbStatus.cancel);
}

cancelOrderDBS 'Отменить сборочное задание' (InternetOrder order) {
    IF NOT GROUP SUM 1 IF isSelected(InternetOrder order1) THEN {
        isSelected(order) <- TRUE ;
    }
    cancelOrdersDBS();
}

// https://marketplace-api.wildberries.ru/api/marketplace/v3/dbs/orders/status/deliver
deliverOrdersDBS 'Перевести сборочные задания в доставку' () {
    changeOrdersDBSStatus(WbStatus.deliver);
}

deliverOrderDBS 'Перевести сборочное задание в доставку' (InternetOrder order) {
    IF NOT GROUP SUM 1 IF isSelected(InternetOrder order1) THEN {
        isSelected(order) <- TRUE ;
    }
    deliverOrdersDBS();
}

// https://marketplace-api.wildberries.ru/api/marketplace/v3/dbs/orders/status/receive
receiveOrdersDBS 'Сообщить о получении заказов' () {
    changeOrdersDBSStatus(WbStatus.receive);
}

receiveOrderDBS 'Сообщить о получении заказа' (InternetOrder order) {
    IF NOT GROUP SUM 1 IF isSelected(InternetOrder order1) THEN {
        isSelected(order) <- TRUE ;
    }
    receiveOrdersDBS();
}

// https://marketplace-api.wildberries.ru/api/marketplace/v3/dbs/orders/status/reject
rejectOrdersDBS 'Сообщить об отказе от заказов' () {
    changeOrdersDBSStatus(WbStatus.reject);
}

rejectOrderDBS 'Сообщить об отказе от заказа' (InternetOrder order) {
    IF NOT GROUP SUM 1 IF isSelected(InternetOrder order1) THEN {
        isSelected(order) <- TRUE ;
    }
    rejectOrdersDBS();
}

//----Stickers-----//

// https://marketplace-api.wildberries.ru/api/marketplace/v3/dbs/orders/stickers
getStickersDBS 'Получить стикеры' () {
    NEWSESSION NESTED LOCAL {
        IF NOT (GROUP SUM 1 IF isSelected(InternetOrder order) AND isWBOrderDBS(order) AND carrier(order) == carrier('Own')) THEN {
            MESSAGE 'Заказ DBS не выбран.';
            RETURN ;
        }

        setHttpHeadersIS();
        LOCAL messageOrder = STRING ();
        LOCAL response = FILE();
        LOCAL error = STRING ();
        LOCAL statusText = STRING ();
        LOCAL status = STRING ();

        logToFile('WB', 'POST: ' + url(CategoryRequest.marketplace) + '/api/marketplace/v3/dbs/orders/stickers');

        EXPORT JSON FROM 'value' = INTEGER(number(InternetOrder order)) WHERE isSelected(order) AND isWBOrderDBS(order) AND carrier(order) == carrier('Own');
        fileToString(exportFile(), 'UTF-8');
        stringToFile('\{"orders":' + replace(resultString(), '\n', '') + '\}', 'UTF-8', 'json');
        fileToString(resultFile(), 'UTF-8');
        logToFile('WB', 'orders: ' + resultString());

        TRY {
            EXTERNAL HTTP POST url(CategoryRequest.marketplace) + '/api/marketplace/v3/dbs/orders/stickers' HEADERS httpHeaders PARAMS resultFile() TO response;
            fileToString(response());
            logToFile('WB', resultString());
            messageOrder() <- messageStatusHTTP(STRING(statusHttp()));
            IF statusHttp() == 200 THEN {
                IMPORT stickersResponse JSON FROM response();
                FOR orderId(INTEGER i) DO {
                    sticker(orderByNumber(orderId(i))) <- RAWFILE(file(decode(file(i), 'base64'), 'pdf'));; 
                }
                APPLY NESTED LOCAL ;
            }
        } CATCH {
            logToFile('WB', messageCaughtException());
            IF statusHttp() == 400 OR statusHttp() == 403 OR statusHttp() == 404 OR statusHttp() == 409 THEN {
                IMPORT importError JSON FROM response();
                extraDescriptionStatusHTTP() <- 'Статус сборочного задания не получен: ' + message();
            }
            messageOrder() <- CONCAT '\n', messageStatusHTTP(STRING(statusHttp())), messageCaughtException();
        } FINALLY {
            afterSendRequestIS();
            MESSAGE messageOrder() NOWAIT;
        }
    }
}

getStickerDBS 'Получить стикер' (InternetOrder order) {
    IF NOT GROUP SUM 1 IF isSelected(InternetOrder order1) THEN {
        isSelected(order) <- TRUE ;
    }
    getStickersDBS();
}

EXTEND FORM internetOrders
    PROPERTIES(o) READONLY isWBOrderDBS AFTER isWBOrder(o)
    PROPERTIES(o) isSelected FIRST, confirmOrderDBS, deliverOrderDBS, receiveOrderDBS, cancelOrderDBS, rejectOrderDBS, getWbStatus
    PROPERTIES() getOrdersDBSNew, postInfCustomer
;

DESIGN internetOrders {
    wbContainer {
        NEW ordersDBS {
            caption = 'Сборочные задания DBS';
            MOVE PROPERTY (getOrdersDBSNew());
            MOVE PROPERTY (postInfCustomer());
        }
        NEW ordersActions {
            caption = 'Действия по заданиям';
            MOVE PROPERTY (confirmOrderDBS(o));
            MOVE PROPERTY (cancelOrderDBS(o));
            MOVE PROPERTY (deliverOrderDBS(o));
            MOVE PROPERTY (receiveOrderDBS(o));
            MOVE PROPERTY (rejectOrderDBS(o));
            MOVE PROPERTY (getWbStatus(o));
        }
    }
}