MODULE EGAISGestori;

REQUIRE EGAIS;

NAMESPACE EGAIS;

fsrarId 'FSRAR_ID' = DATA STRING (UTM) CHARWIDTH 12;
fsrarIdDateTime 'Дата и время запроса FSRAR_ID' = DATA DATETIME (UTM);

EXTEND FORM UTM
    PROPERTIES(o) fsrarId, fsrarIdDateTime READONLY
;

EXTEND FORM dialogUTMs
    PROPERTIES(o) READONLY fsrarId
;

EXTEND FORM integrationData
    PROPERTIES() EGAISTestMode
    PROPERTIES(utm) READONLY fsrarId, fsrarIdDateTime
;

DESIGN integrationData {
    EGAISParams {
        MOVE PROPERTY(EGAISTestMode());
    }
}