MODULE EDocumentEDSTopBy;

REQUIRE EDocumentEDS, EDSTopBy;

NAMESPACE EDI;

aliasEDSServiceSender (EDocument d) = OVERRIDE aliasEDSService(currentUser()), aliasEDSService(sender(d));
passwordEDSServiceSender (EDocument d) = OVERRIDE passwordEDSService(currentUser()), passwordEDSService(sender(d));

aliasEDSServiceReceiver (EDocument d) = OVERRIDE aliasEDSService(currentUser()), extraAliasEDSService(receiver(d)) IF useExtraAlias(receiver(d)), aliasEDSService(receiver(d));
passwordEDSServiceReceiver (EDocument d) = OVERRIDE passwordEDSService(currentUser()), extraPasswordEDSService(receiver(d)) IF useExtraAlias(receiver(d)), passwordEDSService(receiver(d));

EDSServiceSenderTopBy (EDocument d) = OVERRIDE EDSServiceTopBy(currentUser()), EDSServiceTopBy(sender(d));
EDSServiceReceiverTopBy (EDocument d) = OVERRIDE EDSServiceTopBy(currentUser()), EDSServiceTopBy(receiver(d));

EDSServiceSender(STRING[100] provider, EDocument d) += WHEN provider == 'TopBy' AND d IS EDocument THEN EDSServiceSenderTopBy(d);
EDSServiceReceiver(STRING[100] provider, EDocument d) += WHEN provider == 'TopBy' AND d IS EDocument THEN EDSServiceReceiverTopBy(d);


sendRequestEDSSender(STRING[100] provider, EDocument d, FILE file) {
    sendRequestEDI('eds', 'eds', ('http://' + host(EDSServiceSender(provider,d)) + ':' + port(EDSServiceSender(provider,d)) + '/eds/services/EDSService?wsdl'), file, TRUE, client(EDSServiceSender(provider,d)));
}
sendRequestEDSReceiver(STRING[100] provider, EDocument d, FILE file) {
    sendRequestEDI('eds', 'eds', ('http://' + host(EDSServiceReceiver(provider,d)) + ':' + port(EDSServiceReceiver(provider,d)) + '/eds/services/EDSService?wsdl'), file, TRUE, client(EDSServiceReceiver(provider,d)));
}