MODULE SaleReturnShipmentBox;

REQUIRE Box, SaleReturnShipment, SaleShipmentBox;

NAMESPACE SaleReturn;

//---------------------------------Ячейка ----------------------------------//

@defineDocumentInterfaceDetailBox(shipment);
overCopyUserShipmentDetail(d, detail) += ACTION (d, detail) {      
    boxUserShipmentDetail(d) <- boxUserShipmentDetail(detail);
}
@extendFormInterfaceDetailBox(shipment, s, , quantity);
@deriveDocumentOperationProperty(UserShipment, showBox);

//-- invoice
@defineInvoiceShipmentBox(supplierStock);
@deriveDocumentOperationProperty(UserInvoice, showBox);

