MODULE PurchaseReturnShipmentBox;

REQUIRE Box, PurchaseReturnShipment, PurchaseShipmentBox;

NAMESPACE PurchaseReturn;

//--------------------------------- Короб  ----------------------------------//

@defineDocumentInterfaceDetailBox(shipment);
overCopyUserShipmentDetail(d, detail) += ACTION (d, detail) {      
    boxUserShipmentDetail(d) <- boxUserShipmentDetail(detail);
}
@extendFormInterfaceDetailBox(shipment, s, , quantity);

@deriveDocumentOperationProperty(UserShipment, showBox);

//-- invoice
@defineInvoiceShipmentBox(customerStock);
@deriveDocumentOperationProperty(UserInvoice, showBox);
