MODULE NativeMachinery;

REQUIRE MachineryPriceTransaction;

NAMESPACE Machinery;

sendDeltaRests ABSTRACT LIST (MachineryPriceTransaction);

sendMachineryPriceTransaction ABSTRACT LIST (MachineryPriceTransaction);

receiveGroupMachinery ABSTRACT LIST (GroupMachinery);


sendMachineryPriceTransactions 'Загрузка прайса в оборудование (native)' () {
    FOR process(MachineryPriceTransaction t) AND left(handlerModel(groupMachinery(t)), 4) = 'lsf.' DO
        sendMachineryPriceTransaction(t);
}

receiveGroupsMachinery 'Получение данных из оборудования (native)' () {
    FOR GroupMachinery g IS GroupMachinery AND left(handlerModel(g), 4) = 'lsf.' DO
        receiveGroupMachinery(g);
}

//EXTEND FORM machineryPriceTransactions PROPERTIES sendMachineryPriceTransactions(), receiveGroupsMachinery();