MODULE ComplianceGroupArticle;

REQUIRE ComplianceGroupItem, ItemArticle;

NAMESPACE Compliance;

//-- Группа сертификации
complianceGroup = DATA ComplianceGroup(Country, Article);
nameComplianceGroup 'Группа сертификации' (Country country, Article article) = name(complianceGroup(country, article)) MINCHARWIDTH 30 PREFCHARWIDTH 40;
nameComplianceGroupDefaultCountry 'Группа сертификации' (Article article) = name(complianceGroup(defaultCountry(), article)) MINCHARWIDTH 10 PREFCHARWIDTH 15;

changeComplianceGroupDefaultCountry(Article article) = ACTION {
    REQUEST OBJECT cg
    SHOW complianceGroups DIALOG SHOWDROP;
    IF formResult() == FormResult.ok THEN {
        complianceGroup(Country country, article) <- requestedObject() WHERE country == defaultCountry();

    } ELSE IF formResult() == FormResult.drop THEN {
        complianceGroup(Country country, article) <- NULL WHERE country == defaultCountry();
    }
}

EXTEND FORM article
    PROPERTIES(a)    nameComplianceGroupDefaultCountry  ON CHANGE changeComplianceGroupDefaultCountry(a)
    PROPERTIES(c, a) nameComplianceGroup

    PROPERTIES (i) BEFORE deletei nameComplianceGroupDefaultCountry ON CHANGE changeComplianceGroupCountry(i)
;
DESIGN article  {
    regionPrm {
        MOVE PROPERTY(nameComplianceGroupDefaultCountry(a));
    }
}

WHEN SESSION FORMS article CHANGED(complianceGroup(Country country, Article article)) DO         
    complianceGroup(country, Item i) <- complianceGroup(country, article) WHERE article(i) == article; 

WHEN SESSION FORMS article SET(Item i IS Item) DO
    complianceGroup(Country country, i) <- complianceGroup(country, article(i)); 


EXTEND FORM articles
    PROPERTIES(a)  READONLYIF isReadonly() BEFORE deletea nameComplianceGroupDefaultCountry
;
