MODULE EGAISClientGestori;

REQUIRE EGAISClient, EGAISGestori, EGAISUTMGestori, TextHighlight;

NAMESPACE EGAIS;

synchronized 'Синхронизирован' = DATA BOOLEAN (Client);

CONSTRAINT SETCHANGED(utm(Client t)) AND fsrarId(utm(t)) AND NOT fsrarId(utm(t)) == id(t)
    MESSAGE 'Нельзя связывать УТМ с организацией у которой FSRAR_ID отличается от FSRAR_ID УТМ';

show 'Просмотреть' (Client c)  {
    NEWSESSION {
        SHOW client OBJECTS o = c DOCKED READONLY;
    }
}

hideEdit (Client c) += synchronized(c);

hideDelete (Client c) += synchronized(c);
hideDelete (Client c) += TRUE IF utm(c);

EXTEND FORM clients
    PROPERTIES show(o) SHOWIF synchronized(o)
;

overChangeOwn(Client c) +{
    utm(c) <- NULL;
}

clientsFull 'Клиенты' (UTM u) = 
    GROUP CONCAT
        (CONCAT ' / ', id(Client c), shortName(c), INN(c), KPP(c))
        IF utm(c) = u, ', ' ORDER c CHARWIDTH 60;

EXTEND FORM integrationData
    PROPERTIES(utm) READONLY clientsFull
;

DESIGN integrationData {
    REMOVE PROPERTY(clients(utm));
}

FORM dialogClientsForUtm 'Организации'
    OBJECTS u = UTM PANEL

    OBJECTS o = Client
    PROPERTIES(o) READONLY id, shortName, INN, KPP
    FILTERS NOT fsrarId(u) OR id(o) = fsrarId(u)

    LIST Client OBJECT o
;

addClientToUtm 'Привязать клиента' (UTM u) {
    DIALOG dialogClientsForUtm OBJECTS u = u, o INPUT DO {
        utm(o) <- u;
    }
}

removeClientFromUtm 'Отвязать' (Client c) {
    utm(c) <- NULL;
} CONFIRM;

EXTEND FORM UTM
    PROPERTIES(o) addClientToUtm DRAW c TOOLBAR
    PROPERTIES(c) removeClientFromUtm TOOLBAR
;

EXTEND FORM client
    PROPERTIES(o) hlxml = xml CUSTOM 'xmlHighlight'
;

DESIGN client {
    xml {
        REMOVE PROPERTY(xml(o));
        MOVE PROPERTY(hlxml) { fill = 1; panelCaptionVertical = TRUE; }
    }
}
