MODULE DiscountCardSaleLedger;

REQUIRE ZReportDiscountCard, SaleLedger;

NAMESPACE DiscountCard;

EXTEND FORM discountCards
    OBJECTS l=SaleLedger
    PROPERTIES(l) READONLY nameDOWSaleLedger, dateTimeSaleLedger,  
                           nameStockSaleLedger, nameSkuSaleLedger, descriptionSaleLedger, numberDocumentSaleLedger,
                           quantitySaleLedger, costSumSaleLedger, markupSumSaleLedger, valueVATSaleLedger,
                           sumVATSaleLedger, sumSaleLedger, averagePriceSaleLedger   
    ORDER BY dateTimeSaleLedger(l)                        
    FILTERS discountCardReceiptDetail(l)==d OR discountCardReceipt(receiptSaleReceiptReturnDetail(l))==d                           
    
;
EXTEND DESIGN discountCards {
    main {
        ADD d.box;
        ADD l.box;
        ADD functions.box;
    }
}