MODULE GiftCardReceiptDetailPayment;

REQUIRE ZReportReceiptDetailPayment, GiftCard;

NAMESPACE GiftCard;

sumCash 'Сумма (наличные)' (giftCard) = GROUP BY GiftCard giftCard SUM sum(sold(giftCard), Payment payment) IF 
    paymentMeans(paymentType(payment))==  PaymentMeans.paymentMeansCash AND isPosted[ReceiptDetail](sold(giftCard));

EXTEND FORM giftCards
    PROPERTIES(g) READONLYIF isReadonly() sumCash
;

sumCard 'Сумма (карточка)' (giftCard) = GROUP BY GiftCard giftCard SUM sum(sold(giftCard), Payment payment) IF 
    paymentMeans(paymentType(payment))==  PaymentMeans.paymentMeansCard AND isPosted[ReceiptDetail](sold(giftCard));

EXTEND FORM giftCards
    PROPERTIES(g) READONLYIF isReadonly() sumCard
;

sumGiftCardReceiptDetail 'Сумма (сертификат) по товарам' (ZReport zReport, Range range) = sumSkuReceiptDetail(zReport, PaymentMeans.paymentMeansGiftCard, range);