MODULE LotExtra;

REQUIRE Lot;

NAMESPACE Lot;

weight 'Вес' = DATA NUMERIC (Lot); 

TABLE lotImage (Lot);
image 'Изображение' = DATA IMAGEFILE (Lot) TABLE lotImage;

EXTEND FORM lot
    PROPERTIES(l) weight, image
;

DESIGN lot {
    params {
        MOVE PROPERTY(weight(l));
    }
    tabbedPane {
        NEW image {
            caption = 'Изображение';
            MOVE PROPERTY(image(l)) { fill = 1; caption = ''; };
        }
    }
}

EXTEND FORM lots
    PROPERTIES(l) READONLY weight
    
    PROPERTIES(l) READONLY PANEL image
;

DESIGN lots {
    tabbedPane {
        NEW image {
            MOVE PROPERTY(image(l)) { fill = 1; caption = ''; };
        }
    }
}