MODULE EGAISActChargeOnShopLedger;

REQUIRE EGAISActChargeOnShop, EGAISFRegLedger, EGAISFRegShopLedger;

NAMESPACE EGAIS;

EXTEND CLASS ActChargeOnShopPosition : FRegShopLedger;

posted(ActChargeOnShopPosition l) += posted(l);

client(ActChargeOnShopPosition l) += client(l);

date(ActChargeOnShopPosition l) += date(l);
number(ActChargeOnShopPosition l) += number(l);

product(ActChargeOnShopPosition l) += product(l);

quantity(ActChargeOnShopPosition l) += quantity(l);