MODULE RevaluationDisparityManufacturingPrice;

REQUIRE RevaluationDisparity, DisparityManufacturingPrice, RevaluationManufacturingPrice;

showIfManufacturingPriceDisparityDetail (d) += WHEN createRevaluationDisparityDetail(d) THEN TRUE;

curManufacturingPriceRevaluationDetail(detail) += curInputManufacturingPriceDisparityDetail(disparityDetailDisparityRevaluationDetail(detail));
curManufacturingSumRevaluationDetail(detail) += curInputManufacturingSumDisparityDetail(disparityDetailDisparityRevaluationDetail(detail));

manufacturingPriceRevaluationDetail(detail) += afterInputManufacturingPriceDisparityDetail(disparityDetailDisparityRevaluationDetail(detail));
manufacturingSumRevaluationDetail(detail) += afterInputManufacturingSumDisparityDetail(disparityDetailDisparityRevaluationDetail(detail));

backgroundCurInputManufacturingPriceDisparityDetail (d) += WHEN createRevaluationDisparityDetail(d) THEN RGB(250, 218, 221);
backgroundAfterInputManufacturingPriceDisparityDetail (d) += WHEN createRevaluationDisparityDetail(d) THEN RGB(250, 218, 221);