MODULE FiscalVMKInvoicePayment;

REQUIRE FiscalVMKPOS, POSInvoice;

fiscalVMKPrint 'Напечатать оплату'  INTERNAL  'lsfusion.erp.region.by.machinery.cashregister.fiscalvmk.FiscalVMKPrintInvoicePaymentAction' (Sale.Invoice, Payment.Payment);
printReceipt(Sale.Invoice invoice, Payment.Payment payment) + {  IF sidModelCurrentCashRegister() == 'VMK' THEN fiscalVMKPrint(invoice, payment); }

fiscalVMKPrintReturn 'Напечатать возврат'  INTERNAL  'lsfusion.erp.region.by.machinery.cashregister.fiscalvmk.FiscalVMKPrintReturnInvoicePaymentAction' (Sale.Invoice, Payment.Payment);
printReturnReceipt(Sale.Invoice invoice, Payment.Payment payment) + {  IF sidModelCurrentCashRegister() == 'VMK' THEN fiscalVMKPrintReturn(invoice, payment); }
