MODULE FiscalAbsolutInvoicePayment;

REQUIRE FiscalAbsolut, POSInvoice;

fiscalAbsolutPrint 'Напечатать оплату'  INTERNAL  'lsfusion.erp.region.by.machinery.cashregister.fiscalabsolut.FiscalAbsolutPrintInvoicePaymentAction' (Sale.Invoice, Payment.Payment);
printReceipt(Sale.Invoice invoice, Payment.Payment payment) + {  IF sidModelCurrentCashRegister() == 'Absolut' THEN fiscalAbsolutPrint(invoice, payment); }

fiscalAbsolutPrintReturn 'Напечатать возврат'  INTERNAL  'lsfusion.erp.region.by.machinery.cashregister.fiscalabsolut.FiscalAbsolutPrintReturnInvoicePaymentAction' (Sale.Invoice, Payment.Payment);
printReturnReceipt(Sale.Invoice invoice, Payment.Payment payment) + {  IF sidModelCurrentCashRegister() == 'Absolut' THEN fiscalAbsolutPrintReturn(invoice, payment); }
