MODULE PricingPurchasePharmacy;

REQUIRE PricingPurchasePriceDivider, ItemPharmacy;

NAMESPACE Purchase;

blisterAmount 'Кол-во блистеров (в ед.)' (UserInvoiceDetail detail) = blisterAmount(sku(detail)) MINCHARWIDTH 3 PREFCHARWIDTH 6;              

EXTEND FORM userInvoice
    PROPERTIES (d) READONLY blisterAmount AFTER idBarcodeSku(d)    
;

EXTEND FORM invoices
    PROPERTIES (d) READONLY blisterAmount FORCE GRID AFTER idBarcodeSku(d)    
;              

priceDivider(UserInvoiceDetail detail) += blisterAmount(detail);