MODULE PurchaseSaleCreditNoteDetail;

REQUIRE PurchaseSaleCreditNote;

NAMESPACE Purchase;

overFillCreditNote(Sale.UserCreditNoteDetail sd, Purchase.CreditNoteDetail pd) + {
    invoiceDetail(sd) <- invoiceDetail(invoiceDetail[Purchase.InvoiceCreditNoteDetail](pd));
}
overFillCreditNoteDetail(Sale.UserCreditNoteDetail sd, Purchase.CreditNoteDetail pd) + {
    invoiceDetail(sd) <- invoiceDetail(invoiceDetail[Purchase.InvoiceCreditNoteDetail](pd));
}