MODULE ZReportSkuLedger;

REQUIRE ZReport,SkuLedger, ZReportStockDocument;

// -------------Проведение по регистрам --------------------- //

@implementSaleLedger(ReceiptSale, sku, departmentStore);
costSaleLedgerBatch(ledger, batch) +=  costSkuLedgerBatch(ledger, batch) IF ledger IS ReceiptSaleDetail; //quantityReceiptSaleDetail(ledger) IF  batchReceiptSaleDetail(ledger)== batch;
quantitySaleLedger (ledger) += quantityReceiptSaleDetail(ledger);
VATSaleLedger (ledger) += VATReceiptSaleDetail(ledger);
sumSaleLedger (ledger) += sumReceiptSaleDetail(ledger);
costSumSaleLedger (ledger) += costSumSkuLedger(ledger) IF ledger IS ReceiptSaleDetail;

@implementSaleLedger(ReceiptReturn, sku, departmentStore);
costSaleLedgerBatch(ledger, batch) += -costSkuLedgerBatch(ledger, batch) IF ledger IS ReceiptReturnDetail;//quantityReceiptReturnDetail(ledger) IF  batchReceiptReturnDetail(ledger)== batch;
quantitySaleLedger (ledger) += -quantityReceiptReturnDetail(ledger);
VATSaleLedger (ledger) += VATReceiptReturnDetail(ledger);
sumSaleLedger (ledger) += -sumReceiptReturnDetail(ledger);
costSumSaleLedger (ledger) += -costSumSkuLedger(ledger) IF ledger IS ReceiptReturnDetail;

editSaleLedger (ledger) += ACTION editReceiptSaleDetail(ledger);
editSaleLedger (ledger) += ACTION editReceiptReturnDetail(ledger);

// -------------Проведение по регистрам --------------------- //

@implementSkuLedgerOutFIFO(ReceiptSaleDetail, sku, departmentStore);
quantityOutFIFOSkuLedger (ledger) += quantityReceiptSaleDetail(ledger);
batchSkuLedger(ledger) += batchReceiptSaleDetail(ledger);
@implementSkuLedgerOutFIFOBatchBalance(receiptSaleDetail, departmentStore);
sumOutSkuLedger (ledger) += sumReceiptSaleDetail(ledger) (+) discountSumReceiptSaleDetail(ledger);
skipSkuLedger(ledger) += skipReceiptSaleDetail(ledger);

@implementSkuLedgerInLIFO(ReceiptReturnDetail, sku, departmentStore);
quantityInLIFOSkuLedger (ledger) += quantityReceiptReturnDetail(ledger);
batchSkuLedger(ledger) += batchReceiptReturnDetail(ledger);
@implementSkuLedgerInLIFOBatchBalance(receiptReturnDetail, departmentStore);
sumInSkuLedger (ledger) += sumReceiptReturnDetail(ledger) (+) discountSumReceiptReturnDetail(ledger);
skipSkuLedger(ledger) += skipReceiptReturnDetail(ledger);

editSkuLedger(d) += ACTION editReceiptReturnDetail(d);
editSkuLedger(d) += ACTION editReceiptSaleDetail(d);

EXTEND FORM zReports
    PROPERTIES (d) READONLY costSumSkuLedger FORCE GRID AFTER priceReceiptDetail(d)
;

stockDocumentLedgerSkuLedger (ledger) += zReportReceiptSaleDetail(ledger);
stockDocumentLedgerSkuLedger (ledger) += zReportReceiptReturnDetail(ledger);
