MODULE ZReport;

REQUIRE System,
        Utils,
        Document,
        Retail,
        Currency,
        Store,
        StoreSkuLedger,
        Stock,
        StockTax,
        CashRegister,
        SaleLedger,
        PriceRoundStore,
        PriceListType,
        StockSkuDocument,
        Item;
        
// ------------------------------------- Объявление Z-отчета ---------------------------------------- //

CLASS ZReport 'Z-отчет (открытый)';
TABLE zReport (ZReport);

@defineExternalizable(zReport, VARSTRING[100]);
@defineDocumentHeaderTime(ZReport);
@defineDocumentHeaderCreated(ZReport);

@defineDocumentHeaderPosted(ZReport);
@defineDocumentHeaderClosed(ZReport);
@defineDocumentClosedConstraint(ZReport);

@deriveDocumentHeaderTimePrefix(ZReport, );
@defineDocumentHeaderDepartmentStore(zReport);

@defineDocumentHeaderNumber(ZReport);

idDepartmentStore 'Код' (ZReport zReport) = id(departmentStore(zReport));

cashRegister (zReport) = DATA CashRegister(ZReport);
numberCashRegister 'Касса Z-отчета' (ZReport zReport) = npp(cashRegister(zReport)) IN documentPrm;
overNumberCashRegister 'Касса Z-отчета' (ZReport zReport) = overNpp(cashRegister(zReport)) IN documentPrm;

basis 'Основание' (ZReport zReport) = 'Z-отчет №' + number(zReport) + ' с кассы ' + overNumberCashRegister(zReport) + ' от ' + date(zReport) IN documentPrm;

departmentStore(ZReport zReport) <- departmentStore(cashRegister(zReport))
    WHEN CHANGED(cashRegister(zReport));

description 'Название документа' (ZReport zReport) =  VARSTRING[200] (CONCAT '', 'Продажа по кассе ' +overNumberCashRegister(zReport),
                                            ' отдела ' + nameDepartmentStore(zReport),
                                            ' от ' + date(zReport));
    
succeededExtraCheck 'Проверено' (zReport) = DATA BOOLEAN(ZReport);   
//----------------------------------------------- Чеки ---------------------------------------------------//

CLASS Receipt 'Чек';
TABLE receipt (Receipt);

@defineCreated(Receipt);
@defineExternalizable(receipt, VARSTRING[100]);


CLASS ABSTRACT ReceiptDetail 'Строка чека';
TABLE receiptDetail (ReceiptDetail);

CLASS ReceiptSaleDetail 'Строка продажи' : ReceiptDetail;
TABLE receiptSaleDetail (ReceiptSaleDetail);
is(ReceiptSaleDetail receiptSaleDetail) = receiptSaleDetail IS ReceiptSaleDetail;

CLASS ReceiptReturnDetail 'Строка возврата' : ReceiptDetail;
TABLE receiptReturnDetail (ReceiptReturnDetail);
is(ReceiptReturnDetail receiptReturnDetail) = receiptReturnDetail IS ReceiptReturnDetail;

@defineExternalizable(receiptDetail, VARSTRING[100]);

number 'Номер позиции чека' = DATA INTEGER (ReceiptDetail); 

@defineDocumentRelation(zReport, Receipt);
numberZReport 'Номер Z-отчета' (Receipt receipt) = number(zReport(receipt)) IN recognize;
cashRegister (Receipt receipt) = cashRegister(zReport(receipt));
numberCashRegister 'Номер кассы' (Receipt receipt) = npp(cashRegister(receipt)) IN recognize;
overNumberCashRegister 'Номер кассы' (Receipt receipt) = overNpp(cashRegister(receipt)) IN recognize;
numberGroupCashRegister 'Номер кассы' (Receipt receipt) = nppGroupMachinery(cashRegister(receipt)) IN recognize;

groupCashRegister (Receipt receipt) = groupCashRegister(cashRegister(receipt)) COMPLEX;

cashRegisterModel (Receipt receipt) = cashRegisterModel(groupCashRegister(cashRegister(receipt)));
sidCashRegisterModel 'Код модели' (Receipt receipt) = sid(cashRegisterModel(receipt));

employee = DATA Employee(Receipt);
idEmployee (Receipt receipt) = id(employee(receipt));
firstNameEmployee (Receipt receipt) = firstName(employee(receipt));
lastNameEmployee (Receipt receipt) = lastName(employee(receipt));
nameEmployee 'Кассир' (Receipt receipt) = name[Contact](employee(receipt));
employee(Receipt receipt) <- currentUser() WHEN SET(receipt IS Receipt);

@defineDocumentHeaderTime(Receipt);
@deriveDocumentHeaderTimePrefix(Receipt, );

@defineDocumentDetailDepartmentStoreCustom(zReport, receipt);
@defineDocumentDetailPosted(zReport, Receipt);
@defineDocumentDetailClosed(zReport, Receipt);

idDepartmentStore 'Отдел магазина' (Receipt idetail) = id(departmentStore(idetail));    
    

skip 'Не проводить по регистру' = DATA BOOLEAN (Receipt); 

@defineDocumentRelation(receipt, ReceiptSaleDetail);
@defineDocumentRelation(receipt, ReceiptReturnDetail);

@defineDocumentHeaderCurrency (receipt);
@deriveDocumentCurrency (receipt, departmentStore);

@defineDocumentHeaderNote(Receipt);

@defineDocumentDetailCurrency (receipt, receiptSaleDetail);
@defineDocumentDetailCurrency (receipt, receiptReturnDetail);

receipt = ABSTRACT Receipt (ReceiptDetail) PERSISTENT;
receipt(ReceiptReturnDetail detail) += receipt(detail);
receipt(ReceiptSaleDetail detail) += receipt(detail);

zReport(ReceiptSaleDetail d) = zReport(receipt(d)); 
zReport(ReceiptReturnDetail d) = zReport(receipt(d)); 
zReport (ReceiptDetail d) = zReport(receipt(d));
numberZReport 'Номер Z-отчета'(ReceiptDetail d) = number(zReport(d));

sidCashRegisterModel 'Код модели' (ReceiptDetail receiptDetail) = sidCashRegisterModel(receipt(receiptDetail));
numberCashRegister 'Номер кассы' (ReceiptDetail receiptDetail) = overNumberCashRegister(receipt(receiptDetail));

type 'Тип' = ABSTRACT STRING[10] (ReceiptDetail) MINCHARWIDTH 10 PREFCHARWIDTH 12 PERSISTENT;
type(ReceiptSaleDetail detail) += 'Продажа' IF detail IS ReceiptSaleDetail;
type(ReceiptReturnDetail detail) += 'Возврат' IF detail IS ReceiptReturnDetail;

index 'Номер строки' (ReceiptDetail d) =
    PARTITION SUM 1 BY receipt(d)
    ORDER d MINCHARWIDTH 4 PREFCHARWIDTH 4;

@defineDocumentDetailTime(receipt, ReceiptSaleDetail);
dateZReport 'Дата Z-отчета'(ReceiptSaleDetail d) = date(zReport(receipt(d)));

@defineDocumentDetailTime(receipt, ReceiptReturnDetail);
dateZReport 'Дата Z-отчета'(ReceiptReturnDetail d) = date(zReport(receipt(d)));

date 'Дата' = ABSTRACT DATE (ReceiptDetail) PERSISTENT INDEXED;
date(ReceiptReturnDetail detail) += date(detail);
date(ReceiptSaleDetail detail) += date(detail);

dateZReport 'Дата Z-отчета' (ReceiptDetail d) = date(zReport(receipt(d)));

dateTime 'Дата/время' = ABSTRACT DATETIME (ReceiptDetail) PERSISTENT INDEXED;
dateTime(ReceiptReturnDetail detail) += dateTime(detail);
dateTime(ReceiptSaleDetail detail) += dateTime(detail);

time 'Время' (ReceiptDetail d) = TIME(dateTime(d));

// ------------ Проведен --------------- // 

isPosted 'Проведен' (receiptDetail) = ABSTRACT BOOLEAN (ReceiptDetail) PERSISTENT;

@defineDocumentDetailPosted(receipt, ReceiptSaleDetail);
isPosted(ReceiptSaleDetail d) += isPosted(d);

@defineDocumentDetailPosted(receipt, ReceiptReturnDetail);
isPosted(ReceiptReturnDetail d) += isPosted(d); 

// ------------ Закрыт --------------- // 
isClosed 'Закрыт' (receiptDetail) = ABSTRACT BOOLEAN (ReceiptDetail) PERSISTENT;

@defineDocumentDetailClosed(receipt, ReceiptSaleDetail);
isClosed(ReceiptSaleDetail d) += isClosed(d);
 
@defineDocumentDetailClosed(receipt, ReceiptReturnDetail);
isClosed(ReceiptReturnDetail d) += isClosed(d);

// --------------- Магазин --------------- //
departmentStore (receiptDetail) = ABSTRACT DepartmentStore (ReceiptDetail) PERSISTENT;
nameDepartmentStore 'Склад' (ReceiptDetail d) = name(departmentStore(d));
store (ReceiptDetail receiptDetail) = store(departmentStore(receiptDetail));

INDEX departmentStore(ReceiptDetail d), date(d);

@defineDocumentDetailDepartmentStoreCustom(receipt, receiptSaleDetail);
departmentStore (ReceiptSaleDetail d) += departmentStore(d);
 
@defineDocumentDetailDepartmentStoreCustom(receipt, receiptReturnDetail);
departmentStore (ReceiptReturnDetail d) += departmentStore(d); 

// Валюта
@defineDocumentDetailCurrency(receipt, receiptDetail);

@defineDocumentDetailSku(receiptSale, sku);
@defineDocumentDetailSku(receiptReturn, sku);
sku (ReceiptDetail receiptDetail) = MULTI sku[ReceiptReturnDetail](receiptDetail), sku[ReceiptSaleDetail](receiptDetail) PERSISTENT;

INDEX receipt(ReceiptDetail d), sku(d);

idSku 'Код' (ReceiptDetail receiptDetail) = id(sku(receiptDetail));
idSkuGroup 'Код' (ReceiptDetail receiptDetail) = id(skuGroup(sku(receiptDetail)));
nameSkuGroup1Sku 'Классификация' (ReceiptDetail receiptDetail) = nameSkuGroup1(sku(receiptDetail));
nameSkuGroup2Sku 'Категория' (ReceiptDetail receiptDetail) = nameSkuGroup2(sku(receiptDetail));
nameSkuGroup3Sku 'Направление' (ReceiptDetail receiptDetail) = nameSkuGroup3(sku(receiptDetail));
nameSkuGroup4Sku 'Группа' (ReceiptDetail receiptDetail) = nameSkuGroup4(sku(receiptDetail));
nameSkuGroup5Sku 'Подгруппа' (ReceiptDetail receiptDetail) = nameSkuGroup5(sku(receiptDetail));
nameSkuGroup6Sku 'Субгруппа' (ReceiptDetail receiptDetail) = nameSkuGroup6(sku(receiptDetail));
shortNameUOMSku 'Ед. изм.' (ReceiptDetail receiptDetail) = shortNameUOM(sku(receiptDetail));


skip 'Не проводить по регистру' (ReceiptSaleDetail receiptDetail) = skip(receipt(receiptDetail)) OR skuType(sku(receiptDetail)) == SkuType.skuTypeCharge; 
skip 'Не проводить по регистру' (ReceiptReturnDetail receiptDetail) = skip(receipt(receiptDetail)) OR skuType(sku(receiptDetail)) == SkuType.skuTypeCharge; 

active(ReceiptSaleDetail d) = isPosted(d) AND NOT skip(d); 
active(ReceiptReturnDetail d) = isPosted(d) AND NOT skip(d); 

setAttributes = ACTION ABSTRACT (ReceiptDetail);

changeDialogSku(ReceiptDetail detail)  = ACTION {
    setAttributes(detail); 
    REQUEST OBJECT s
        IF sku(detail) THEN {
            FORM skus OBJECTS s = sku(detail) MODAL;
        } ELSE {
            FORM skus MODAL;
        }
                                              
    IF formResult() == FormResult.ok THEN {
        sku(detail) <- requestedObject();
    }
} TOOLBAR;

//партии
@defineDocumentAbstractDetailBatchCustom(receiptDetail, batch);
@defineDocumentDetailBatchCustom(receiptSaleDetail, batch);
@defineDocumentDetailBatchCustom(receiptReturnDetail, batch);

batch(ReceiptSaleDetail detail) += batch(detail);
batch(ReceiptReturnDetail detail) += batch(detail);

replace(Sku s, Batch b) += ACTION { sku(ReceiptSaleDetail detail) <- s WHERE batch(detail) == b;}
replace(Sku s, Batch b) += ACTION { sku(ReceiptReturnDetail detail) <- s WHERE batch(detail) == b;}

changeBatch(ReceiptDetail detail) = ACTION {
    FORM dialogBatchStockOut OBJECTS st = departmentStore(detail),
                             t = dateTime(detail),
                             sk = sku(detail) DIALOG SHOWDROP;

    IF formResult() == FormResult.ok THEN {
        batch(detail) <- chosenObject('bt');
    } ELSE IF formResult() == FormResult.drop THEN {
        batch(detail) <- NULL;
    }
}

nameSku 'Товар' (ReceiptDetail d) = IF batch(d) THEN documentNameSku(batch(d)) ELSE name(sku(d)) IN recognize;

boardNameSku 'Товар' = ABSTRACT VARISTRING[255] (ReceiptDetail);

explicitBatchLedger(Receipt receipt) = explicitBatchLedger(departmentStore(zReport(receipt)));
notExplicitBatchLedger(Receipt receipt) = departmentStore(zReport(receipt)) AND NOT explicitBatchLedger(receipt);

number 'Номер чека' (receipt) = DATA INTEGER (Receipt) IN documentHeader;
numberReceipt 'Номер чека' (ReceiptDetail receiptDetail) = number(receipt(receiptDetail));

nameEmployee 'Кассир' = nameEmployee(receipt(ReceiptDetail detail));

maxNumberReceipt 'Максимальный номер чека' (zReport) = GROUP MAX number(Receipt receipt) BY zReport(receipt) PERSISTENT;

GROUP receiptDiscount 'Дисконтная карта' : public;

idBarcode 'Штрихкод' (receiptDetail) = DATA VARSTRING[15] (ReceiptDetail) FIXEDCHARWIDTH 14 INDEXED;

// Возвраты

saleReceipt = DATA Receipt (ReceiptReturnDetail);
receiptDetail(sku, receipt) = GROUP MAX ReceiptDetail receiptDetail BY sku(receiptDetail), receipt(receiptDetail);
saleReceiptDetail(ReceiptReturnDetail returnReceiptDetail) = receiptDetail(sku[ReceiptDetail](returnReceiptDetail), saleReceipt(returnReceiptDetail));                                                                                                                                                             
receiptSaleDetail = DATA ReceiptSaleDetail (ReceiptReturnDetail);
overReceiptSaleDetail(ReceiptReturnDetail detail) = OVERRIDE receiptSaleDetail(detail), saleReceiptDetail(detail);
receiptSale (ReceiptReturnDetail returnDetail) = receipt[ReceiptSaleDetail](overReceiptSaleDetail(returnDetail));

descriptionSale 'Чек продажи' (ReceiptReturnDetail returnDetail) = CONCAT ' ',
    'Чек № ' + number(receiptSale(returnDetail)),
    'от ' + dateTime(receiptSale(returnDetail)),
    'позиция ' + index(overReceiptSaleDetail(returnDetail)) MINCHARWIDTH 15 PREFCHARWIDTH 20;

changeDescriptionSale = ACTION ABSTRACT LIST (ReceiptReturnDetail);

// Количества и суммы

quantity 'Количество' (receiptDetail) = DATA NUMERIC[14,3] (ReceiptSaleDetail);
price 'Цена' (receiptDetail) = DATA NUMERIC[16,4] (ReceiptSaleDetail) @@denomination;
sum 'Сумма' (receiptDetail) = DATA NUMERIC[18,4] (ReceiptSaleDetail) @@denomination;
discountPercent 'Процент скидки' (receiptDetail) = DATA NUMERIC[6,2] (ReceiptSaleDetail);
discountPercent (receipt)= GROUP SUM 1 IF discountPercent(ReceiptSaleDetail detail) BY receipt[ReceiptDetail](detail);
discountSum 'Сумма скидки' (receiptDetail) = DATA NUMERIC[18,4] (ReceiptSaleDetail) @@denomination;

priceSum 'Сумма без скидки' = round(quantity(ReceiptSaleDetail detail) * price(detail), roundCondition(departmentStore(detail)));

//discountSumReceiptSaleDetail (detail) <- round(priceSumReceiptSaleDetail(detail) * discountPercentReceiptSaleDetail (detail) / 100,
//                                               priceRoundCurrency(currencyReceiptSaleDetail (detail)))
//    WHEN CHANGED (quantityReceiptSaleDetail(detail)) OR
//         CHANGED (priceReceiptSaleDetail(detail)) OR
//         CHANGED (discountPercentReceiptSaleDetail(detail)) OR
//         CHANGED (currencyReceiptSaleDetail (detail));
calcDiscountSum (ReceiptSaleDetail detail) = round(priceSum(detail) * discountPercent (detail) / 100,
                                               roundDiscountCondition(departmentStore(detail)));

extraDiscountSum = ABSTRACT NUMERIC[18,4] (ReceiptSaleDetail);
calcSum (ReceiptSaleDetail detail) = priceSum(detail) (-) discountSum(detail) (-) extraDiscountSum(detail);
sum (ReceiptSaleDetail detail) <- calcSum(detail)
    WHEN CHANGED (quantity(detail)) OR
         CHANGED (price(detail)) OR
         CHANGED (discountPercent(detail)) OR
         CHANGED (discountSum(detail)) OR
         CHANGED (extraDiscountSum(detail)) OR
         CHANGED (departmentStore(detail));

quantity 'Количество' (receiptDetail) = DATA NUMERIC[14,3] (ReceiptReturnDetail);
price 'Цена' (receiptDetail) = DATA NUMERIC[16,4] (ReceiptReturnDetail) @@denomination;
sum 'Сумма' (receiptDetail) = DATA NUMERIC[18,4] (ReceiptReturnDetail) @@denomination;
discountSum 'Сумма скидки' (receiptDetail) = DATA NUMERIC[18,4] (ReceiptReturnDetail) @@denomination;

quantityReturned 'Возвращено' (saleDetail) = GROUP SUM quantity(ReceiptReturnDetail returnDetail) BY receiptSaleDetail(returnDetail) PERSISTENT;
CONSTRAINT quantityReturned(ReceiptSaleDetail detail) > quantity (detail) MESSAGE 'Количество возвратов по строке чека превышает проданное количество';

overSum (ReceiptReturnDetail d) = round(
        (quantity(d) * sum(receiptSaleDetail(d)) / 
        (quantity(receiptSaleDetail(d)) IF quantity(receiptSaleDetail(d))!=0)), 
    roundCondition(departmentStore (d)));

priceSum 'Сумма без скидки' = round(
        quantity(ReceiptReturnDetail d) * price(d),
    roundCondition(departmentStore(d)));

sum (ReceiptReturnDetail detail) <- IF receiptSaleDetail(detail) 
                                        THEN overSum(detail)
                                        ELSE priceSum(detail)
                                            
                                   WHEN CHANGED(quantity(detail)) OR
                                        CHANGED(receiptSaleDetail(detail)) OR
                                        CHANGED(departmentStore(detail));

discountSum (ReceiptReturnDetail detail) <- IF receiptSaleDetail(detail) THEN
                                                round(quantity(detail) * discountSum(receiptSaleDetail(detail)) / quantity(receiptSaleDetail(detail)),
                                                    roundDiscountCondition(departmentStore(receiptSaleDetail(detail))))
                                           ELSE
                                                quantity(detail) * price(detail) - sum(detail)
                                           WHEN CHANGED(quantity(detail)) OR
                                                CHANGED(sum(detail)) OR
                                                CHANGED(receiptSaleDetail(detail)) OR
                                                CHANGED(departmentStore(detail));

quantity 'Количество' = ABSTRACT NUMERIC[14,3] (ReceiptDetail) PERSISTENT;
quantity(ReceiptReturnDetail detail) += quantity(detail);
quantity(ReceiptSaleDetail detail) += quantity(detail);

price 'Цена' = ABSTRACT NUMERIC[16,4] (ReceiptDetail) PERSISTENT @@denomination;
price(ReceiptReturnDetail detail) += price(detail);
price(ReceiptSaleDetail detail) += price(detail);

INDEX sku(ReceiptDetail d), price(d);

sum 'Сумма' = ABSTRACT NUMERIC[18,4] (ReceiptDetail) PERSISTENT @@denomination;
sum(ReceiptReturnDetail detail) += sum(detail);
sum(ReceiptSaleDetail detail) += sum(detail);

discountSum 'Сумма скидки' = ABSTRACT NUMERIC[18,4] (ReceiptDetail) PERSISTENT @@denomination;
discountSum(ReceiptSaleDetail d) += discountSum(d);
discountSum(ReceiptReturnDetail d) += discountSum(d);

fullSum 'Сумма без скидки' (ReceiptSaleDetail d) = sum(d) (+) discountSum(d);
fullSum 'Сумма без скидки' (ReceiptReturnDetail d) = sum(d) (+) discountSum(d);
fullSum 'Сумма без скидки' (ReceiptDetail d) = sum(d) (+) discountSum(d);

sumReceiptSaleDetail 'Сумма продажи' (receipt) = GROUP SUM sum(ReceiptSaleDetail receiptDetail)
    BY receipt (receiptDetail) IN documentSum PERSISTENT @@denomination;

sumReceiptReturnDetail 'Сумма возврата' (receipt) = GROUP SUM sum(ReceiptReturnDetail receiptDetail)
    BY receipt (receiptDetail) IN documentSum PERSISTENT @@denomination;

signedSum 'Сумма' = ABSTRACT NUMERIC[18,4] (ReceiptDetail) PERSISTENT @@denomination;
signedSum(ReceiptReturnDetail detail) += -sum(detail);
signedSum(ReceiptSaleDetail detail) += sum(detail);

signedQuantity 'Количество' = ABSTRACT NUMERIC[14,3] (ReceiptDetail) PERSISTENT;
signedQuantity(ReceiptReturnDetail detail) += -quantity(detail);
signedQuantity(ReceiptSaleDetail detail) += quantity(detail);

signedDiscountSum = ABSTRACT NUMERIC[18,4] (ReceiptDetail);
signedDiscountSum(ReceiptReturnDetail detail) += -discountSum(detail);
signedDiscountSum(ReceiptSaleDetail detail) += discountSum(detail);

sumReceiptDetail 'Сумма чека' (receipt) = GROUP SUM signedSum(ReceiptDetail detail)
    BY receipt(detail) PERSISTENT @@denomination;

sumSkuReceiptDetail 'Сумма чека по товарам' (receipt) = 
    GROUP SUM signedSum(ReceiptDetail detail) IF sku(detail) BY receipt(detail) PERSISTENT  @@denomination;
//sumReceiptDetailReceipt 'Сумма чека' (receipt) = sumReceiptSaleDetailReceipt(receipt) (-) sumReceiptReturnDetailReceipt(receipt) PERSISTENT;
sumReceiptDetail 'Сумма чека' (ReceiptDetail receiptDetail) = sumReceiptDetail(receipt(receiptDetail));

discountSumSaleReceiptDetailSale 'Сумма скидки (продажи)' (receipt) = GROUP SUM discountSum(ReceiptSaleDetail receiptDetail)
    BY receipt (receiptDetail) IN documentSum;
discountSumSale 'Сумма скидки (продажи) по чеку' (receipt) = DATA NUMERIC[18,4] (Receipt) @@denomination;

discountSumReturnReceiptDetailReturn 'Сумма скидки (возврат)' (receipt) = GROUP SUM discountSum(ReceiptReturnDetail receiptDetail)
    BY receipt (receiptDetail) IN documentSum;
discountSumReturn 'Сумма скидки (возврат) по чеку' (receipt) = DATA NUMERIC[18,4] (Receipt) @@denomination;

discountSumReceiptDetail 'Сумма скидки' (Receipt receipt) = discountSumSaleReceiptDetailSale(receipt) (-) discountSumReturnReceiptDetailReturn(receipt) PERSISTENT @@denomination;
discountSum 'Сумма скидки по чеку' (Receipt receipt) = discountSumSale(receipt) (-) discountSumReturn(receipt);

@defineDocumentHeaderCount(receipt);

@defineDocumentHeaderQuantity(receipt);
@defineDocumentHeaderSkuQuantity(receipt, sku);
@defineDocumentHeaderSkuQuantity(receipt, receiptSaleDetail, sku);

// -------------------------------------------------- НДС ------------------------------------------------ //

VAT = DATA Range (ReceiptSaleDetail);
CONSTRAINT tax(VAT(ReceiptSaleDetail detail)) != Tax.taxVAT OR
           country(VAT(detail)) != country(departmentStore(detail))
           CHECKED BY VAT[ReceiptSaleDetail]
           MESSAGE 'ошибка: Шкала должна соответствовать шкале НДС и стране магазина: продажа';

VAT(ReceiptSaleDetail d) <- VAT(sku(d), departmentStore(d))
    WHEN CHANGED(sku(d)) OR CHANGED(departmentStore(d));

VAT = DATA Range (ReceiptReturnDetail);
CONSTRAINT tax(VAT(ReceiptReturnDetail detail)) != Tax.taxVAT OR
           country(VAT(detail)) != country(departmentStore(detail))
           CHECKED BY VAT[ReceiptReturnDetail]
           MESSAGE 'ошибка: Шкала должна соответствовать шкале НДС и стране магазина: возврат';

VAT(ReceiptReturnDetail d) <- VAT(sku(d), departmentStore(d))
    WHEN CHANGED(sku(d)) OR CHANGED(departmentStore(d));

VAT 'НДС' = ABSTRACT Range(ReceiptDetail) PERSISTENT;
VAT(ReceiptSaleDetail d) += VAT(d);
VAT(ReceiptReturnDetail d) += VAT(d);

numberVAT 'НДС, номер' (ReceiptDetail receiptDetail) = number(VAT(receiptDetail));

valueVAT 'НДС, %' (receiptDetail) = DATA NUMERIC[10,5] (ReceiptDetail) PERSISTENT;
overValueVAT(d) = ABSTRACT VALUE OVERRIDE FIRST NUMERIC[10,5] (ReceiptDetail);
overValueVAT(ReceiptDetail d) += valueRate(VAT(d), date(d));
WHEN CHANGED(VAT(ReceiptDetail d)) OR CHANGED(date(d)) OR CHANGED (batch(d)) DO {
    valueVAT(d) <- overValueVAT(d);
}

sumVAT 'Сумма НДС' (d) = DATA NUMERIC[18,4] (ReceiptDetail) @@denomination;
calcSumVAT 'Сумма НДС' (ReceiptDetail d) = round(sum(d) * valueVAT(d) / (100 + valueVAT(d)), currency(d));
// пока делаем не сессионным событием, чтобы быстрее принималось
WHEN CHANGED(valueVAT(ReceiptDetail d)) OR CHANGED(sum(d)) OR CHANGED(currency(d)) DO {
    sumVAT(d) <- calcSumVAT(d);
}

signedSumVAT 'Сумма НДС' (ReceiptDetail d) = IF d IS ReceiptReturnDetail THEN -sumVAT(d) ELSE sumVAT(d);

// используется только для приема реализации из внешних касс
description 'Название документа' (Receipt receipt) = 'Чек № ' + number(receipt) + ' от ' + dateTime(receipt);

description (ReceiptSaleDetail receiptDetail) = 'Продажа № ' + number(receipt(receiptDetail)) + ' от ' + dateTime(receipt(receiptDetail));

description (ReceiptReturnDetail receiptDetail) = 'Возврат № ' + number(receipt(receiptDetail)) + ' от ' + dateTime(receipt(receiptDetail));

description 'Название документа' (ReceiptDetail receiptDetail) = MULTI description[ReceiptReturnDetail](receiptDetail), description[ReceiptSaleDetail](receiptDetail);

@defineAddDetailDialogSkuStockCustom(receipt, receiptSaleDetail, ' (продажа)', sku, departmentStore, dialogSku);
@defineAddDetailDialogSkuStockCustom(receipt, receiptReturnDetail, ' (возврат)', sku, departmentStore, dialogSku);

// ----------------- Оплаты по чеку ------------------------------

CLASS Payment 'Оплата по чеку';
TABLE payment (Payment);

@defineExternalizable(payment, VARSTRING[100]);

CLASS PaymentMeans 'Форма оплаты'{
    paymentMeansCash 'Наличные',
    paymentMeansCard 'Карточка'
}
FORM paymentMeans
    OBJECTS m = PaymentMeans
    PROPERTIES(m) staticCaption
    DIALOG PaymentMeans OBJECT m
;

CLASS PaymentType 'Тип платежа';
TABLE paymentType (PaymentType);

name 'Наименование' = DATA VARISTRING[110](PaymentType) IN recognize;

paymentMeans (paymentType) = DATA PaymentMeans (PaymentType);
namePaymentMeans 'Форма оплаты' (PaymentType paymentType) = staticCaption(paymentMeans(paymentType)) IN recognize;

sid 'Идентификатор' = DATA STRING[10] (PaymentType) IN base;
typePaymentSID (tp) = GROUP AGGR PaymentType paymentType BY sid(paymentType) WHERE paymentType IS PaymentType;

FORM paymentType 'Тип платежа'
    OBJECTS pt = PaymentType FIXED PANEL
    PROPERTIES(pt) name, namePaymentMeans, sid

    EDIT PaymentType OBJECT pt
;

FORM paymentTypes 'Тип платежа'
    OBJECTS pt = PaymentType
    PROPERTIES(pt) READONLY name, namePaymentMeans, sid
    PROPERTIES(pt) ADDFORM, EDITFORM, DELETE FORCE PANEL TOOLBAR

    DIALOG PaymentType OBJECT pt
;

receipt (payment) = DATA Receipt (Payment) NOT NULL DELETE INDEXED;

countPayment 'Кол-во типов платежей' (receipt) = GROUP SUM 1 BY receipt(Payment payment);

paymentType (payment) = DATA PaymentType(Payment);
namePaymentType 'Тип платежа' (Payment payment) = name(paymentType(payment));
sidPaymentType 'ID Типа платежа' (Payment payment) = sid(paymentType(payment));

minCashPaymentType () = GROUP MIN PaymentType paymentType IF paymentMeans(paymentType) == PaymentMeans.paymentMeansCash;
minCardPaymentType () = GROUP MIN PaymentType paymentType IF paymentMeans(paymentType) == PaymentMeans.paymentMeansCard;

paymentMeans (Payment payment) = paymentMeans(paymentType(payment)) PERSISTENT;
namePaymentMeans 'Форма оплаты' (Payment payment) = staticCaption(paymentMeans(payment));

number 'Номер платежа' (payment) = DATA INTEGER (Payment);

sum 'Сумма платежа' (payment) = DATA NUMERIC[18,4] (Payment) @@denomination;

sumPayment 'Сумма платежа' (receipt) = GROUP SUM sum(Payment payment) BY receipt(payment);

sumInCashPayment (receipt) = GROUP SUM sum(Payment payment) IF paymentMeans(payment) == PaymentMeans.paymentMeansCash  BY receipt(payment);

changePayment 'Сдача' (Receipt receipt) = sumPayment(receipt) - sumReceiptDetail(receipt);

sumCashPayment 'Сумма продажа (наличные)' (Receipt receipt) = sumInCashPayment(receipt) - changePayment(receipt) PERSISTENT  @@denomination;
sumCardPayment 'Сумма продажа (карточка)' (receipt) = GROUP SUM sum(Payment payment) IF paymentMeans(payment) == PaymentMeans.paymentMeansCard BY receipt(payment);

sumPositiveCashPayment 'Сумма продажа (наличные)' (Receipt receipt) =  sumCashPayment (receipt) IF sumCashPayment (receipt) >= 0.0 IN documentSum;
sumNegativeCashPayment 'Сумма возврата (наличные)' (Receipt receipt) =  sumCashPayment (receipt) IF sumCashPayment (receipt) < 0.0 IN documentSum;

sumPositiveCardPayment 'Сумма продажа (карточка)' (Receipt receipt) =  sumCardPayment (receipt) IF sumCardPayment (receipt) >= 0.0 IN documentSum;
sumNegativeCardPayment 'Сумма возврата (карточка)' (Receipt receipt) =  sumCardPayment (receipt) IF sumCardPayment (receipt) < 0.0 IN documentSum;

sumCashPayment 'Сумма (наличные)' (zReport) = GROUP SUM sumCashPayment(Receipt r) BY zReport(r) IN documentSum PERSISTENT  @@denomination;

sumPositiveCashPayment 'Сумма продажа (наличные)' (zReport) = GROUP SUM sumPositiveCashPayment(Receipt r) BY zReport(r) IN documentSum;
sumNegativeCashPayment 'Сумма возврата (наличные)' (zReport) = GROUP SUM sumNegativeCashPayment(Receipt r) BY zReport(r) PERSISTENT IN documentSum  @@denomination;

sumPositiveCardPayment 'Сумма продажа (карточка)' (zReport) = GROUP SUM sumPositiveCardPayment(Receipt r) BY zReport(r) IN documentSum;
sumNegativeCardPayment 'Сумма возврата (карточка)' (zReport) = GROUP SUM sumNegativeCardPayment(Receipt r) BY zReport(r) PERSISTENT IN documentSum @@denomination;

isSumPaymentReceipt 'Выключать ограничения по суммам платежей в чеке' = DATA BOOLEAN ();

EXTEND FORM options
    PROPERTIES() isSumPaymentReceipt
;

DESIGN options {
    commons {
        MOVE PROPERTY(isSumPaymentReceipt());
    }
}

CONSTRAINT Receipt receipt IS Receipt AND NOT isSumPaymentReceipt() AND NOT sumPayment(receipt) MESSAGE 'По чеку не указаны платежи';

CONSTRAINT ((sumReceiptDetail(Receipt receipt) > 0 AND sumReceiptDetail(receipt) > sumPayment(receipt)) OR
           (sumReceiptDetail(receipt) < 0 AND sumReceiptDetail(receipt) != sumPayment(receipt))) AND NOT isSumPaymentReceipt()
    MESSAGE 'Сумма платежей по чеку меньше суммы чека';
    
CONSTRAINT ((sumReceiptDetail(Receipt receipt) > 0 AND sumReceiptDetail(receipt) < sumCardPayment(receipt)) 
           OR (sumReceiptDetail(receipt) <0 AND sumReceiptDetail(receipt) > sumCardPayment(receipt))) AND NOT isSumPaymentReceipt()
    MESSAGE 'Сумма платежей по безналичному расчету больше суммы чека';

// Итоги по Z-отчету

quantityReceiptDetail 'Кол-во (всего)' (zReport) = GROUP SUM signedQuantity(ReceiptDetail detail) BY zReport(detail) IN documentSum PERSISTENT;

sumReceiptDetail 'Сумма Z-отчета' (zReport) = GROUP SUM sumReceiptDetail(Receipt receipt) BY zReport(receipt) PERSISTENT IN documentSum @@denomination;

sumCash 'Сумма наличных Z-отчета' (zReport) = GROUP SUM sumCashPayment(Receipt receipt) BY zReport(receipt) PERSISTENT IN documentSum @@denomination;
sumCard 'Сумма по карточкам Z-отчета' (zReport) = GROUP SUM sumCardPayment(Receipt receipt) BY zReport(receipt) PERSISTENT IN documentSum @@denomination;

sumSkuReceiptDetail 'Сумма Z-отчета по sku' (zReport) = GROUP SUM sumSkuReceiptDetail(Receipt receipt) BY zReport(receipt);

discountSumReceiptDetail 'Сумма скидок Z-отчета' (zReport) = GROUP SUM discountSumReceiptDetail(Receipt receipt) BY zReport(receipt) PERSISTENT IN documentSum @@denomination;
discountSumReceipt 'Сумма скидок по чекам Z-отчета' (zReport) = GROUP SUM discountSum(Receipt receipt) BY zReport(receipt) PERSISTENT IN documentSum @@denomination;
discountSum 'Сумма скидок Z-отчета' (ZReport zReport) = discountSumReceiptDetail(zReport) (+) discountSumReceipt(zReport) IN documentSum;

sumCashZReport 'Сумма наличных по кассе' = GROUP SUM sumCash(ZReport z) BY cashRegister(z); 
sumCardZReport 'Сумма безнал. по кассе' = GROUP SUM sumCard(ZReport z) BY cashRegister(z); 
// НДС

sumVATSkuReceiptDetail 'Сумма НДС по sku' (zReport) = GROUP SUM signedSumVAT(ReceiptDetail detail)
    IF sku(detail) BY zReport(detail);
sumVATReceiptDetail'Сумма НДС' (receipt) = GROUP SUM signedSumVAT(ReceiptDetail detail)
    BY receipt(detail) PERSISTENT @@denomination; 
sumVATReceiptDetail 'Сумма НДС' (zReport) = GROUP SUM sumVATReceiptDetail(Receipt receipt)
    BY zReport(receipt) IN documentSum;            

discountSumVAT 'Сумма НДС в скидке' (ReceiptDetail d) = round(discountSum(d) * valueVAT(d) / (100 + valueVAT(d)), currency(d));
 
discountSumVATSale 'Сумма НДС в скидке (продажа)' (zReport)= GROUP SUM discountSumVAT(ReceiptSaleDetail d) IF d IS ReceiptSaleDetail BY zReport[ReceiptDetail](d);
discountSumVATReturn 'Сумма НДС в скидке (возврат)' (zReport)= GROUP SUM discountSumVAT(ReceiptReturnDetail d) IF d IS ReceiptReturnDetail BY zReport[ReceiptDetail](d);

discountSumVAT 'Сумма НДС в скидке' (ZReport zReport)= discountSumVATSale(zReport) (-) discountSumVATReturn(zReport);

discountSumMarkup 'Сумма набавки в скидке' (ZReport z) = discountSum(z) (-) discountSumVAT(z);

// Суммы за дату
sumCard 'Продано с использованием банк. карточек' (departmentStore, dateFrom, dateTo) = GROUP SUM sum(Payment payment) IF paymentMeans(payment)==PaymentMeans.paymentMeansCard
    AND date(receipt(payment)) >= DATE dateFrom AND date(receipt(payment)) <= DATE dateTo AND isPosted(receipt(payment))
        BY departmentStore(receipt(payment)), dateFrom, dateTo;
sumCash 'Продано с использованием наличных' (departmentStore, dateFrom, dateTo) = GROUP SUM sum(Payment payment) IF paymentMeans(payment)==PaymentMeans.paymentMeansCash
    AND date(receipt(payment)) >= DATE dateFrom AND date(receipt(payment)) <= DATE dateTo AND isPosted(receipt(payment))
        BY departmentStore(receipt(payment)), dateFrom, dateTo;
        
sumSale 'Продано по кассе' (departmentStore, dateFrom, dateTo) = GROUP SUM sumReceiptDetail(Receipt receipt)
    IF date(receipt) >= DATE dateFrom AND date(receipt) <= DATE dateTo AND isPosted(receipt)
        BY departmentStore(receipt), dateFrom, dateTo;

//----------------------------------- Формы -------------------------------------------------//

FORM zReport 'Z-отчет'
    OBJECTS z=ZReport FIXED PANEL
    PROPERTIES (z) overNumberCashRegister, nameDepartmentStore, date, time, number, //sumCashZReport
                   basis, countReceipt, quantityReceiptDetail, 
                   sumPositiveCashPayment, sumPositiveCardPayment, discountSum,
                   sumNegativeCashPayment, sumNegativeCardPayment, sumReceiptDetail,
                   sumVATReceiptDetail

    OBJECTS b=Receipt, d=ReceiptDetail
    PROPERTIES(b) number, date, time, nameEmployee,
                  sumReceiptDetail, discountSumReceiptDetail,
                  discountSum, sumVATReceiptDetail, countReceiptDetail, quantityReceiptDetail,
                  sumCashPayment, sumCardPayment, ADDOBJ, DELETESESSION
    FILTERS zReport(b)==z

    PROPERTIES(b) TODRAW d addDetailDialogSkuStockReceiptSaleDetail, addDetailDialogSkuStockReceiptReturnDetail
                           // todo : добавить операции возврата по штрихкоду

    PROPERTIES(d) type READONLY, idBarcode, 
                  nameSku ON CHANGE changeDialogSku(d) FORCE GRID, 
                  nameBatch ON CHANGE changeBatch(d) SHOWIF explicitBatchLedger(b),
                  descriptionSale FORCE GRID ON CHANGE changeDescriptionSale(d),
                  quantity, quantityReturned FORCE GRID, price,
                  sum, discountPercent FORCE GRID, discountSum FORCE GRID,
                  numberVAT FORCE GRID, valueVAT FORCE GRID, ADDOBJ, DELETESESSION

    FILTERS receipt(d)==b

    OBJECTS p=Payment
    PROPERTIES(p) namePaymentType, namePaymentMeans, sum, ADDOBJ, DELETESESSION

    FILTERS receipt(p)==b

    EDIT ZReport OBJECT z
;

DESIGN zReport {

    NEW pane {
        type = CONTAINERH;      
           
        NEW first {
            fill = 1;
            type = CONTAINERV;
            MOVE z.documentHeader {
                type = CONTAINERH;
                MOVE PROPERTY (nameDepartmentStore(z));
                MOVE PROPERTY (number(z));
                MOVE PROPERTY (date(z));
                MOVE PROPERTY (time(z));
            }
            MOVE z.documentPrm;
        }
        MOVE z.documentSum { columns = 2;}    

    }    
    MOVE b.box;
    NEW secondCase{
        fill = 1;
        type = SPLITH;

        MOVE d.box {
            fill = 3;
            caption = 'Строка чека';
        }
        MOVE p.box;
    }           

    MOVE functions.box;
}



overCopy = ACTION ABSTRACT LIST (ReceiptDetail, ReceiptDetail);
overCopy = ACTION ABSTRACT LIST (ReceiptDetail, Receipt);    

edit 'Редактировать' = ACTION EDITFORM ZReport;

copy 'Копировать'(Receipt receipt) = ACTION {
    FOR ADDOBJ r = Receipt DO {
        zReport(r) <- zReport(receipt);
        skip(r) <- skip(receipt);
        currency(r) <- currency(receipt);
        discountSumSale(r) <- discountSumSale(receipt);
        discountSumReturn(r) <- discountSumReturn(receipt);        
        note(r) <- note(receipt);
        date(r) <- date(receipt);
        time(r) <- time(receipt);
        
        FOR receipt(ReceiptDetail detail) == receipt ORDER detail DO {
            IF detail IS ReceiptSaleDetail THEN {
                FOR ADDOBJ d=ReceiptSaleDetail DO {                    
                    receipt(d) <- r;
                    sku(d) <- sku[ReceiptSaleDetail](detail);
                    batch(d) <- batch[ReceiptSaleDetail](detail);
                    idBarcode(d) <- idBarcode(detail);
                    quantity(d) <- quantity[ReceiptSaleDetail](detail);
                    price(d) <- price[ReceiptSaleDetail](detail);
                    discountPercent(d) <- discountPercent(detail);
                    discountSum(d) <- discountSum[ReceiptSaleDetail](detail);
                    VAT(d) <- VAT[ReceiptSaleDetail](detail);
                    sum(d) <- sum(detail);
                    
                    overCopy(d, detail);
                }            
            } 
            IF detail IS ReceiptReturnDetail THEN {
                FOR ADDOBJ d=ReceiptReturnDetail DO {
                    receipt(d) <- r;
                    sku(d) <- sku[ReceiptReturnDetail](detail);
                    idBarcode(d) <- idBarcode(detail);
                    quantity(d) <- quantity[ReceiptReturnDetail](detail);
                    price(d) <- price[ReceiptReturnDetail](detail);
                    discountSum(d) <- discountSum[ReceiptReturnDetail](detail);
                    VAT(d) <- VAT[ReceiptReturnDetail](detail);                    
                    sum(d) <- sum[ReceiptReturnDetail](detail);

                    overCopy(d, detail);
                }            
            }           
            overCopy(detail,r);

        }
        FOR receipt(Payment payment) == receipt DO {
            FOR ADDOBJ p=Payment DO {
                receipt(p) <- r;
                paymentType(p) <- paymentType(payment);
                number(p) <- number(payment);
                sum(p) <- sum(payment);
                
            }
        }
        SEEK zReport.b = r;
    }
} TOOLBAR;

EXTEND FORM zReport 
    PROPERTIES (b) copy
;

overPrice 'Цена' (Sku sku, Receipt receipt, DATETIME dateTime) =
        priceA(priceListType(groupCashRegister(receipt)), sku, departmentStore(receipt), dateTime);
overPrice 'Цена' (Batch batch, Receipt receipt, DATETIME dateTime) =
    IF priceA(priceListType(groupCashRegister(receipt)), batch, departmentStore(receipt), dateTime) THEN
        priceA(priceListType(groupCashRegister(receipt)), batch, departmentStore(receipt), dateTime)
    ELSE
        overPrice(sku(batch), receipt, dateTime); 
        
WHEN SESSION FORMS zReport (CHANGED (sku(ReceiptDetail d)) OR CHANGED (batch(d))) AND NOT (CHANGED (price(d))) DO {
    IF explicitBatchLedger(receipt(d)) THEN {
        price(d) <- overPrice(batch(d), receipt(d), dateTime(d));    
    } ELSE {
        price(d) <- overPrice(sku(d), receipt(d), dateTime(d));    
    }
}
WHEN SESSION FORMS zReport CHANGED (sku(ReceiptDetail d))  AND NOT (CHANGED (idBarcode(d))) DO {
    idBarcode(d) <- idBarcode(sku(d));
}
        
edit 'Редактировать' = ACTION ABSTRACT LIST  (ReceiptDetail) IMAGE 'edit.png' EDITKEY 'BACK_SPACE' HIDE TOOLBAR;

edit 'Редактировать' (ReceiptReturnDetail d) = ACTION NEWSESSION {
    FORM zReport OBJECTS z = zReport(d), b = receipt(d), d = d MANAGESESSION DOCKEDMODAL;
}
edit(ReceiptReturnDetail d) += ACTION edit(d);

edit 'Редактировать' (ReceiptSaleDetail d) = ACTION NEWSESSION {
    FORM zReport OBJECTS z = zReport(d), b = receipt(d), d = d MANAGESESSION DOCKEDMODAL;
}
edit(ReceiptSaleDetail d) += ACTION edit(d);

show 'Просмотреть' = ACTION ABSTRACT LIST  (ReceiptDetail)  TOOLBAR;

show 'Просмотреть' (ReceiptReturnDetail d) = ACTION NEWSESSION {
    FORM zReport OBJECTS z = zReport(d), b = receipt(d), d = d DOCKEDMODAL READONLY ;
}
show(ReceiptReturnDetail d) += ACTION show(d);

show 'Просмотреть' (ReceiptSaleDetail d) = ACTION NEWSESSION {
    FORM zReport OBJECTS z = zReport(d), b = receipt(d), d = d DOCKEDMODAL READONLY;
}
show(ReceiptSaleDetail d) += ACTION show(d);


isPostedOpened (ZReport z)= isPosted(z) AND isOpened(z);
isDraftOpened (ZReport z)= isDraft(z) AND isOpened(z);

filterZReportDateFrom 'Дата с' = DATA LOCAL DATE ();
filterDateFromZreport (ZReport z) = date(z) >= filterZReportDateFrom() OR (z IS ZReport AND NOT filterZReportDateFrom());      

filterZReportDateTo 'Дата по' = DATA LOCAL DATE ();
filterDateToZreport (ZReport z) = date(z) <= filterZReportDateTo() OR (z IS ZReport AND NOT filterZReportDateTo());

filterZReportDepartmentStore  = DATA LOCAL DepartmentStore ();
nameFilterZReportDepartmentStore 'Отдел магазина' = name(filterZReportDepartmentStore()) MINCHARWIDTH 15 PREFCHARWIDTH 20;          
filterDepartmentStore (ZReport z) = departmentStore(z) == filterZReportDepartmentStore() OR (z IS ZReport AND NOT filterZReportDepartmentStore());
 
filterZReportCashRegister 'Касса Z-отчета'   = DATA LOCAL VARSTRING[10] ();
filterCashRegister (ZReport z) = overNumberCashRegister(z) == filterZReportCashRegister() OR (z IS ZReport AND NOT filterZReportCashRegister()); 

lastDateTimeReceipt 'Время последнего чека'  = GROUP LAST dateTime(Receipt b)
        BY zReport(b)
        ORDER dateTime(b), b;    
firstDateTimeReceipt 'Время первого чека' = GROUP LAST dateTime(Receipt b)
        BY zReport(b)
        ORDER DESC dateTime(b), b;      
        
FORM zReports 'Z-отчеты'
    PROPERTIES ()  filterZReportDateFrom, filterZReportDateTo, nameFilterZReportDepartmentStore, filterZReportCashRegister

    OBJECTS z=ZReport LAST
    PROPERTIES (z) READONLY succeededExtraCheck, isClosed, isPosted, number, date, time, nameDepartmentStore, 
                            overNumberCashRegister, basis, countReceipt, quantityReceiptDetail, 
                            sumReceiptDetail, sumPositiveCashPayment, sumPositiveCardPayment,                             
                            sumNegativeCashPayment, sumNegativeCardPayment, sumVATReceiptDetail,
                            discountSum, firstDateTimeReceipt, lastDateTimeReceipt                                                                                 
                                                        
    PROPERTIES (z) ADDFORM, EDITFORM SHOWIF isOpened(z) 
    PROPERTIES (z) close SHOWIF isOpened(z), open SHOWIF isClosed(z)

    PROPERTIES (z) deletez=DELETE FORCE PANEL TOOLBAR SHOWIF isDraftOpened(z),
                            post SHOWIF isDraftOpened(z), unpost SHOWIF isPostedOpened(z)
    
    FILTERS filterDateFromZreport(z),
            filterDateToZreport(z),
            filterDepartmentStore(z),
            filterCashRegister(z)

    OBJECTS b=Receipt
    PROPERTIES(b) READONLY  number, date, time, nameEmployee,
                            sumReceiptDetail, discountSumReceiptDetail,
                            discountSum, sumVATReceiptDetail, countReceiptDetail, quantityReceiptDetail,
                            sumCashPayment, sumCardPayment

    FILTERS zReport(b)==z
    ORDER BY                number(b)

    OBJECTS d=ReceiptDetail
    PROPERTIES(d) READONLY  type, idBarcode, nameSku FORCE GRID, nameBatch SHOWIF explicitBatchLedger(b),
                            descriptionSale FORCE GRID,
                            quantity, quantityReturned FORCE GRID, price,
                            sum, discountPercent FORCE GRID,
                            discountSum FORCE GRID

    FILTERS receipt(d)==b

    OBJECTS p=Payment
    PROPERTIES(p) READONLY  namePaymentType, namePaymentMeans, sum

    FILTERS receipt(p)==b
;
@extendFormFilterAccessStock(ZReport, z, zReports, departmentStore, company);

DESIGN zReports {

    NEW topContainer{
        fill = 1;
        type = SPLITV;

        NEW firstCase {
            fill = 2;
            type = SPLITV;
             NEW ZFilters {
                fill = 1;
                NEW filters{
                    caption = 'Фильтры';
                    type = CONTAINERH;          
                    MOVE PROPERTY(filterZReportDateFrom());
                    MOVE PROPERTY(filterZReportDateTo());
                    MOVE PROPERTY(nameFilterZReportDepartmentStore());
                    MOVE PROPERTY(filterZReportCashRegister());
                }
                MOVE z.box;   
             }
            MOVE b.box;
        }

        NEW secondCase{
            fill = 1;
            type = SPLITH;

            MOVE d.box{
                caption = 'Строка чека';
                fill = 3;
            }
            MOVE p.box;
        }
    }

    MOVE functions.box;
}
@defineFilterIsOpened (zReport, zReports, z);

NAVIGATOR {
    retailNavigator {
        NEW ZReportNavigator 'Касса' BEFORE retailMasterData {
            ADD zReports;
        }
    }
}

countZReports 'Кол-во Z-отчетов' (dep, date) = GROUP SUM 1 IF isPosted(ZReport r) BY departmentStore(r), date(r);
sumZReports 'Сумма Z-отчетов' (dep, date) = GROUP SUM sumReceiptDetail(ZReport r) IF isPosted(r) BY departmentStore(r), date(r); 

countZReports 'Кол-во Z-отчетов' (s, date) = GROUP SUM 1 IF isPosted(ZReport r) BY store(departmentStore(r)), date(r);
sumZReports 'Сумма Z-отчетов' (s, date) = GROUP SUM sumReceiptDetail(ZReport r) IF isPosted(r) BY store(departmentStore(r)), date(r); 

EXTEND FORM zReports
    OBJECTS dt = DATE FIXED PANEL 
    PROPERTIES (dt) OBJVALUE        
    
    TREE treeStore1 a1=STRING[3], t1=ChainStores, st1=StoreType
    PROPERTIES READONLY OBJVALUE(a1), name(t1), name(st1)
    FILTERS chainStores(st1) == t1

    FILTERS stringEqualsAll(a1)
    FILTERS in (t1, st1)          
    
    OBJECTS s1=Store
    PROPERTIES(s1) READONLY name, id SHOWIF showIDs(), countCashRegister
    FILTERS in(t1, st1, s1)    
    PROPERTIES (s1,dt) READONLY countZReports, sumZReports       
    
    TREE treeStore a=STRING[3], t=ChainStores, st=StoreType, s = Store 
    PROPERTIES READONLY OBJVALUE(a), name(t), name(st), name(s)

    FILTERS stringEqualsAll(a)
    FILTERS in(t, st, s) 
 
    OBJECTS dep=DepartmentStore
    PROPERTIES(dep) READONLY name, id SHOWIF showIDs(), countSalesCashRegister
    PROPERTIES READONLY countZReports(dep,dt), sumZReports(dep,dt)
     
    FILTERS in(t, st, s, dep),
            isCompany(dep)    
    FILTERGROUP active
        FILTER 'Активные' countSalesCashRegister(dep) 'F5' DEFAULT
;

DESIGN zReports {
    NEW tabContainer BEFORE functions.box {
        fill = 1;
        type = TABBED;
        MOVE topContainer {caption = 'Z-отчеты';}
        NEW department {
            caption = 'Магазины';
            fill = 1;
            type = CONTAINERV;
            MOVE dt.box;
            NEW treeContainer {
                fill = 1;  
                type = TABBED;
                NEW treeContainer1{
                    fill = 1;
                    type = SPLITH;
                    caption = 'По магазинам';
                    MOVE treeStore1.tree.box;
                    MOVE s1.box { fill = 2;}                 
                }
                NEW treeContainer2{
                    fill = 1;
                    type = SPLITH;
                    caption = 'По отделам';
                    MOVE treeStore.tree.box;
                    MOVE dep.box { fill = 2;}                    
                }                
                
            }
        }
    }
}

@extendFormFilterStockGroupAccess(s1, zReports, company);
@extendFormFilterStockAccess(dep, zReports, company);


// ----------------------------------------------- Стандартные значения ------------------------------------- //

loadDefaultType 'Добавить тип оплаты'(VARISTRING[110] string, PaymentMeans paymentMeans, STRING[10] sid) = ACTION {
    FOR ADDOBJ p = PaymentType DO {
        name(p) <- string;
        paymentMeans(p) <- paymentMeans;
        sid(p) <- sid;
    }
}

overLoadDefaultPaymentTypes 'Загрузить дополнительные типы оплаты' = ACTION ABSTRACT LIST ();
loadDefaultPaymentTypes 'Загрузить стандартные типы оплаты'() = ACTION {
    loadDefaultType('Наличные', PaymentMeans.paymentMeansCash, 'cash');
    loadDefaultType('Карточка', PaymentMeans.paymentMeansCard, 'card');
    overLoadDefaultPaymentTypes();
} IN loadDefault;

@implementLoadDefaultData(loadDefaultPaymentTypes);

//--
isDateZReport 'Дата чека должна равняться дате Z-отчета' = DATA BOOLEAN ();

EXTEND FORM options
    PROPERTIES() isDateZReport
;

DESIGN options {
    commons {
        MOVE PROPERTY(isDateZReport());
    }
}

countDate (z) = GROUP SUM 1 IF date(zReport(Receipt r)) != date(r) IF sumSkuReceiptDetail(r) BY zReport(r);

CONSTRAINT isDateZReport() AND countDate(ZReport z) 
    MESSAGE 'В z-отчете должны быть чеки с одной датой';

