MODULE ZReportProcessing;

REQUIRE ZReport;

retailPriceReceiptDetail 'Розничная цена' (d)= IF batchReceiptDetail(d) 
    THEN priceAPriceListTypeBatchStockDateTime(SystemLedgerPriceListType.retailPricingPriceListType, batchReceiptDetail(d), departmentStoreReceiptDetail(d), dateTimeReceiptDetail(d)) 
    ELSE priceAPriceListTypeSkuStockDateTime(SystemLedgerPriceListType.retailPricingPriceListType, skuReceiptDetail(d), departmentStoreReceiptDetail(d), dateTimeReceiptDetail(d));

FORM ZReportProcessing 'Обработка Z-отчетов'
    OBJECTS ds = DepartmentStore FIXED PANEL
    PROPERTIES(ds) SELECTOR nameDepartmentStore 

    FILTERS isCompanyStock(ds)

    OBJECTS d = ReceiptDetail FIXED GRID
    PROPERTIES(d) READONLY FORCE GRID dateTimeReceiptDetail, typeReceiptDetail, idBarcodeReceiptDetail
    PROPERTIES(d) FORCE GRID nameSkuReceiptDetail ON CHANGE changeDialogSkuReceiptDetail(d)
    PROPERTIES(d) READONLY FORCE GRID descriptionSaleReceiptReturnDetail, quantityReceiptDetail, quantityReturnedReceiptSaleDetail,
                  priceReceiptDetail, sumReceiptDetail, discountPercentReceiptSaleDetail, discountSumReceiptDetail, numberVATReceiptDetail, 
                  valueVATReceiptDetail
    ORDER BY dateTimeReceiptDetail(d)              
    FILTERS departmentStoreReceiptDetail(d) == ds                  
    FILTERGROUP priceFilter
        FILTER  'Без расценки' skuReceiptDetail(d) AND NOT retailPriceReceiptDetail(d) 'F11'
        FILTER  'Разные цены' retailPriceReceiptDetail(d) != priceReceiptDetail(d) 'F10'
;

@extendFormFilterStockAccess(ds, ZReportProcessing);

NAVIGATOR {
    retailDashboardNavigator {
        ADD ZReportProcessing;
    }
}

