MODULE DisparityOperationStoreBy;

REQUIRE DisparityOperation, OperationDefault, RepricingOperationDefaultBy, RepricingDisparity;

NAMESPACE Disparity;

@defineCreateDefaultOperation();


loadDefaultDisparityOperations 'Загрузить стандартные операции (изменение сортности)' ()  { 
    createDefaultOperation('Уценка','disparity');   
    FOR operation('disparity') ==  Operation o DO {
        createRepricing(o) <- TRUE;  
        repricingOperation(o) <- Repricing.operation('by_default_repricing'); 
    }


} IN loadDefault;
    

loadDefaultOperations () + {  loadDefaultDisparityOperations(); }
