MODULE ConsignmentEInvoiceTracking;

REQUIRE ConsignmentEInvoice, ItemTracking, TrackingLedger;

NAMESPACE Consignment;

isTracking = ABSTRACT VALUE BOOLEAN (ConsignmentDetail);
isTracking(ConsignmentDetail cd) += isTrackingOver(sku(cd)) AND date(consignment(cd)) >= dateStartSPT(sku(cd)) ;

trackingUOM = ABSTRACT VALUE STRING[3] (ConsignmentDetail);
trackingUOM(ConsignmentDetail cd) += trackingUOMCustomsGroup(sku(cd));

overCreate(EInvoiceDetail eid, ConsignmentDetail cd) + {
    //чтобы ТНВЭД и 4х зн код передавался для всех товаров с такими свойствами, а не только для прослеживаемых
    itemCustomCode(eid) <- codeCustomsGroupDefaultCountry(sku(cd));
    itemCustomCodeOther(eid) <- idExtraCode(sku(cd));
    IF isTracking(cd) THEN {
        itemCustomCode(eid) <- codeCustomsGroupDefaultCountry(sku(cd));
        itemCustomCodeOther(eid) <- idExtraCode(sku(cd));
        deliveryTypePrev(eid) <- deliveryTypePrev(trackingLedger(cd));
        deliveryNotePrev(eid) <- deliveryNotePrev(trackingLedger(cd));
        deliveryNoteDatePrev(eid) <- DATETIME(deliveryNoteDate(trackingLedger(cd)));
        deliveryNotePrevLineID(eid) <- deliveryNotePrevLineID(trackingLedger(cd));
        lineItemQuantitySPT(eid) <- trackingUOM(cd);
        quantityDespatchedSPT(eid) <- NUMERIC[12,5](OVERRIDE despatchUnitQuantityDespatched(cd), NUMERIC[12,5](quantity(cd)), 1.0);
        // на данный момент прослеживаемые только шт
        //            (CASE
        //            WHEN (OVERRIDE lineItemQuantitySPT(batch(cd), supplierStock(consignment(cd)))=='112' OR trackingUOM(cd)=='112')
        //                THEN ((OVERRIDE despatchUnitQuantityDespatched(cd), NUMERIC[12,5](quantity(cd)), 1.0)* volume(sku(cd))) 
        //            WHEN (OVERRIDE lineItemQuantitySPT(batch(cd), supplierStock(consignment(cd)))=='166' OR trackingUOM(cd)=='166') 
        //                THEN ((OVERRIDE despatchUnitQuantityDespatched(cd), NUMERIC[12,5](quantity(cd)), 1.0)* netWeight(sku(cd)))
        //            ELSE (OVERRIDE despatchUnitQuantityDespatched(cd), NUMERIC[12,5](quantity(cd)), 1.0));

        lineItemPriceSPT(eid) <- NUMERIC[12,2](price(cd));
        // на данный момент прослеживаемые только шт
        //            (CASE
        //            WHEN (OVERRIDE lineItemQuantitySPT(batch(cd), supplierStock(consignment(cd)))=='112' OR trackingUOM(cd)=='112') THEN (price(cd)/ volume(sku(cd))) 
        //            WHEN (OVERRIDE lineItemQuantitySPT(batch(cd), supplierStock(consignment(cd)))=='166' OR trackingUOM(cd)=='166') THEN (price(cd)/ netWeight(sku(cd)))
        //            ELSE price(cd));
    }
}
