MODULE ConsignmentDashboardEInvoice;

REQUIRE ConsignmentEInvoice, ConsignmentDashboard;

NAMESPACE Order;


EXTEND FORM consignmentDashboard
    PROPERTIES include(i)
    PROPERTIES READONLY isEInvoice(i), numberEInvoice(i)
    PROPERTIES READONLY statusDescription =statusDescription(i) BACKGROUND backgroundStatusDescription(i)
    PROPERTIES READONLY PANEL numberEInvoicePanel = numberEInvoice(i)
    PROPERTIES(i) createEInvoice SHOWIF (NOT eInvoice(i) AND NOT hideCreateEInvoice(i)), statusDescription SHOWIF eInvoice(i) PANEL, 
                      signAndSendSupplierEDI SHOWIF (eInvoice(i) AND NOT exportedSupplier(eInvoice(i))), 
                      cancelSignAndSendSupplierEDI SHOWIF (eInvoice(i) AND exportedSupplier(eInvoice(i)))    
    PROPERTIES(i) editAttributesEInvoice  SHOWIF (eInvoice(i) AND showEditEInvoiceCurrent())
    PROPERTIES    editAttributes = editAttributes(i) SHOWIF eInvoice(i)
    PROPERTIES(i) SHOWIF (eInvoice[Invoice](i) AND NOT hidePrintEInvoice(i)) printConsignmentEInvoiceAttachment,  printConsignmentEInvoice, 
                  printConsignmentEAttachment, printConsignmentEAttachmentXLSX
    PROPERTIES () printConsignmentEInvoices TOOLBAR DRAW i SHOWIF ((GROUP SUM 1 IF include(Invoice iii)) AND NOT hidePrintEInvoice(i))
;

DESIGN consignmentDashboard {
    tabContainer {
        NEW eInvoice {
            caption = 'Электронная накладная';
            NEW createEI {
                type = CONTAINERH;
                MOVE PROPERTY(numberEInvoicePanel);
                MOVE PROPERTY(createEInvoice(i));
                MOVE PROPERTY(editAttributesEInvoice(i));
                MOVE PROPERTY(editAttributes);
                MOVE PROPERTY(signAndSendSupplierEDI(i));
                MOVE PROPERTY(statusDescription(i));
            }
            NEW printEI {
                type = CONTAINERH;
                MOVE PROPERTY (printConsignmentEInvoiceAttachment(i));
                MOVE PROPERTY (printConsignmentEInvoice(i));
                MOVE PROPERTY (printConsignmentEAttachment(i));
            }
            NEW exportEI {
                type = CONTAINERH;
                MOVE PROPERTY (printConsignmentEAttachmentXLSX(i));
            }
        }
    }
}