MODULE EInvoiceEDS;

REQUIRE EInvoice, EDS;

NAMESPACE EDI;

EDSServiceCustomer = ABSTRACT CASE EDSService (STRING[100], EInvoice);

EDSServiceSupplier = ABSTRACT CASE EDSService (STRING[100], EInvoice);

//STRING[100] provider, EInvoice eInvoice, FILE contentSubXML, BOOLEAN interactive
getSignedDocumentSupplier ABSTRACT LIST FIRST (STRING[100], EInvoice, FILE, BOOLEAN);

//STRING[100] provider, EInvoice eInvoice, FILE contentSubXML, BOOLEAN interactive
getSignedDocumentCustomer ABSTRACT LIST FIRST (STRING[100], EInvoice, FILE, BOOLEAN);


EDSServiceCustomer = ABSTRACT CASE EDSService (STRING[100], ECreditNote);

EDSServiceSupplier = ABSTRACT CASE EDSService (STRING[100], ECreditNote);

//getSignedDocumentSupplier(STRING[100] provider, ECreditNote e, FILE contentSubXML, BOOLEAN interactive)
getSignedDocumentSupplier ABSTRACT LIST FIRST (STRING[100], ECreditNote, FILE, BOOLEAN);

//getSignedDocumentCustomer(STRING[100] provider, ECreditNote e, FILE contentSubXML, BOOLEAN interactive)
getSignedDocumentCustomer ABSTRACT LIST FIRST (STRING[100], ECreditNote, FILE, BOOLEAN);

//V2

getSignedDocumentCustomerV2 ABSTRACT LIST FIRST (STRING[100], EInvoice, STRING, BOOLEAN);
getSignedDocumentSupplierV2 ABSTRACT LIST FIRST (STRING[100], EInvoice, STRING, BOOLEAN);