MODULE PurchaseEInvoiceLot;

REQUIRE PurchaseEInvoice, PurchaseShipmentLot, EInvoiceLot, LotAggregate;

NAMESPACE Purchase;

overCopy(EInvoiceDetail eid, UserInvoiceDetail id) + {
    FOR EInvoiceLotDetail el == [GROUP MAX EInvoiceLotDetail dd BY eInvoiceDetail(dd), id(dd)](eid, STRING[200] str) AND NOT lot(str) DO NEW l = Lot {
        id(l) <- str;
        sku(l) <- sku(id);
        dataCount(l) <- (GROUP SUM quantity(EInvoiceLotDetail dd) IF eInvoiceDetail(dd) == eid AND id(dd) == str)
            IF (GROUP SUM quantity(EInvoiceLotDetail dd) IF eInvoiceDetail(dd) == eid AND id(dd) == str) != 1;
        //status(l) <- status(tl);
    }
    quantity(id, Lot l) <- (GROUP SUM 1 IF eInvoiceDetail(EInvoiceLotDetail dd) == eid AND l == lot(id(dd)));
}