MODULE LabelDirectPrintBy;

REQUIRE LabelDirectPrint, LabelBy;


overDirectPrint(LabelTransactionDetail ld) + { 

    IF basePrice(ld) THEN {
        formattedText() <- replace(formattedText(),'@basePrice@', VARSTRING[20](NUMERIC[16,2](basePrice(ld))));
    } ELSE formattedText() <- replace(formattedText(),'@basePrice@', '');    
    IF basePriceRub(ld) THEN {
        formattedText() <- replace(formattedText(),'@basePriceRub@', VARSTRING[20](basePriceRub(ld)));
    } ELSE formattedText() <- replace(formattedText(),'@basePriceRub@', '');    
    IF basePriceKop(ld) THEN {
        formattedText() <- replace(formattedText(),'@basePriceKop@', VARSTRING[20](basePriceKop(ld)));
    } ELSE formattedText() <- replace(formattedText(),'@basePriceKop@', '');    
    IF baseRetailPrice(ld) THEN {
        formattedText() <- replace(formattedText(),'@baseRetailPrice@', VARSTRING[20](NUMERIC[16,2](baseRetailPrice(ld))));
    } ELSE formattedText() <- replace(formattedText(),'@baseRetailPrice@', '');    
    IF basePriceName(ld) THEN {
        formattedText() <- replace(formattedText(),'@basePriceName@', 'руб /' + basePriceName(ld));
    } ELSE formattedText() <- replace(formattedText(),'@basePriceName@', '');  

}
