MODULE RepricingPurchaseInvoiceBy;

REQUIRE RepricingPurchaseInvoice, RepricingBy;

NAMESPACE Repricing;

overExtraValuation (RepricingDetail rd, Purchase.InvoiceDetail detail) + {
    curVAT(rd) <- OVERRIDE lastVatPriceListLedger(sku(detail), customerStock(detail), dateTime(detail)), VAT(detail);
    valueCurVAT(rd) <- OVERRIDE lastValueVatPriceListLedger(sku(detail), customerStock(detail), dateTime(detail)), valueVAT(detail);
    skipChangeVAT(rd) <- TRUE;
}

overExtraRevertValuation (RepricingDetail rd, Purchase.InvoiceDetail detail) + {
    curVAT(rd) <- OVERRIDE lastVatPriceListLedger(sku(detail), customerStock(detail), dateTime(detail)), VAT(detail);
    valueCurVAT(rd) <- OVERRIDE lastValueVatPriceListLedger(sku(detail), customerStock(detail), dateTime(detail)), valueVAT(detail);
    skipChangeVAT(rd) <- TRUE;
}