MODULE ArtixAPI; // Настройки API сервера Artix

NAMESPACE Artix;

hostArtix 'Хост' = DATA STRING[255] () CHARWIDTH 50;
portArtix 'Порт' = DATA STRING[255] () CHARWIDTH 4;
userArtix 'Пользователь' = DATA STRING[255] () CHARWIDTH 50;
passwordArtix 'Пароль' = DATA STRING[255] () ECHO CHARWIDTH 50;

urlArtixCS 'URL Artix Cash Server' () = 'http://' + hostArtix() + ':' + portArtix() + '/CSrest/rest/';
urlArtixLM 'URL Artix Loyality Managment' () = 'http://' + hostArtix() + ':' + portArtix() + '/ACC/rest/v1/';

EXTEND FORM integrationData
    PROPERTIES() hostArtix, portArtix, userArtix, passwordArtix
;

DESIGN integrationData {
    pane {
        NEW artix {
            caption = 'Artix';
            fill = 1;
            NEW artixAPISettings {
                caption = 'Параметры API';
                MOVE PROPERTY(hostArtix());
                MOVE PROPERTY(portArtix());
                MOVE PROPERTY(userArtix());
                MOVE PROPERTY(passwordArtix());
            }
        }
    }
}