MODULE GISMTLotInit;

REQUIRE GISMTDocument, LotInit;

NAMESPACE GISMT;

DESIGN lotInits {
    tabbedPane {
        NEW gismt {
            caption = 'ГИС МТ';
        }
    }
}

EXTEND CLASS LotInit : Document;

id (LotInit i) += Lot.id(i);
dateTime (LotInit i) += Lot.dateTime(i);
type (LotInit i) += Lot.type(i);
gismtType (LotInit i) += 'LP_INTRODUCE_OST' IF i IS LotInit;

legalEntity (LotInit i) += legalEntityStock(i);

isPosted(LotInit i) += Lot.isPosted(i);
canceled(LotInit i) += Lot.canceled(i);

FORM exportLotInit
    OBJECTS i = LotInit PANEL
    
    PROPERTIES trade_participant_inn = inn(legalEntityStock(i))
    
    OBJECTS products_list = (d = LotInitDetail, l = Lot)
    PROPERTIES ki = id(l)
    FILTERS lotInit(d) = i, quantity(d, l)
;

export (LotInit i) + {
    EXPORT exportLotInit OBJECTS i = i JSON;
}

EXTEND FORM lotInits
    PROPERTIES(i) READONLY status, downloadDesc PANEL
    PROPERTIES(i) create SHOWIF NOT id(i)
;

DESIGN lotInits {
    gismt {
        MOVE PROPERTY(create(i));
        MOVE PROPERTY(downloadDesc(i));
    }
}