MODULE GISMTWriteOff;

REQUIRE GISMTDocument, WriteOffLot;

NAMESPACE GISMT;

@defineDocumentGISMT(writeOff, isPosted, writeOffs, w, legalEntityStock, 'LK_RECEIPT');

FORM exportWriteOff
    OBJECTS i = WriteOff, t = LotType PANEL
    
    PROPERTIES action = 'DAMAGE_LOSS', action_date = toDateISO(date(i)), 
               document_date = toDateISO(date(i)), document_number = seriesNumber(i),
               document_type = 'DESTRUCTION_ACT', inn = inn(legalEntityStock(i))
    
    OBJECTS products = (d = WriteOffDetail, l = Lot)
    PROPERTIES cis = id(l)
    FILTERS writeOff(d) = i, quantity(d, l), lotType(sku(l)) = t
;

export (WriteOffDocument i) + {
    EXPORT exportWriteOff OBJECTS i = writeOff(i), t = lotType(i) JSON;
}
 