MODULE LegalEntityEDIRu;

REQUIRE LegalEntityRu;

NAMESPACE LegalEntity;

//participant id
idEdi 'ИД участника документооборота' = DATA STRING[46] (LegalEntity);
legalEntityUpd (id) = GROUP AGGR LegalEntity legalEntity BY idEdi (legalEntity);

EXTEND FORM legalEntity
    PROPERTIES (l) idEdi
;

DESIGN legalEntity {
    column1 {
        NEW edo {
            caption = 'ЭДО';
            MOVE PROPERTY(idEdi(l));
        }
    }
}

EXTEND FORM legalEntities
    PROPERTIES (l) READONLY idEdi
;