MODULE WriteOffLot;

REQUIRE WriteOff, Lot;

NAMESPACE WriteOff;

@defineOperationProperty(useLot, 'Марки', showContainer);

useLot(WriteOff a) = useLot(operation(a));

@defineDocumentLotOut(userWriteOff, stock, quantity, w, isPosted);

@defineDocumentLotType(writeOff);

quantity = ABSTRACT NUMERIC[16,5] (WriteOffDetail, Lot);
quantity(UserWriteOffDetail d, Lot l) += quantity(d, l);