MODULE ImportTNVED;

REQUIRE DefaultData, Country, CustomsGroup;


//---------------------------------------------- Импорт ТНВЭД -----------------------------------------------------//

GROUP tnved 'ТНВЭД' : public;

importTNVEDClassifierAction 'Импортировать справочник (файл TNVED4.DBF)'  INTERNAL  'lsfusion.erp.region.by.certificate.declaration.ImportTNVEDClassifierAction' () IN tnved;
importTNVEDCustomsRatesAction 'Импортировать платежи (файл TNVED_ST.DBF)'  INTERNAL  'lsfusion.erp.region.by.certificate.declaration.ImportTNVEDCustomsRatesAction' () IN tnved;
importTNVEDCustomsExceptionsAction 'Импортировать льготы (файл TNVED_PL.DBF)'  INTERNAL  'lsfusion.erp.region.by.certificate.declaration.ImportTNVEDCustomsExceptionsAction' () IN tnved;

EXTEND FORM defaultData
    PROPERTIES() importTNVEDClassifierAction, importTNVEDCustomsRatesAction, importTNVEDCustomsExceptionsAction
;

DESIGN defaultData {
    pane {
        NEW customs {
            caption = 'ТН ВЭД';

            MOVE PROPERTY(importTNVEDClassifierAction());
            MOVE PROPERTY(importTNVEDCustomsRatesAction());
            MOVE PROPERTY(importTNVEDCustomsExceptionsAction());
        }
    }
}
