MODULE SaleInvoiceTax;

REQUIRE SaleInvoice, SkuLedgerTax;

NAMESPACE Sale;

over1VATUserInvoiceDetail(detail) += VATBatch(batchUserInvoiceDetail(detail));

overDeriveValueVATUserInvoiceDetail (d) += lastValueVATSkuStockDateTime(skuUserInvoiceDetail(d), supplierStockUserInvoiceDetail(d), dateTimeUserInvoiceDetail(d));

// не берем НДС 0, потому что это может быть льгота, а дальше нужно перемещать/продавать с полным НДС
overSetValueVATUserInvoiceDetail(detail) += valueVATBatch(batchUserInvoiceDetail(detail));

// todo : временное решение, пока нету последовательности выполнения событий
WHEN SESSION FORMS userInvoice CHANGED(batchUserInvoiceDetail(d)) DO {
    valueVATUserInvoiceDetail(d) <- calcSetValueVATUserInvoiceDetail (d); 
}
