MODULE LabelBy;

REQUIRE Label;

NAMESPACE Label;

denominationDivider = IF currentDate() < denominationDate() THEN 10000.0 ELSE 1.0;
denominationMultiplier = IF currentDate() < denominationDate() THEN 1.0 ELSE 10000.0;

priceRubB 'Рубли' (LabelTransactionDetail d) = divideInteger(price(d), denominationDivider());
priceKopB 'Копейки' (LabelTransactionDetail d) = lpad((OVERRIDE '' IF priceRubB(d), VARSTRING[2](round0(abs(priceRubB(d) (-) round2(price(d) / denominationDivider()))*100.0))), 2, '0');

retailPriceRubB 'Рубли (цена до)' (LabelTransactionDetail d) = divideInteger(retailPrice(d), denominationDivider());
retailPriceKopB 'Копейки (цена до)' (LabelTransactionDetail d) = lpad((OVERRIDE '' IF retailPriceRubB(d), VARSTRING[2](round0(abs(retailPriceRubB(d) (-) round2(retailPrice(d) / denominationDivider()))*100.0))), 2, '0');

discountPriceRubB 'Рубли (скидка)' (LabelTransactionDetail d) = divideInteger(discountSum(d), denominationDivider());
discountPriceKopB 'Копейки (скидка)' (LabelTransactionDetail d) = lpad((OVERRIDE '' IF discountPriceRubB(d), VARSTRING[2](round0(abs(discountPriceRubB(d) (-) round2(discountSum(d) / denominationDivider()))*100.0))), 2, '0');


priceA 'Цена' (LabelTransactionDetail d) = price(d) * denominationMultiplier();
retailPriceA 'Цена до' (LabelTransactionDetail d) = retailPrice(d) * denominationMultiplier();
discountPriceA 'Скидка' (LabelTransactionDetail d) = discountSum(d) * denominationMultiplier();


EXTEND FORM printLabelTransaction PROPERTIES(d) READONLY priceRubB, priceKopB, retailPriceRubB, retailPriceKopB, discountPriceRubB, discountPriceKopB, priceA, retailPriceA, discountPriceA;
EXTEND FORM customLabelTransaction PROPERTIES(d) priceRubB, priceKopB, retailPriceRubB, retailPriceKopB, discountPriceRubB, discountPriceKopB, priceA, retailPriceA, discountPriceA;
EXTEND FORM labelTransactions 
    PROPERTIES(dt) READONLY priceRubB, priceKopB, retailPriceRubB, retailPriceKopB, discountPriceRubB, discountPriceKopB, priceA, retailPriceA, discountPriceA 
    PROPERTIES(dts) READONLY priceRubB, priceKopB, retailPriceRubB, retailPriceKopB, discountPriceRubB, discountPriceKopB, priceA, retailPriceA, discountPriceA
;