MODULE PickingTerminal;

REQUIRE Terminal, Picking;

NAMESPACE Picking;

skipFillBatch = ABSTRACT CASE BOOLEAN (PickingDetail);

@defineAddDetailDialogTerminal(userPicking, sku, stock);

EXTEND FORM userPicking
    PROPERTIES(o) addDetailDialogTerminalUserPickingDetail
;

DESIGN userPicking {
    headerRow1 {
        NEW import {
            caption = 'Импорт';
            horizontal = TRUE;
            height = 45;
            MOVE PROPERTY(addDetailDialogTerminalUserPickingDetail(o));
        }
    }
}