MODULE SalePickingOrder;

REQUIRE OrderPickingOrder, OrderInvoicePickingOrder, SaleOrder, SaleInvoice;

NAMESPACE Sale;

@defineOrderPickingOrder(' (продажа)', supplierStock);

@defineOrderInvoicePickingOrder (' (продажа)');

// Операция
@defineOperationProperty(createPickingOrder, 'Заказ на комплектацию', createContainer);
@deriveDocumentOperationProperty(UserOrder, createPickingOrder);