MODULE Vetis;

REQUIRE Certificate, Utils, Stock;

NAMESPACE Vetis;

login 'Логин' = DATA STRING[100]();
password 'Пароль' = DATA STRING[100]() ECHO;

encodeText = FORMULA TEXT 'encode(convert_to(($1),\'UTF8\'),($2))';

httpHeaders(TEXT name) = CASE
    WHEN name = 'Authorization' THEN 'Basic ' + encodeText(login() + ':' + password(), 'base64');

formatT (DATETIME dt) = replace(toChar(dt, 'yyyy-MM-dd T HH24:MI:SS'),' ','');

initDefaultProd 'Заполнить по умолчанию (Продуктивный контур)' ABSTRACT LIST ();
initDefaultTest 'Заполнить по умолчанию (Тестовый контур)' ABSTRACT LIST ();

EXTEND FORM integrationData
    PROPERTIES() login, password
    
    PROPERTIES() initDefaultProd, initDefaultTest 
;

DESIGN integrationData {
    pane {
        NEW vetis {
            caption = 'Ветис';
            NEW actions {
                type = CONTAINERH;
                MOVE PROPERTY(initDefaultProd());
                MOVE PROPERTY(initDefaultTest());
            }
            MOVE PROPERTY(login());
            MOVE PROPERTY(password());
        }
    }
}

// export / import
GROUP body EXTID 'soapenv=http://schemas.xmlsoap.org/soap/envelope/:Body';

header = DATA LOCAL STRING();

count 'Начальная запись' = DATA LOCAL INTEGER();
offset 'Кол-во записей' = DATA LOCAL INTEGER();

guid = DATA LOCAL STRING();

guid = DATA LOCAL STRING(INTEGER);
name = DATA LOCAL STRING(INTEGER);
fullName = DATA LOCAL STRING(INTEGER);

// navigator
NAVIGATOR {
    customsNavigator {
        NEW FOLDER vetisNavigator 'Ветис' {
            NEW FOLDER vetisDocuments 'Документы';
            NEW FOLDER vetisMasterData 'Справочники';
        }
    }
}
 
