MODULE CashOperationPOS;

REQUIRE POS, CashOperationZReport;

NAMESPACE CashOperation;

overClose (ZReport zReport) += ACTION {
    IF curSum(cashRegister(zReport)) THEN {
        FOR NEW o = OutcomeCashOperation DO {
            date(o) <- date(zReport);
            time(o) <- time(zReport);
//            departmentStoreOutcomeCashOperation(o) <- departmentStoreZReport(zReport);
            cashRegister(o) <- cashRegister(zReport);
            sumCash(o) <- curSum(cashRegister(zReport));
        }
    }
}
