MODULE LabelOrderInvoiceDashboard;

REQUIRE PurchaseOrderInvoiceDashboard;

NAMESPACE Purchase;

EXTEND FORM orderInvoiceDashboard
    PROPERTIES(i) statusLabel  BACKGROUND backgroundPrintLabelTransaction(i) READONLY ,
              createLabelTransaction SHOWIF showToPrintLabelTransaction(i), createSnapshotLabelTransaction
              
;
DESIGN orderInvoiceDashboard {
    actions {
        MOVE PROPERTY (createLabelTransaction(i));
        MOVE PROPERTY (createSnapshotLabelTransaction(i));            
    }
}