MODULE PurchaseReturnInvoiceGeneralLedger;

REQUIRE GeneralLedger, PurchaseReturnInvoice, DimensionLegalEntity, DimensionStock, DimensionTax;

NAMESPACE PurchaseReturn;

//------------------- Приход товара/тары от поставщ. --------------------//

EXTEND CLASS Invoice : GeneralLedger.GLDocument;
isPostedGLDocument(document) += isPostedInvoice(document);
nameGLDocument(document) += descriptionInvoice(document);

numberGLDocument(document) += numberInvoice(document);
seriesGLDocument(document) += seriesInvoice(document);

dateTimeGLDocument(document) += dateTimeInvoice(document);
operationGLDocument(document) += operationInvoice(document);
//editGLDocument (GLDocument)+= ACTION editInvoice(GLDocument);

descriptionInvoiceRange(invoice, range) =  CONCAT ', ', descriptionInvoice(invoice),
                                                       staticCaption(taxRange(range)),
                                                       'шкала' + numberRange(range),
                                                       'тек.ставка' + valueRateRangeDate(range, dateInvoice(invoice)); 
                                                          
///////////////////////// Сторно ///////////////////////////
//-------------------------------- НДС поставщика с разбивкой по ставке----------------------------------//
//-- Тара
negativeVATSumContainerInvoiceDetailInvoiceRange (invoice, range) = -VATSumContainerInvoiceDetailInvoiceRange(invoice, range);
@defineGeneralLedgerAggregationOperation (invoice,                                      // основание
                                          range,                                        // шкала
                                          InvSupVATC,                                   // идентификатор
                                          customer,                                     // компания
                                          negativeVATSumContainerInvoiceDetail,          // сумма
                                          description,                                  // описание
                                          '18.5',                                       // дебет
                                          '60.1',                                       // кредит
                                          'by_default',                                 // идентификатор плана счетов
                                          'by_default_purchase_invoice'                         // идентификатор операции
                                          );
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupVATCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock THEN customerStockInvoice(invoiceInvSupVATCGeneralLedger(generalLedger));
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupVATCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.range THEN rangeInvSupVATCGeneralLedger(generalLedger);

creditGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupVATCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.organization THEN supplierInvoice(invoiceInvSupVATCGeneralLedger(generalLedger));
idOperationGeneralLedger(l) += '01' IF l IS InvSupVATCGeneralLedger;    

//-- Услуги
negativeVATSumChargeInvoiceDetailInvoiceRange (invoice, range) = -VATSumChargeInvoiceDetailInvoiceRange(invoice, range);

@defineGeneralLedgerAggregationOperation (invoice,
                                          range,
                                          InvSupVATCH,
                                          customer,
                                          negativeVATSumChargeInvoiceDetail,
                                          description,
                                          '18.6',
                                          '60.1',
                                          'by_default',
                                          'by_default_purchase_invoice'
                                          );
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupVATCHGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock THEN customerStockInvoice(invoiceInvSupVATCHGeneralLedger(generalLedger));
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupVATCHGeneralLedger(generalLedger)) AND dimensionType == DimensionType.range THEN rangeInvSupVATCHGeneralLedger(generalLedger);

creditGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupVATCHGeneralLedger(generalLedger)) AND dimensionType == DimensionType.organization THEN supplierInvoice(invoiceInvSupVATCHGeneralLedger(generalLedger));
idOperationGeneralLedger(l) += '01' IF l IS InvSupVATCHGeneralLedger;    

//-- Товар
negativeVATSumItemInvoiceDetailInvoiceRange (invoice, range) = -VATSumItemInvoiceDetailInvoiceRange(invoice, range);

@defineGeneralLedgerAggregationOperation (invoice,
                                          range,
                                          InvSupVATI,
                                          customer,
                                          negativeVATSumItemInvoiceDetail,
                                          description,
                                          '18.1',
                                          '60.1',
                                          'by_default',
                                          'by_default_purchase_invoice'
                                          );
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupVATIGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock THEN customerStockInvoice(invoiceInvSupVATIGeneralLedger(generalLedger));
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupVATIGeneralLedger(generalLedger)) AND dimensionType == DimensionType.range THEN rangeInvSupVATIGeneralLedger(generalLedger);
creditGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupVATIGeneralLedger(generalLedger)) AND dimensionType == DimensionType.organization THEN supplierInvoice(invoiceInvSupVATIGeneralLedger(generalLedger));
idOperationGeneralLedger(l) += '01' IF l IS InvSupVATIGeneralLedger;    

//-------------------------------- Сумма поставщика ----------------------------------//
//-- Тара
negativeSumContainerInvoiceDetailInvoice (invoice) = -sumContainerInvoiceDetailInvoice(invoice);

@defineGeneralLedgerAggregationOperation (invoice,
                                          InvSupC,
                                          customer,
                                          negativeSumContainerInvoiceDetail,
                                          description,
                                          '41.3',
                                          '60.1',
                                          'by_default',
                                          'by_default_purchase_invoice'
                                          );
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock THEN customerStockInvoice(invoiceInvSupCGeneralLedger(generalLedger));
creditGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.organization THEN supplierInvoice(invoiceInvSupCGeneralLedger(generalLedger));
idOperationGeneralLedger(l) += '01' IF l IS InvSupCGeneralLedger;    

//-- Товар
negativeSumItemInvoiceDetailInvoice (invoice) = -sumItemInvoiceDetailInvoice(invoice);

@defineGeneralLedgerAggregationOperation (invoice,
                                          InvSupIH,
                                          customer,
                                          negativeSumItemInvoiceDetail,
                                          description,
                                          '41.2',
                                          '60.1',
                                          'by_default',
                                          'by_default_purchase_invoice'
                                          );
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupIHGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock THEN customerStockInvoice(invoiceInvSupIHGeneralLedger(generalLedger));
creditGeneralLedgerDimensionType(generalLedger,dimensionType) += WHEN CLASS(invoiceInvSupIHGeneralLedger(generalLedger)) AND dimensionType == DimensionType.organization THEN supplierInvoice(invoiceInvSupIHGeneralLedger(generalLedger));
idOperationGeneralLedger(l) += '01' IF l IS InvSupIHGeneralLedger;    

// ----------------------------------- Стандартные данные ----------------------------------- //

@defineLoadDefaultOperation (Purchase, iname, isid);
loadDefaultOperationsPurchaseInvoiceBy 'Загрузить стандарные операции прихода товара' () = ACTION () {
    EXEC loadDefaultOperation ('Приход товара от поставщика', 'by_default_purchase_invoice');
} ;

loadDefaultOperations () += ACTION loadDefaultOperationsPurchaseInvoiceBy();

@extendFormGeneralLedgerDocument(invoices, i);