MODULE BOMHeatTreatment;

REQUIRE BOM;

heatTechnology 'Тепловая обработка' = DATA BOOLEAN (Technology);

EXTEND FORM technology
    PROPERTIES(t)  heatTechnology
;

EXTEND FORM technologies 
    PROPERTIES(t)  READONLY AFTER nameTechnology(t) heatTechnology
;

heatWastageComponent 'Тепловая обработка' = DATA BOOLEAN (Component);

EXTEND FORM BOM
    PROPERTIES(c)  BACKGROUND backgroundComponent(c) heatWastageComponent AFTER wastageComponent(c)
;
EXTEND FORM BOMs 
    PROPERTIES(c)  BACKGROUND backgroundComponent(c) READONLY AFTER wastageComponent(c) heatWastageComponent
    PROPERTIES(c1)  BACKGROUND backgroundComponent(c1) READONLY AFTER wastageComponent(c1) heatWastageComponent    
;

EXTEND FORM BOMsDialog
    PROPERTIES(c)  BACKGROUND backgroundComponent(c) READONLY AFTER wastageComponent(c) heatWastageComponent
;