MODULE SalePurchaseManufacturingPrice;

REQUIRE SaleManufacturingPrice, PurchaseManufacturingPrice, SalePurchaseInvoiceOrder, PricingSalePurchase;

PRIORITY Sale;

//----------------------------------------------------------------------------//

overPurchasePricingPriceUserInvoiceDetail(detail) += manufacturingPriceUserInvoiceDetail(detail);

Purchase.showManufacturingPriceInvoice(invoice) += showManufacturingPriceInvoice(invoicePurchaseInvoice(invoice));
Purchase.manufacturingPriceInvoiceDetail(invoiceDetail) += manufacturingPriceInvoiceDetail(invoiceDetailPurchaseInvoiceDetail(invoiceDetail));
Purchase.manufacturingSumInvoiceDetail(invoiceDetail) += manufacturingSumInvoiceDetail(invoiceDetailPurchaseInvoiceDetail(invoiceDetail));

overFillInvoiceUserInvoiceInvoice (sd, id) += ACTION ASSIGN Purchase.showManufacturingPriceUserInvoice (sd) <- showManufacturingPriceInvoice(id);
overFillInvoiceUserInvoiceDetailInvoiceDetail (sd, id) += ACTION ASSIGN Purchase.manufacturingPriceUserInvoiceDetail (sd) <- manufacturingPriceInvoiceDetail(id);

overFillOrderUserOrderInvoice (sd, id) += ACTION ASSIGN Purchase.showManufacturingPriceUserOrder (sd) <- showManufacturingPriceInvoice(id);
overFillOrderUserOrderDetailInvoiceDetail (sd, id) += ACTION ASSIGN Purchase.manufacturingPriceUserOrderDetail (sd) <- manufacturingPriceInvoiceDetail(id);