MODULE PurchaseInvoiceContract;

REQUIRE PurchaseInvoice, InvoiceContract, ContractPayment;

NAMESPACE Purchase;

@defineInvoicePaymentCondition(' (закупка)');

@defineInvoiceContractSum();
// ------------------- Проведение по регистру задолженностей ----------------------- //

@implementContractLedger(a, Invoice, contractSku);

reverseContractSum = ABSTRACT NUMERIC[18,4] (Invoice);
sum[ContractALedger](Invoice contractALedger) += OVERRIDE contractSum(contractALedger), invoiceSumInvoiceDetail(contractALedger) (-) reverseContractSum(contractALedger);

TABLE invoicePaymentPeriod (Invoice, PaymentPeriod);
@implementContractPrepaymentLedger(invoice, invoiceSumInvoiceDetail, contractSku);

@implementInContractLedger(Invoice, contractSku);
 
sum[InContractLedger](Invoice inContractLedger) += OVERRIDE contractSum(inContractLedger), invoiceSumInvoiceDetail(inContractLedger) (-) reverseContractSum(inContractLedger);

inContractLedger[ContractLedger](InvoiceContractLedger l) += invoice(l);