MODULE PurchaseReturnInvoiceContract;

REQUIRE PurchaseReturnInvoice, InvoiceContract, ContractPayment;

NAMESPACE PurchaseReturn;

@defineInvoiceContractSum();

// ------------------- Проведение по регистру задолженностей ----------------------- //

@implementContractLedger(, Invoice, contractSku);
sum[ContractLedger](Invoice contractLedger) += 
    (OVERRIDE -contractSum(contractLedger), -invoiceSumInvoiceDetail(contractLedger)) 
    IF isSaleType(contractSku(contractLedger)) AND isPrepaymentType(paymentCondition(contractLedger));
skip[ContractLedger](Invoice contractLedger) += contractLedger IS Invoice AND NOT (isSaleType(contractSku(contractLedger)) AND isPrepaymentType(paymentCondition(contractLedger)));

@implementContractLedger(a, Invoice, contractSku);
customInvoiceSum = ABSTRACT NUMERIC[18,4] (Invoice); // предполагаем, что не используем reverseContractSum
sum[ContractALedger](Invoice contractALedger) += OVERRIDE -contractSum(contractALedger), -customInvoiceSum(contractALedger), -invoiceSumInvoiceDetail(contractALedger); 

@implementOutContractLedger(Invoice, contractSku);
sum[OutContractLedger](Invoice outContractLedger) += OVERRIDE contractSum(outContractLedger), customInvoiceSum(outContractLedger), invoiceSumInvoiceDetail(outContractLedger);