MODULE SaleReturnShipmentBox;

REQUIRE Box, SaleReturnShipment, SaleShipmentBox;

NAMESPACE SaleReturn;

//---------------------------------Ячейка ----------------------------------//

@defineDocumentInterfaceDetailBox(shipment);
overCopy[UserShipmentDetail,UserShipmentDetail](UserShipmentDetail d, UserShipmentDetail detail) + {       
    box(d) <- box(detail);
}
@extendFormInterfaceDetailBox(shipment, s, , quantity);
@deriveDocumentOperationProperty(UserShipment, showBox);

//-- invoice
@defineInvoiceShipmentBox(supplierStock);
@deriveDocumentOperationProperty(UserInvoice, showBox);

