MODULE SaleCreditNoteContract;

REQUIRE SaleCreditNote, SaleInvoiceContract;

NAMESPACE Sale;

paymentCondition(InvoiceCreditNote creditNote) += paymentCondition(invoice(creditNote));

// --------------------------- Проведение по регистру задолженностей ------------------------------------ //

@implementContractLedger(, CreditNote, contractSku);
sum[ContractLedger](CreditNote contractLedger) += -invoiceSumCreditNoteDetail(contractLedger);

@implementContractLedger(a, CreditNote, contractSku);
sum[ContractALedger](CreditNote contractALedger) += -invoiceSumCreditNoteDetail(contractALedger);

@implementOutContractLedger(CreditNote, contractSku);
sum[OutContractLedger](CreditNote outContractLedger) += invoiceSumCreditNoteDetail(outContractLedger);
