MODULE BatchTracking;

REQUIRE PurchaseShipment, PurchaseInvoiceTracking ;

NAMESPACE Stock;

isTracking 'Подлежит прослеживанию' = ABSTRACT VALUE BOOLEAN (Batch);

deliveryTypePrev 'Тип приходного документа' = ABSTRACT VALUE INTEGER (Batch);
deliveryNotePrev 'Номер приходного документа'= ABSTRACT VALUE STRING[70] (Batch);
deliveryNoteDate 'Дата создания приходного документа' = ABSTRACT VALUE DATE (Batch);
deliveryNotePrevLineID 'Номер строки в приходном документе' = ABSTRACT VALUE INTEGER (Batch);
lineItemQuantitySPT 'Единица измерения прослеживаемости' = ABSTRACT VALUE STRING[3](Batch);
lineItemPriceSPT 'Цена за единицу товара для прослеживаемости' = ABSTRACT VALUE NUMERIC(Batch); // не записываем для партии по приходу, только по инвентаризации
quantityDespatchedSPT 'Количество в единицах прослеживаемости' = ABSTRACT VALUE NUMERIC[12,5] (Batch); // не записываем для партии по приходу, только по инвентаризации
itemCustomCode'Код ТНВЭД' = ABSTRACT VALUE STRING[10] (Batch);
itemCustomCodeOther 'Дополнительный таможенный код' = ABSTRACT VALUE STRING[4] (Batch);

deliveryTypePrev(ShipmentBatch batch) += deliveryTypePrev(invoiceDetail(shipmentDetail(batch)));
deliveryNotePrev(ShipmentBatch batch) += deliveryNotePrev(invoiceDetail(shipmentDetail(batch)));
deliveryNoteDate(ShipmentBatch batch) += deliveryNoteDate(invoiceDetail(shipmentDetail(batch)));
deliveryNotePrevLineID(ShipmentBatch batch) += deliveryNotePrevLineID(invoiceDetail(shipmentDetail(batch)));
lineItemQuantitySPT(ShipmentBatch batch) += lineItemQuantitySPT(invoiceDetail(shipmentDetail(batch)));
itemCustomCode(ShipmentBatch batch) += itemCustomCode(invoiceDetail(shipmentDetail(batch)));
itemCustomCodeOther(ShipmentBatch batch) += itemCustomCodeOther(invoiceDetail(shipmentDetail(batch)));