MODULE BatchInventoryTracking;

REQUIRE SkuLedger ;

NAMESPACE Stock;

isTracking 'Подлежит прослеживанию' = ABSTRACT VALUE BOOLEAN (Batch);
isTracking 'Подлежит прослеживанию' = DATA BOOLEAN (Batch, Stock);
deliveryTypePrev 'Тип приходного документа' = DATA INTEGER (Batch, Stock);
deliveryNotePrev 'Номер приходного документа'= DATA STRING[70] (Batch, Stock);
deliveryNoteDate 'Дата создания приходного документа' = DATA DATE (Batch, Stock);
deliveryNotePrevLineID 'Номер строки в приходном документе' = DATA INTEGER (Batch, Stock);
lineItemQuantitySPT 'Единица измерения прослеживаемости' = DATA STRING[3] (Batch, Stock);
//lineItemPriceSPT 'Цена за единицу товара для прослеживаемости' = DATA NUMERIC(Batch, Stock);////цену не сохраняем а рассчитываем в момент расхода
//quantityDespatchedSPT 'Количество в единицах прослеживаемости' = DATA NUMERIC[12,5] (Batch, Stock);//кол-во не сохраняем а рассчитываем в момент расхода
itemCustomCode'Код ТНВЭД' = DATA STRING[10] (Batch, Stock);
itemCustomCodeOther 'Дополнительный таможенный код' = DATA STRING[4] (Batch, Stock);
