MODULE SkuLedgerCostStockDocument;

REQUIRE SkuLedgerCost, StockDocument;

NAMESPACE Stock;


FORM enterDays 'Укажите количество дней назад для пересчёта'
    OBJECTS i = INTEGER PANEL
    PROPERTIES VALUE(i)
;

recalulateCostLedgerAllSkus 'Пересчитать с/с в открытом периоде'() {
    DIALOG enterDays OBJECTS i = 14 INPUT DO {
        recalulateCostLedgerAllSkus (i);
    }
}

EXTEND FORM closingDocuments
    PROPERTIES () recalulateCostLedgerAllSkus DRAW s TOOLBAR
;