MODULE StockDocumentSkuLedger;

REQUIRE StockDocument, SkuLedger;

NAMESPACE Stock;

stockDocumentLedger = ABSTRACT StockDocumentLedger (SkuLedger) MATERIALIZED;

numberDocument 'Номер документа' (SkuLedger ledger) = number(stockDocumentLedger(ledger)) CHARWIDTH 8;
seriesDocument 'Серия документа' (SkuLedger ledger) = series(stockDocumentLedger(ledger)) CHARWIDTH 3 NOFLEX;
seriesNumberDocument 'Серия/номер документа' (SkuLedger ledger) = seriesNumber(stockDocumentLedger(ledger)) CHARWIDTH 10;

legalEntityDocument (SkuLedger ledger) = legalEntity(stockDocumentLedger(ledger)); 
nameLegalEntityDocument 'Контрагент' (SkuLedger ledger) = name(legalEntityDocument(ledger));
overNameLegalEntityDocument 'Контрагент' (SkuLedger ledger) = OVERRIDE nameLegalEntityDocument(ledger), 'Не задан';

legalEntityStockDocument (SkuLedger ledger) = legalEntityStock(stockDocumentLedger(ledger));
nameLegalEntityStockDocument 'Склад контрагента' (SkuLedger ledger) = name(legalEntityStockDocument(ledger));
idLegalEntityStockDocument 'Склад контрагента' (SkuLedger ledger) = id(legalEntityStockDocument(ledger));
overNameLegalEntityStockDocument 'Склад контрагента' (SkuLedger ledger) = OVERRIDE nameLegalEntityStockDocument(ledger), 'Не задан';

operationDocument (SkuLedger ledger) = operation(stockDocumentLedger(ledger));
nameOperationDocument 'Операция' (SkuLedger ledger) = name(operationDocument (ledger));
overNameOperationDocument 'Операция' (SkuLedger ledger) = OVERRIDE nameOperationDocument(ledger),  'Не задана';

EXTEND FORM costSkuLedger
    PROPERTIES(bil) READONLY AFTER dateTime(bil) numberDocument, seriesDocument
    PROPERTIES(bil) READONLY BEFORE quantity(bil) nameLegalEntityDocument, nameLegalEntityStockDocument
;

EXTEND FORM costSkuBatchLedger
    PROPERTIES(bil) READONLY AFTER dateTime(bil) numberDocument, seriesDocument
    PROPERTIES(bil) READONLY BEFORE quantity(bil) nameLegalEntityDocument, nameLegalEntityStockDocument
;

EXTEND FORM currentBalanceSkuStock
    PROPERTIES(bil) READONLY AFTER dateTime(bil) numberDocument, seriesDocument
    PROPERTIES(bil) READONLY BEFORE signedQuantity(bil) nameLegalEntityDocument, nameLegalEntityStockDocument
;

EXTEND FORM balanceSkuStock
    PROPERTIES(bil) READONLY AFTER dateTime(bil) numberDocument, seriesDocument
    PROPERTIES(bil) READONLY BEFORE signedQuantity(bil) nameLegalEntityDocument, nameLegalEntityStockDocument
;

EXTEND FORM currentBalanceBatchStock
    PROPERTIES(bil) READONLY AFTER dateTime(bil) numberDocument, seriesDocument 
    PROPERTIES(bil) READONLY BEFORE signedQuantity(bil) nameLegalEntityDocument, nameLegalEntityStockDocument
;

EXTEND FORM balanceBatchStock
    PROPERTIES(bil) READONLY AFTER dateTime(bil) numberDocument, seriesDocument
    PROPERTIES(bil) READONLY BEFORE signedQuantity(bil) nameLegalEntityDocument, nameLegalEntityStockDocument
;

EXTEND FORM skuLedger
    PROPERTIES(s) READONLY AFTER dateTime(s) numberDocument, seriesDocument
    PROPERTIES(s) READONLY BEFORE signedQuantity(s) overNameOperationDocument, overNameLegalEntityDocument, overNameLegalEntityStockDocument
;

// --------- Суммы по документу ------------//

showSkuLedgerStockDocument 'Показывать суммы по регистру в товарном отчете' = DATA BOOLEAN ();
EXTEND FORM options
    PROPERTIES() showSkuLedgerStockDocument
;

DESIGN options {
    stock1 {
        MOVE PROPERTY(showSkuLedgerStockDocument());
    }
}

sumSkuLedger 'Сумма по регистру' = GROUP SUM signedSum(SkuLedger l) BY stockDocumentLedger(l) CHARWIDTH 12;

EXTEND FORM sumStockDocumentLedger
    PROPERTIES(il) sumSkuLedger SHOWIF showSkuLedgerStockDocument()
    FILTERGROUP incorrectIncSum FILTER 'Неправильная сумма по регистру' NOT sum(il) == sumSkuLedger(il) 'F7'

    PROPERTIES(ol) sumSkuLedger SHOWIF showSkuLedgerStockDocument()
    FILTERGROUP incorrectOutSum FILTER 'Неправильная сумма по регистру' NOT sum(ol) == -sumSkuLedger(ol) 'F7'
;