MODULE ErpDefault;

REQUIRE Scheduler, Service, SystemEvents, Backup, EvalScript, Excel, SQLUtils, Chat,
        LegalEntity, 
        Item, ItemLog, ItemSize, PurchasePackItem, SalePackItem, SkuList,
        EmployeeLegalEntity,
        TaxBy,
        FiscalEpson, FiscalVMK, TerminalYarus, ScannerDaemon,
        LegalEntityBy,
        PurchaseSaleOrder, PurchaseOrderDaysChange, // OR
        CustomerOrder, PreOrder, 
        PurchaseDemandOrder, // PO
        PurchaseOrderSeparation, PurchaseDemandSeparation, // PO
        PurchaseDemandOrderPromotion, // PO, PL
        PurchaseScheduleOrder, PurchaseScheduleOrderPriceList, PurchaseScheduleDemand, PurchaseScheduleOrderContract, PurchaseScheduleOrderSeparation, // SO
        RangeLevel, RangeLevelShelf, SalePlace, RangeLog, RangeLevelLog, RangePurchaseOrderStore, RangeBalance, RangePurchaseDemandOrder, RangeCompare, // AM
        PurchaseAutoOrder, PurchaseDemandAuto, // AM
        RangeRetailPriceDashboard, RangeLevelPriceListDashboard, // AM
        PurchaseOrderPriceList, PurchaseOrderPriceListGroup, // OR, PL
        PurchaseOrderReplace, SaleOrderReplace, // OR
        PurchaseOrderStatus, PurchaseScheduleOrderStatus, // OR
        PurchaseOrderPromotion, // OR, PL
        PurchaseInvoice, PurchaseReturnInvoice, PurchaseSaleReturnInvoice, PurchaseInvoiceExtraCharge, PurchaseShipmentReturn,
        PurchaseLedgerItem,
        SaleLedgerItem,
        SaleLedgerRetailCRM, // POS, CRM
        PurchaseOrderInvoiceDashboard, SaleReturnOrderInvoiceDashboard, PurchaseOrderInvoiceDashboardExtra, // OR
        ConsignmentDashboard, ConsignmentDashboardBy, // OR
        PurchaseSaleOrderDashboard, // OR
        PurchaseOrderAgreement, PurchaseInvoiceAgreement, PurchaseOrderInvoiceAgreement, // OR
        WarehouseConsignmentBy, PurchaseReturnInvoiceConsignmentBy, SaleInvoiceConsignmentBy,
        StoreConsignmentBy, PurchaseSaleReturnConsignmentRetailBy, SalePurchaseConsignmentRetailBy, // RT
        SalePurchaseCompliance, SalePurchaseDeclaration,
        PurchaseSaleReturnInvoiceShipment, SalePurchaseInvoiceShipment,
        PurchaseShipmentAccountLedger,
        PurchaseCreditNoteContract, PurchaseSaleCreditNote, SaleCreditNoteContract, SalePurchaseCreditNote, 
        PurchaseReturnCreditNote, SaleReturnCreditNote,        
        TerminalHandler,
        TerminalItem, LabelTerminal, PurchaseInvoiceTerminal, PurchaseReturnInvoiceTerminal, SaleOrderTerminal, SaleInvoiceTerminal,
        PurchaseOrderTerminalOrder, // OR
        WarehouseSkuLedger, StockMovementItem,
        WriteOffWarehouse, WriteOffBy, 
        WriteOffStore, // RT
        StockAdjustment,
        Disparity, DisparityLabel, DisparityMachinery, 
        DisparityAccountLedger,
        PricingDisparity, RepricingDisparity, RepricingCommittee, // RT
        Inventory, InventoryBy, InventoryZone,
        NaturalLossBy, NaturalLossItem, PurchaseWriteOffBy, WriteOffPurchaseItem,
        StockDocumentBy, StockDocumentWarehouse, StockDocumentStore, AccountSumDashboard,
        ContainerMovement, ContainerMovementBy,
        MachineryPriceTransactionStockTax,
        PriceListCalcDocument, PriceListForm, PriceListItem, PriceListLedgerItem, PriceListPurchase, PriceListPurchaseInvoice, // PL
        PriceListDashboard, PriceListDashboardStore, PriceListSaleLedger, // PL
        PriceListContract, // PL
        PriceListBefore, // PL
        PriceListPromotion, PriceListPromotionForbid, // PL
        Promotion, // PL
        RetailPriceDashboard, RetailPriceDashboardCompetitor, // PL
        ZReportSkuLedgerStockDocument,
        PricingSalePurchaseShipment, PricingPurchaseReturn, PricingSalePurchaseSalePricing, PricingSalePurchaseShipment,
        PricingWriteOff, PricingZReport, ZReportProcessing,
        PricingPurchaseSupplierCalc, // RT, PL
        UpdatePriceDashboardLabel, UpdatePricePurchaseInvoice,
        PricingPurchaseInvoiceDashboard, // OR
        RepricingStore, RepricingPurchaseShipment,
        RepricingLabel,
        RepricingDashboard, // PL
        RepricingPurchaseInvoice,
        DiscountCardReceiptSkuLedger, DiscountCardReports, DiscountCardData, // CRM
        PriceListMachinery, PurchaseInvoiceMachinery, // Отключать, если POS
        RepricingMachinery, // Отключать, если POS
        MachineryOrderInvoiceDashboard, // OR // Отключать, если POS
        CashRegisterItem, // Отключать, если POS
        ScalesItem, // Отключать, если POS
        LabelItem, SalePurchaseLabel,
        LabelPromotion, // PL
        LabelPriceList, // PL 
        LabelOrderInvoiceDashboard, // OR
        LabelBy,
        MarketingContract, MarketingInvoice, MarketingWord, //MR
        POS, CashOperationPOS, POSSection, Board, // POS
        StoreSaleOrder, StoreSaleInvoice, StoreSaleReturnInvoice, SaleOrderRetailPrintBy,
        PurchaseReports, SaleReports, StockReports,
        PurchaseLedgerWeek, SaleLedgerWeek, SaleLedgerCustomerWeek,
        SaleTurnover, SupplierStockReports, StockGroupReports,
        ZReportReport, ZReportReportDiscountCard, ZReportReportGiftCard, 
        GiftCardReport, GiftCardSaleInvoice,
        POSGiftCard, // POS
        ReceiptReports,
        SaleStatisticsBy, SaleStatisticsItem, SaleStatisticsItemDescription,
        SaleStatisticsReportBy, SaleStatisticsStore,
        PurchaseSnapshot, SaleSnapshot, WriteOffSnapshot, ZReportSnapshot,
        PurchaseReturnInvoiceContract, SalePurchaseInvoiceContract, SaleInvoiceContract, PurchaseReturnInvoiceDiscount,
        PurchaseInvoicePayment, SaleInvoicePayment, BankPaymentLedger,
        PurchaseOrderPayment, SaleOrderPayment,
        Dimension, GeneralLedger,
        DimensionBy, GLAccountTypeBy,
        // Стандартные данные 
        ItemDefault, CountryDefaultBy, CurrencyDefaultBy, PriceListDefault, LabelDefault,
        PricingOperationDefaultBy, PurchaseOperationDefaultStore, SaleOperationDefaultStoreBy, RepricingOperationDefaultBy, 
        WriteOffOperationDefaultStoreBy, DisparityOperationStoreBy, InventoryOperationDefault, StockAdjustmentOperationDefault, PriceListOperationDefaultStore,
//      По умолчанию не включаем проводки
//        PurchaseInvoiceGeneralLedger, SaleInvoiceGeneralLedger, ZReportGeneralLedger, PricingGeneralLedger, RepricingGeneralLedger, SalePurchaseShipmentGeneralLedger,
        ProductionConsumptionBatch, ProductionOutputPurchaseInvoice, // MF
        ProductionConsumptionDefaultSkuLedger, // MF
        ProductionOutputAccountLedger, // MF
        ProductionOrderLabel, // MF
        ProductionOrderMachinery, // MF
        ProductionOrderConsignmentBy, CostCardOrderBy, // MF
        BOMTechnology, BOMOperation, BOMBy, // MF
        ManufacturingTransferDashboard, //MF
        PurchaseOrderRamp, PurchaseReturnOrderRamp, SaleOrderRamp, SaleReturnOrderRamp, // WMS, OR
        PurchaseScheduleOrderRamp, // WMS, SO
        BinOrderTerminalOrder, BinOrderDemand, BinTransferDashboard,//WMS
        ItemImport, LegalEntityImport, WarehouseImport, UOMImport, ItemGroupImport, BrandImport, LegalEntityByImport, AccountImport, StoreTypeImport, StoreImport, 
        ImportEuroopt, ImportMila,
        ABCAnalysisSnapShot,
        SaleOrderPayment, PurchaseOrderPayment, PurchaseDemandItem,
        API, StoreAPI, ZReportAPI, SkuLedgerAPI, TerminalAPI, SkuAPI, ItemInfoAPI, ItemSizeAPI, LegalEntityAPI, CompetitorAPI, TurnoverAPI, //API
        TurnoverBI, ReceiptBI,// BI
        TripConsignmentDashboardBy, ImportInit; //TR
        //PricingMachineryTask, PricingSumLabelTask, RepricingMachineryTask, PurchaseScheduleOrderTask; //BPM