MODULE ErpDefault;

REQUIRE Scheduler, Service, SystemEvents, Backup, EvalScript, Excel, SQLUtils,
        LegalEntity, 
        Item, ItemSize, PurchasePackItem, SalePackItem, 
        EmployeeLegalEntity,
        TaxBy,
        FiscalEpson, TerminalYarus,
        LegalEntityBy,
        PurchaseSaleOrder, // OR
        PurchaseDemandOrder, // PO
        PurchaseDemandOrderPromotion, // PO, PL
        PurchaseScheduleOrder, PurchaseScheduleOrderPriceList, PurchaseScheduleDemand, PurchaseScheduleOrderContract, // SO
        RangeLevel, RangeLog, RangePurchaseOrderStore, RangeBalance, RangePurchaseDemandOrder, RangeCompare, // AM
        PurchaseAutoOrder, PurchaseAutoOrderPriceList, PurchaseDemandAuto, // AM
        RangeRetailPriceDashboard, RangeLevelPriceListDashboard, // AM
        PurchaseOrderPriceList, // OR, PL
        PurchaseOrderReplace, SaleOrderReplace, // OR
        PurchaseOrderStatus, PurchaseScheduleOrderStatus, // OR
        PurchaseOrderPromotion, // OR, PL
        PurchaseInvoice, PurchaseReturnInvoice, PurchaseSaleReturnInvoice, PurchaseInvoiceExtraCharge,
        PurchaseLedgerItem,
        SaleLedgerItem,
        SaleLedgerRetailCRM, // POS, CRM
        PurchaseOrderInvoiceDashboard, SaleReturnOrderInvoiceDashboard, PurchaseOrderInvoiceDashboardExtra, // OR
        PurchaseOrderAgreement, PurchaseInvoiceAgreement, PurchaseOrderInvoiceAgreement, // OR
        WarehouseConsignmentBy, PurchaseReturnInvoiceConsignmentBy, SaleInvoiceConsignmentBy,
        StoreConsignmentBy, PurchaseSaleReturnConsignmentRetailBy, SalePurchaseConsignmentRetailBy, // RT
        SalePurchaseCompliance, SalePurchaseDeclaration,
        PurchaseSaleReturnInvoiceShipment, SalePurchaseInvoiceShipment,
        PurchaseShipmentAccountLedger,
        PurchaseCreditNoteContract,
        TerminalHandler,
        PurchaseOrderTerminalOrder, // OR
        WarehouseSkuLedger, StockMovementItem,
        WriteOffWarehouse, WriteOffBy, 
        WriteOffStore, // RT
        StockAdjustment,
        Disparity, DisparityLabel, DisparityMachinery, 
        DisparityAccountLedger,
        PricingDisparity, RepricingDisparity, RepricingCommittee, // RT
        Inventory, InventoryBy,
        NaturalLossBy, NaturalLossItem, PurchaseWriteOffBy, WriteOffPurchaseItem,
        StockDocumentBy, StockDocumentWarehouse, StockDocumentStore,
        ContainerMovement, ContainerMovementBy,
        PriceListCalc, PriceListForm, PriceListItem, PriceListLedgerItem, PriceListPurchase, PriceListPurchaseInvoice, PriceListCompare, // PL
        PriceListDashboard, PriceListDashboardStore, PriceListSaleLedger, // PL
        PriceListContract, // PL
        PriceListBefore, // PL
        Promotion, // PL
        ZReportSkuLedgerStockDocument,
        PricingSalePurchaseShipment, PricingPurchaseReturn, PricingSalePurchaseSalePricing, PricingSalePurchaseShipment,
        PricingWriteOff, PricingZReport,
        UpdatePriceDashboardLabel, UpdatePricePurchaseInvoice,
        PricingPurchaseInvoiceDashboard, // OR
        RepricingStore, RepricingPurchaseShipment,
        RepricingLabel,
        RepricingDashboard, // PL
        RepricingPurchaseInvoice,
        DiscountCardReceiptSkuLedger, DiscountCardReports, // CRM
        PriceListMachinery, PurchaseInvoiceMachinery, // Отключать, если POS
        RepricingMachinery, // Отключать, если POS
        MachineryOrderInvoiceDashboard, // OR // Отключать, если POS
        CashRegisterItem, // Отключать, если POS
        ScalesItem, // Отключать, если POS
        LabelItem, SalePurchaseLabel,
        LabelPromotion, // PL
        LabelPriceList, // PL 
        LabelOrderInvoiceDashboard, // OR
        LabelBy,
        POS, CashOperationPOS, POSSection, Board, // POS
        StoreSaleInvoice, StoreSaleReturnInvoice, SaleOrderRetailPrintBy,
        PurchaseReports, SaleReports, StockReports,
        PurchaseLedgerWeek, SaleLedgerWeek, SaleLedgerCustomerWeek,
        SaleTurnover, SupplierStockReports, StockGroupReports,
        ZReportReport, ZReportReportDiscountCard, ZReportReportGiftCard,
        ReceiptReports,
        SaleStatisticsBy, SaleStatisticsItem, SaleStatisticsItemDescription,
        SaleStatisticsReportBy, SaleStatisticsStore,
        PurchaseSnapshot, SaleSnapshot, WriteOffSnapshot, ZReportSnapshot,
        PurchaseReturnInvoiceContract, SalePurchaseInvoiceContract, SaleInvoiceContract,
        PurchaseInvoicePayment, SaleInvoicePayment, BankPaymentLedger,
        Dimension, GeneralLedger,
        DimensionBy, GLAccountTypeBy,
        // Стандартные данные 
        ItemDefault, CountryDefaultBy, CurrencyDefaultBy, PriceListDefault, LabelDefault,
        PricingOperationDefaultBy, PurchaseOperationDefaultStore, SaleOperationDefaultStoreBy, RepricingOperationDefaultBy, 
        WriteOffOperationDefaultStoreBy, DisparityOperationStoreBy, InventoryOperationDefault, StockAdjustmentOperationDefault, PriceListOperationDefaultStore,
//      По умолчанию не включаем проводки
//        PurchaseInvoiceGeneralLedger, SaleInvoiceGeneralLedger, ZReportGeneralLedger, PricingGeneralLedger, RepricingGeneralLedger, SalePurchaseShipmentGeneralLedger,
        ProductionConsumptionBatch, ProductionOutputPurchaseInvoice, // MF
        ProductionOutputAccountLedger, // MF
        ProductionOrderLabel, // MF
        ProductionOrderMachinery, // MF
        ProductionOrderConsignmentBy, CostCardOrderBy, // MF
        BOMTechnology, BOMOperation, // MF
        PurchaseOrderRamp, PurchaseReturnOrderRamp, SaleOrderRamp, SaleReturnOrderRamp, // WMS, OR
        PurchaseScheduleOrderRamp, // WMS, SO
        ItemImport, LegalEntityImport, WarehouseImport, UOMImport, ItemGroupImport, BrandImport, LegalEntityByImport, AccountImport, StoreTypeImport, StoreImport, ImportEuroopt,
        SaleRebate, // ретро-бонусы
        ABCAnalysisSnapShot,
        TurnoverBI, ReceiptBI,// BI
        PricingMachineryTask, PricingSumLabelTask, RepricingMachineryTask, PurchaseScheduleOrderTask, AccountSumDashboard; //BPM