MODULE ExportDeclaration;

REQUIRE System,
        Compliance,
        Item,
        PurchaseDeclarationDetail,
        PurchaseDeclarationDetailBy,
        PurchaseDeclarationDetailCompliance;

exportXml 'Экспортировать' = ACTION CUSTOM 'lsfusion.erp.region.by.certificate.declaration.ExportDeclarationActionProperty' (Declaration);

import 'Импорт из Декларанта' = ACTION CUSTOM 'lsfusion.erp.region.by.certificate.declaration.ImportDeclarationDBFActionProperty' (Declaration);
exportDBFAction 'Экспорт декларанта' = ACTION CUSTOM 'lsfusion.erp.region.by.certificate.declaration.ExportDeclarationDBFActionProperty' (Declaration);

exportDeclarant 'Экспорт в Декларант' (Declaration declaration) = ACTION {
    exportDBFAction(declaration);
    fillExported(declaration);
    apply();
}

importDeclarationAdjustment 'Импорт KTC' = ACTION CUSTOM 'lsfusion.erp.region.by.certificate.declaration.ImportDeclarationAdjustmentDBFActionProperty' (Declaration);

EXTEND FORM declaration
    PROPERTIES (d) import TODRAW dd FORCE PANEL TOOLBAR, importDeclarationAdjustment TODRAW a FORCE PANEL TOOLBAR
    PROPERTIES (d) exportDeclarant TODRAW dd FORCE PANEL TOOLBAR
;