MODULE EnterpriseDataReceive;

REQUIRE EnterpriseDataSend;

NAMESPACE EnterpriseData;

nonResidentNumber = DATA LOCAL ISTRING(INTEGER);

// partner
EXTEND FORM receiveMessage
    PROPERTIES (partner) IN keyProperties
            fullNamePartner EXTID 'НаименованиеПолное',
            innPartner EXTID 'ИНН',
            kppPartner EXTID 'КПП',
            typePartner EXTID 'ЮридическоеФизическоеЛицо'
    PROPERTIES(partner) nonResidentNumber EXTID 'РегистрационныйНомерНерезидента'
;

// item
idItem = DATA LOCAL ISTRING (INTEGER);
typeItem = DATA LOCAL ISTRING (INTEGER);

EXTEND FORM receiveMessage
    PROPERTIES (item) IN keyProperties
        idItem EXTID 'КодВПрограмме', articleItem EXTID 'Артикул'
    PROPERTIES (item) typeItem EXTID 'ТипНоменклатуры'
;