MODULE EZAuthentication;

//EQUIRE CryptoPro;

NAMESPACE EZ;

urlEZ 'Url к Web-сервису ГИС "Электронный знак"' = DATA STRING ();

usernameEZ 'Пользователь' = DATA STRING();
passwordEZ 'Пароль для API' = DATA STRING() ECHO;
hostEZ 'Host' = DATA STRING ();
token 'Токен' = DATA STRING ();


EXTEND FORM integrationData
    PROPERTIES() urlEZ, usernameEZ, passwordEZ
    PROPERTIES() hostEZ
    PROPERTIES() READONLY EZtoken = token
;

DESIGN integrationData {
    pane {
        NEW EZ {
            caption = 'ЭЗ';
            MOVE PROPERTY(urlEZ());
            MOVE PROPERTY(usernameEZ());
            MOVE PROPERTY(passwordEZ());
            MOVE PROPERTY(hostEZ());
            MOVE PROPERTY(EZtoken);
        }
    }
}

