MODULE Pharm;

GROUP itemPharmacy 'Фармакологические свойства';

DESIGN options {
    pane {
        NEW pharmacy {   
            caption = 'Фармация';
        }
    }
}

META defineItemPharmDesign(object)
    DESIGN item {
        itemPrimaryColumn1 {
            MOVE GROUP(itemPharmacy, i) {
                lines = 2;
            }
        }
    }

    DESIGN itemGroup {
        BOX {
            attributes {
                MOVE GROUP(itemPharmacy, g) {
                    lines = 5;
                };
            }
        }
    }    
END    