MODULE EGAISPurchaseShipmentGestori;

REQUIRE EGAISPurchaseShipment, EGAISWayBillGestory;

NAMESPACE EGAISPurchase;

@defineOriginalLastDocumentWayBillAttributes(Purchase, Shipment);
@defineOriginalLastDocumentWayBillAttributes(Purchase, Shipment, customerStock);

@defineOriginalLastPositionDocumentWayBillAttributes(Purchase, shipment, ShipmentDetail);

canCreateLot (UserInvoice i) =
    GROUP MAX TRUE IF quantity(UserInvoiceDetail d, wayBillPosition(WayBillMark m)) AND wayBill(wayBillPosition(m)) = wayBill(i);

overCreateDetail(UserInvoice i) +{
    IF canCreateLot(i) THEN
        createLots(i);
}

hideCreateLots(UserInvoice i) += (NOT canCreateLot (i) AND i IS UserInvoice)
    OR (TRUE IF NOT disableEGAISDocumentConstraints() AND activeWayBillAct(wayBill(i)));