MODULE EGAISWriteOffGestori;

REQUIRE EGAISWriteOff, EGAISActWriteOffGestori, SkuLedgerLotGestori, EGAISDocGestori, WriteOffTerminal;

NAMESPACE EGAIS;

minPostedActWriteOff (UserWriteOff w) = GROUP MIN ActWriteOff awo IF posted(actWriteOff(w)) AND actWriteOff(w) == awo;

editQuantity(UserWriteOffDetail d, F2Reg r) += posted(actWriteOff(writeOff(d))) AND r IS F2Reg;
hideFillQuantity(UserWriteOffDetail d, F2Reg r) += posted(actWriteOff(writeOff(d))) AND r IS F2Reg;
hideFillQuantity(UserWriteOff w) += posted(actWriteOff(w));
hideShowLots (UserWriteOffDetail w) += posted(actWriteOff(writeOff(w)));

overCheckQuantity(UserWriteOffDetail d, F2Reg r, NUMERIC[16,5] n) += 
    IF NOT currentBalance(r) >= n AND r IS F2Reg THEN 'Количество (ЕГАИС) не может быть больше текущего остатка';

skipDataQuantity(ActWriteOffPosition p) += TRUE IF quantity(p);

CONSTRAINT SETCHANGED(quantity(UserWriteOffDetail d, Lot l)) AND availableQuantity(l, stock(d)) < 0
    MESSAGE 'Неверное количество доступного остатка марок';

skipShowEdit(WriteOff w) += forbidEditSendDocument() AND activeActWriteOff(w);
skipShowDelete(WriteOff w) += forbidEditSendDocument() AND activeActWriteOff(w);

@defineOriginalLastDocumentActWriteOffAttributes(WriteOff);
@defineOriginalLastDocumentWayBillAttributes(WriteOff, stock);

editQuantity(UserWriteOffDetail d, F2Reg r) += NOT hideFillQuantity(userWriteOff(d));
hideFillQuantity(UserWriteOffDetail d, F2Reg r) += hideFillQuantity(userWriteOff(d));

@defineSimpleDocumentEGAISConstraint(activeActWriteOff, , writeOff, 'Списание');

DESIGN userWriteOff {
    PROPERTY(addDetailDialogTerminalUserWriteOffDetail(w)) { showIf = disableEGAISDocumentConstraints() OR NOT activeActWriteOff(w); }
}