MODULE InventoryBy;

REQUIRE Inventory;

NAMESPACE Inventory;

//------------------------------------------ Печатные формы -------------------------------------------------//

//------------------------------------ Опись ------------------------------------------//

FORM printListInventoryBy 'Опись'

    OBJECTS         li=ListInventory FIXED PANEL
    PROPERTIES (li) dateListInventory, nameLegalEntityStockListInventory, nameStockListInventory,
                    nameInventoryListInventory, nameListInventory, noteListInventory, committeeListInventory,
                    nameCommitteeListInventory, nameChairmanCommitteeListInventory, namePositionChairmanListInventory, nameEmployeeListInventory,
                    countPageInventoryListInventory, countPageInventoryDetailListInventory, quantityPageInventoryDetailListInventory,
                    sumPageInventoryDetailListInventory, countIndexListInventory, countIndexBatchListInventory, isBatchListInventory, isSkuListInventory

    OBJECTS t=DATETIME FIXED PANEL
    PROPERTIES(t) OBJVALUE

    OBJECTS         i=Sku
    PROPERTIES (li,i) indexListInventorySku
    PROPERTIES (i)    idBarcodeSku, nameSku
    PROPERTIES (li,i) quantityPageInventoryDetailListInventorySku, pricePageInventoryDetailListInventorySku, sumPageInventoryDetailListInventorySku
    FILTERS           quantityPageInventoryDetailListInventorySku(li,i) > 0
    ORDER BY indexListInventorySku(li,i)

    OBJECTS         b=Batch
    PROPERTIES (li,b) indexListInventoryBatch
    PROPERTIES (b)    idBarcodeSkuBatch, nameSkuBatch, descriptionBatch, nameBatch
    PROPERTIES (li,b) quantityPageInventoryDetailListInventoryBatch, pricePageInventoryDetailListInventoryBatch, sumPageInventoryDetailListInventoryBatch
    FILTERS           quantityPageInventoryDetailListInventoryBatch(li,b) > 0
    ORDER BY indexListInventoryBatch(li,b)

    OBJECTS e=Employee
    PROPERTIES(e) READONLY   nameContact, namePositionEmployee
    FILTERS        inListInventoryEmployee(li, e)
;

DESIGN printListInventoryBy FROM DEFAULT {
    main {
        preferredSize = (1024, 768);
        type = CONTAINERV;
        ADD li.box {
            type = CONTAINERH;
            NEW row {
                type = CONTAINERV;
                ADD li.documentHeader {
                    type = CONTAINERH;
                    ADD PROPERTY(nameInventoryListInventory(li));
                    ADD PROPERTY(nameListInventory(li));
                }
                ADD li.inventoryCommittee {
                    type = CONTAINERH;
                }
                ADD li.documentPrm;


            }
            ADD li.documentSum {
                type = CONTAINERV;
                PROPERTY(countPageInventoryListInventory(li)) {
                    caption = 'Количество страниц';
                }

            }
        }

        ADD i.box;
        ADD b.box;
        ADD e.box;
        ADD functions.box;
    }
}

printListInventoryBy 'Опись' (listInventory) =
    ACTION FORM printListInventoryBy OBJECTS li=listInventory, t=currentDateTime() PRINT
    IMAGE 'print.png' IN print;

//------------------------------------ Сличительная ведомость ------------------------------------------//

FORM printCollationSheetBy 'Сличительная ведомость'

    OBJECTS          cs=CollationSheet FIXED PANEL
    PROPERTIES (cs)  SELECTOR nameCollationSheet, nameLegalEntityStockCollationSheet, nameCommitteeCollationSheet,
                              nameChairmanCommitteeCollationSheet, namePositionChairmanCollationSheet, nameEmployeeCollationSheet,
                              nameTypeOfAdditionCollationSheet, nameStockCollationSheet, dateCollationSheet,
                              quantityPageInventoryDetailCollationSheet, quantityBalanceCollationSheet, quantityShortageCollationSheet,
                              sumPageInventoryDetailCollationSheet, sumBalanceCollationSheet, sumShortageCollationSheet,
                              countListInventoryCollationSheet, countPageInventoryCollationSheet, prevDateCollationSheet,
                              sumItemPageInventoryDetailCollationSheet, sumContainerPageInventoryDetailCollationSheet,
                              sumItemBalanceCollationSheet, sumContainerBalanceCollationSheet,
                              sumItemShortageCollationSheet, sumContainerShortageCollationSheet, isBatchCollationSheet, isSkuCollationSheet

    OBJECTS          i=Sku
    PROPERTIES(i)     SELECTOR nameSku, idBarcodeSku
    PROPERTIES(cs, i) SELECTOR quantityPageInventoryDetailCollationSheetSku, quantityBalanceCollationSheetSku, quantityShortageCollationSheetSku
    PROPERTIES(cs, i)          pricePageInventoryDetailCollationSheetSku, priceBalanceCollationSheetSku
    PROPERTIES(cs, i) SELECTOR sumPageInventoryDetailCollationSheetSku, sumBalanceCollationSheetSku, sumShortageCollationSheetSku
    FILTERS                    includeCollationSheetSku(cs, i)
    ORDER BY nameSku(i)

    OBJECTS         b=Batch
    PROPERTIES(b)    SELECTOR nameSkuBatch, idBarcodeSkuBatch, descriptionBatch, nameBatch
    PROPERTIES(cs,b) SELECTOR quantityPageInventoryDetailCollationSheetBatch, quantityBalanceCollationSheetBatch, quantityShortageCollationSheetBatch
    PROPERTIES(cs,b) SELECTOR pricePageInventoryDetailCollationSheetBatch, priceBalanceCollationSheetBatch
    PROPERTIES(cs,b) READONLY sumPageInventoryDetailCollationSheetBatch, sumBalanceCollationSheetBatch, sumShortageCollationSheetBatch
    FILTERS                   includeCollationSheetBatch(cs,b),
                              quantityPageInventoryDetailCollationSheetBatch(cs,b) OR quantityBalanceCollationSheetBatch(cs,b)
    ORDER BY nameSkuBatch(b)
;

printCollationSheetBy 'Сличительная ведомость' (collationSheet) =
    ACTION FORM printCollationSheetBy OBJECTS cs = collationSheet PRINT  IMAGE 'print.png' IN print;

//------------------------------------ Сличительная ведомость (итоги) ------------------------------------------//

FORM printTotalCollationSheetBy 'Сличительная ведомость (итоги)'

    OBJECTS          cs=CollationSheet FIXED PANEL

    PROPERTIES (cs)  SELECTOR nameCollationSheet, nameLegalEntityStockCollationSheet, nameCommitteeCollationSheet,
                              nameChairmanCommitteeCollationSheet, namePositionChairmanCollationSheet, nameEmployeeCollationSheet,
                              timeFromCollationSheet, timeToCollationSheet, dateCollationSheet, nameHeadManCollationSheet
    PROPERTIES (cs)  SELECTOR nameTypeOfAdditionCollationSheet, nameStockCollationSheet,
                              quantityPageInventoryDetailCollationSheet, quantityBalanceCollationSheet, quantityShortageCollationSheet,
                              sumPageInventoryDetailCollationSheet, sumBalanceCollationSheet, sumShortageCollationSheet,
                              countListInventoryCollationSheet, countPageInventoryCollationSheet, prevDateCollationSheet
    PROPERTIES (cs)  SELECTOR sumItemBalanceCollationSheet, sumContainerBalanceCollationSheet, sumItemPageInventoryDetailCollationSheet,
                              sumContainerPageInventoryDetailCollationSheet, sumItemShortageCollationSheet, sumContainerShortageCollationSheet
;

printTotalCollationSheetBy 'Сличительная ведомость (итоги)' (collationSheet) =
    ACTION FORM printTotalCollationSheetBy OBJECTS cs = collationSheet PRINT  IMAGE 'print.png' IN print;


EXTEND FORM inventories

    PROPERTIES(li) printListInventoryBy
    PROPERTIES(cs) printTotalCollationSheetBy, printCollationSheetBy
;