MODULE PurchaseInvoiceWholesalePriceListStock;

REQUIRE PurchaseInvoiceWholesalePrice, PurchaseInvoicePriceListStock;

NAMESPACE Purchase;

// Создаем вид цен по всем складам компании
EXTEND CLASS SystemLedgerPriceListType { purchaseWholesaleInvoicePriceListType 'Оптовая (последняя по ценовой группе)' }
batchLedgerPriceListTypeStock (type, stock) += WHEN type == SystemLedgerPriceListType.purchaseWholesaleInvoicePriceListType AND isCompanyStock(stock)
                                               THEN priceBatchLedgerStock(stock);
inPriceListLedgerSystemLedgerPriceListType (ledger, type) += WHEN wholesalePriceInvoiceDetail(invoiceDetailInvoicePriceListLedger(ledger)) AND type == SystemLedgerPriceListType.purchaseWholesaleInvoicePriceListType THEN TRUE;
pricePriceListLedgerSystemLedgerPriceListType (ledger, type) += WHEN wholesalePriceInvoiceDetail(invoiceDetailInvoicePriceListLedger(ledger)) AND type == SystemLedgerPriceListType.purchaseWholesaleInvoicePriceListType THEN wholesalePriceInvoiceDetail(invoiceDetailInvoicePriceListLedger(ledger));
