MODULE PurchaseReturnInvoiceContract;

REQUIRE PurchaseReturnInvoice, InvoiceContract;

NAMESPACE PurchaseReturn;

@defineInvoicePaymentCondition(' (закупка-возврат)', Invoice);

// ------------------- Проведение по регистру задолженностей ----------------------- //

@implementContractLedger(, invoice, contractSku);
sumContractLedger(contractLedger) += -invoiceSumInvoiceDetailInvoice(contractLedger);

@implementContractLedger(a, invoice, contractSku);
sumContractALedger(contractALedger) += -invoiceSumInvoiceDetailInvoice(contractALedger);

@implementInOutContractLedgerPrefix(out, invoice, contractSku);
sumOutContractLedger(outContractLedger) += invoiceSumInvoiceDetailInvoice(outContractLedger);