MODULE PurchaseInvoiceMachinery;

REQUIRE PurchaseInvoice, MachineryPriceTransaction;

NAMESPACE Purchase;

// ------------------------------------- Загрузка в оборудование ------------------------------ //

@Machinery.implementPriceTransactionDocument(Invoice);
@defineDocumentMachineryPriceTransaction(invoice, sku, customerStock);
@extendFormDocumentMachineryPriceTransaction(invoices, i, invoice, isCommission, machineryContainer);

