MODULE LotInitBy;

REQUIRE LotInit;

NAMESPACE Lot;

DESIGN lotInit 'Маркировка'{
    caption = 'Маркировка';
}

DESIGN lotInits 'Маркировка'{
    caption = 'Маркировка';
    
    BOX(i) { caption = 'Маркировка'; } 
}

NAVIGATOR {
    lotNavigator {
        lotInits 'Маркировка';
    }
}

EXTEND FORM lotInit
    OBJECTS l = Lot
    PROPERTIES(l) READONLY id
    FILTERS quantity(d, l);
;

DESIGN lotInit {
    documentBox {
        caption = 'Заказ';
        NEW tabbedPane {
            type = TABBED;
            fill = 1;
            NEW spec {
                fill = 1;
                caption = 'Спецификация';
                MOVE BOX(d) { caption = 'Товары'; }
                MOVE BOX(l) { caption = 'Марки'; }
            }
        }        
    }
}
