MODULE EmployeeManager;

REQUIRE Employee;

NAMESPACE Employee;

managerEmployee = DATA Employee (Employee);
nameManagerEmployee 'Менеджер' (e) = shortNameContact(managerEmployee(e));

overManagerEmployee (employee) =  OVERRIDE employee AS Employee, managerEmployee(employee) PERSISTENT;

currentManager = overManagerEmployee(currentUser());

EXTEND FORM employee
    PROPERTIES (e) nameManagerEmployee
;

DESIGN employee {
    pane { 
        NEW manager{
            caption = 'Менеджмент';
            MOVE PROPERTY(nameManagerEmployee(e)); 
            NEW managerTabContainer {
                type = TABBED;
                fill = 1;
            }
        }
    } 
}