MODULE VetisPurchaseInvoice;

REQUIRE VetisDocument, VetisStock, VetisLegalEntity, PurchaseInvoice, VetisItem;

PRIORITY Purchase;

NAMESPACE VetisPurchase;

@defineDocumentVetDocument(userInvoice, supplier, customer, shipmentQuantity, i, specificationBox);

// invoice detail
volume 'Объем (ВСД)' = ABSTRACT NUMERIC[16,5] (InvoiceDetail, VetDocument);
volume(UserInvoiceDetail d, VetDocument s) += volume(d, s);
