MODULE VetisSaleShipment;

REQUIRE VetisOutgoingConsignment, VetisLegalEntity, VetisSaleInvoice, 
        SaleShipment, TripSaleShipment,
        VetisPrepareOutgoingConsignment, VetisWithdrawVetDocument;

PRIORITY Sale;

NAMESPACE VetisSale;

@defineDocumentStockEntry(userShipment, supplierStock, quantity, s, specificationBox);

// shipment detail
volume 'Объем (ВСД)' = ABSTRACT NUMERIC[16,5] (ShipmentDetail, StockEntry);

// invoice detail
volume(UserShipmentDetail d, StockEntry s) += volume(d, s);
volume(InvoiceShipmentDetail d, StockEntry s) += volume(invoiceDetail(d), s);

// consignment
@defineDocumentOutgoingConsignment(shipment, supplier, customer, ' (продажа)');

// shipment
volume (ShipmentDetail d, VetDocument vd) = GROUP SUM volume(d, StockEntry s) IF vetDocument(outgoingConsignment(d, s)) = vd;
@defineDocumentOutgoingProcess(shipment, s);

@defineDocumentOutgoingWithdraw(shipment);

// invoice
outgoingConsignment (InvoiceDetail vd, StockEntry se) = outgoingConsignment(invoiceShipmentDetail(vd), se);
@defineDocumentOutgoingProcess(invoice, i);

@defineDocumentOutgoingWithdraw(invoice);