MODULE GiftCardUKM;

REQUIRE GiftCardItem;

NAMESPACE GiftCard;


connectionStringExportGiftCards 'Строка подключения' = DATA VARSTRING[255] ();
userExportGiftCards 'Пользователь' = DATA VARSTRING[255] ();
passwordExportGiftCards 'Пароль' = DATA VARSTRING[255] ();
checkUnderpayExportGiftCards 'check_underpay' = DATA INTEGER ();

inExportGiftCards 'Экспорт' = DATA LOCAL BOOLEAN (GiftCard);
exportedExportGiftCards 'Экспортирован' = DATA BOOLEAN (GiftCard);
exportedActive 'Экспортирован (активация)' = DATA BOOLEAN (GiftCard);
exportGiftCardsUKMCustom 'Экспорт в УКМ'  INTERNAL  'lsfusion.erp.region.by.ukm.ExportGiftCardsActionProperty'();

idDepartmentStore = ABSTRACT VARISTRING[10](GiftCard);
isSoldInvoice 'Активировать при выгрузке' = ABSTRACT BOOLEAN (GiftCard);
isDefect = ABSTRACT BOOLEAN (GiftCard);

exportGiftCards 'Экспорт в УКМ' ()  { 

    inExportGiftCards(GiftCard g) <- NULL WHERE inExportGiftCards(g) AND (exportedActive(g) OR isSold(g));

    exportGiftCardsUKMCustom();
};

EXTEND FORM giftCards
    PROPERTIES(g) BEFORE number(g) inExportGiftCards, exportedExportGiftCards, exportedActive READONLY 
    PROPERTIES() exportGiftCards BEFORE generateGiftCards() DRAW g TOOLBAR
;


EXTEND FORM integrationData 
    PROPERTIES() connectionStringExportGiftCards, userExportGiftCards, passwordExportGiftCards, checkUnderpayExportGiftCards
;
DESIGN integrationData {
    PROPERTY(checkUnderpayExportGiftCards()) {
        toolTip = '0 - не разрешено, 1 - разрешено, 2 - решение принимает кассир';
    }
}

DESIGN integrationData {
    pane {
        NEW exportGiftCards {
            caption = 'Экспорт сертификатов';
            MOVE PROPERTY(connectionStringExportGiftCards());
            MOVE PROPERTY(userExportGiftCards());
            MOVE PROPERTY(passwordExportGiftCards());
            MOVE PROPERTY(checkUnderpayExportGiftCards());
        }    
    }
}

