MODULE EGAISInDocGestori;

REQUIRE EGAISInDoc, EGAISOutDocGestori;

NAMESPACE EGAIS;

typeBaseDocumentOutDoc 'Тип документа-основания' (InDoc d) = typeBaseDocument(outDoc(d));
numberBaseDocumentOutDoc 'Номер документа-основания' (InDoc d) = numberBaseDocument(outDoc(d));
dateBaseDocumentOutDoc 'Дата документа-основания' (InDoc d) = dateBaseDocument(outDoc(d));

typeOriginalDocumentOutDoc 'Тип документа системы' (InDoc d) = typeOriginalDocument(outDoc(d));
numberOriginalDocumentOutDoc 'Номер документа системы' (InDoc d) = numberOriginalDocument(outDoc(d));
dateOriginalDocumentOutDoc 'Дата документа системы' (InDoc d) = dateOriginalDocument(outDoc(d));

EXTEND FORM inDocs
    PROPERTIES(d) READONLY AFTER idOutDoc(d) typeBaseDocumentOutDoc, numberBaseDocumentOutDoc, dateBaseDocumentOutDoc,
        typeOriginalDocumentOutDoc, numberOriginalDocumentOutDoc, dateOriginalDocumentOutDoc
    
    FILTERGROUP filterProcessed
        FILTER 'Необработанные' toProcess(d)
        FILTER 'Обработанные' processed(d)
    
    FILTERGROUP filterDocType
;

DESIGN inDocs {
    PROPERTY(idOutDoc(d)) { caption = 'Номер транспортного пакета исходящего документа'; }
}

META defineInDocsFilterDocType (type, caption)
    EXTEND FORM inDocs
        EXTEND FILTERGROUP filterDocType
            FILTER caption docType(d) == DocType.type
    ;
END;

DESIGN outDocs {
    BOX(i) { caption = CONCAT '', 'Входящие документы', ' (' + countInDocs(r) +  ')'; }
}

NAVIGATOR {
    inDocs 'Входящие документы УТМ';
}