MODULE InvoicePaymentCashRegister;

REQUIRE SaleInvoice, SaleReturnInvoice, Payment;

NAMESPACE Sale;

printReceiptResult = DATA LOCAL BOOLEAN ();
printReceiptError = DATA LOCAL STRING ();

fiscalType 'Тип платежа' = ABSTRACT INTEGER (Payment.Payment); 
dataFiscalType 'Тип платежа' = DATA INTEGER (Payment.Payment);
fiscalType(Payment.Payment p) += dataFiscalType(p);

dataNumberSection 'Номер секции' = ABSTRACT INTEGER (Invoice);
numberSection 'Номер секции' (Invoice i) = OVERRIDE dataNumberSection(i), 1 IF i IS Invoice;