MODULE RangePurchaseOrder;

REQUIRE PurchaseOrder, Range, PurchaseReserve;

NAMESPACE Range;

EXTEND FORM userOrder
    FILTERGROUP filter2
        FILTER 'В ассортименте' countRangeSkuDepartmentStoreDate(ks, st, dateUserOrder(o)) 'F4';
;

limitRecommendedQuantitySkuUserOrder(s, o) += s IS Sku AND useRangeDepartmentStore(customerStockUserOrder(o)) AND NOT countRangeSkuDepartmentStoreDate(s, customerStockUserOrder(o), dateUserOrder(o));