MODULE PricingPharmacy;

REQUIRE Pricing, ItemPharmacyBy;

NAMESPACE Pricing;

limitRetailMarkupPharmacyCondition 'Условие округления розничной цены' = DATA RoundCondition ();
nameLimitRetailMarkupPharmacyCondition 'Условие округления розничной цены' = name(limitRetailMarkupPharmacyCondition());

EXTEND FORM options
    PROPERTIES () nameLimitRetailMarkupPharmacyCondition
;

DESIGN options {
    pricings {
        MOVE PROPERTY(nameLimitRetailMarkupPharmacyCondition());       
    }
}
