MODULE SaleInternetPickingTerminalOrderLotDefault;

REQUIRE SaleInternetOrderLot, SaleInternetPickingTerminalOrderDefault, TerminalLot;

NAMESPACE Sale;

overProcessPickingInternetOrder(TerminalDocument document, InternetOrderDetail detail) +{
   FOR terminalDocument(TerminalLotDetail l) = document AND sku(terminalDocumentDetail(l)) = sku(detail) NEW lot = InternetOrderDetailLot DO{
       id(lot) <- id(l);
       quantity(lot) <- quantity(l);
       internetOrderDetail(lot) <- detail;
   } 
}

