MODULE TerminalHandler;

REQUIRE Terminal, MachineryPriceTransaction;

processTerminalDocument 'Обработка документа ТСД' (terminalDocument) = ABSTRACT ACTION LIST (TerminalDocument);

upcaseLoginCustomUser 'Логин в верхнем регистре' (customUser) = upper(loginCustomUser(customUser));
customUserUpcaseLogin 'Обычный пользователь' (login) = GROUP AGGR customUser BY upcaseLoginCustomUser(customUser) WHERE customUser IS CustomUser;        