MODULE PurchaseShipmentTax;

REQUIRE PurchaseShipment, SkuLedgerTax, PurchaseOperation;

NAMESPACE Purchase;

notUseDetailVAT 'Не использовать НДС строки накладной для НДС партии' = DATA BOOLEAN (Purchase.Operation);
EXTEND FORM Purchase.operation
    PROPERTIES(o) notUseDetailVAT
;

DESIGN Purchase.operation {
    paramsContainer {
        MOVE PROPERTY(notUseDetailVAT(o));
    }
}

VAT (ShipmentBatch b) += VAT(invoiceDetail(shipmentDetail(b))) IF NOT notUseDetailVAT(operation(invoiceDetail(shipmentDetail(b))));
valueVAT (ShipmentBatch b) += valueVAT(invoiceDetail(shipmentDetail(b))) IF NOT notUseDetailVAT(operation(invoiceDetail(shipmentDetail(b))));