MODULE PurchaseShipment;

REQUIRE Shipment, PurchaseInvoice, PurchaseOperation, OrderShipment, InvoiceShipment, PriceListLedger, StockDocumentSkuLedger;

NAMESPACE Purchase;

//----------------------------------------------- Поставка ---------------------------------------------------//

@defineShipment('Поставки', ' (закупка)', customer, supplier, company, company, Purchase);

selected 'Отм.' = DATA LOCAL BOOLEAN (Shipment); 

EXTEND FORM shipments
    PROPERTIES(s) selected BEFORE isClosed(s)
;

@extendFormFilterAccessStock(Shipment, s, shipments, customerStock, company);

@defineShipmentBatch(customerStock);
@defineShipmentBatchDialog();

@defineExternalizable(userShipment, VARSTRING[100]);
@defineExternalizable(userShipmentDetail, VARSTRING[100]);

in(Shipment s) += s IS Shipment;

expiryDate(UserShipmentDetail detail) <- prevExpiryDate(batch(detail)) WHEN CHANGED (batch(detail));

@defineShipmentStockDestination(supplierStock, customerStock);

@defineOrderShipment(' (закупка)', customerStock);
@defineInvoiceShipment(' (закупка)', customerStock, company, Purchase);
//
//EXTEND FORM invoices
//    PROPERTIES (i) numberByTime
//;

@defineInvoiceShipmentAction(' (закупка)');

@defineInvoiceShipmentBatch();

overCostPrice(d) = ABSTRACT NUMERIC[16,4] (ShipmentDetail);
extraCostPrice(d) = ABSTRACT NUMERIC[16,4] (ShipmentDetail);
costPrice(ShipmentDetail d) = OVERRIDE price(d), overCostPrice(d), extraCostPrice(d);

isShipped = shipped(Invoice invoice) OR NOT quantityNotChargeInvoiceDetail(invoice) > 0.0;

statusShipped 'Статус приемки' (Invoice invoice)= IF isShipped (invoice) AND toShipNotChargeInvoiceDetail(invoice)  
                                                    THEN 'Расхождение'
                                                    ELSE 
                                                        IF isShipped (invoice) 
                                                            THEN 'Оприходована' 
                                                            ELSE 'Не оприходована' IF invoice IS Invoice;
                                                                                                                                                                                                                     
backgroundShip 'Цвет' (Invoice invoice)= RGB(212,255,212) IF invoice IS Invoice AND NOT isShipped(invoice);  

EXTEND FORM invoices
    PROPERTIES (i) READONLY statusShipped BACKGROUND backgroundShip(i) AFTER isCommission(i)
    
    FILTERGROUP shipped 
        FILTER 'Не оприходованы' i IS Invoice AND NOT isShipped(i) 'F11'
        FILTER 'Оприходованы' isShipped(i) 'F10'
;   
@defineOrderShipmentExecution(); 
@defineOrderInvoiceSupplierExecution(purchase, ' (закупка)');

//----------------------------------------------- Операции -----------------------------------------------------//

@defineDocumentOperationContainer(shipment, s);
operation[Shipment.Shipment](Shipment s)+=operation(s);
@extendFormFilterRoleAccess(shipment, s, shipments);
@defineDocumentOperationConstraint(shipment, 'поставка (закупка)', Purchase);

@defineDocumentOperationLegalEntity(userShipment, supplier, 'Поставщик');
@deriveDocumentOperationLegalEntity(userShipment, supplier, userShipment);
@defineDocumentOperationLegalEntity(userShipment, customer, 'Покупатель');
@deriveDocumentOperationLegalEntity(userShipment, customer, userShipment);
@defineDocumentOperationStock(userShipment, supplier, 'Склад поставщика');
@deriveDocumentOperationStock(userShipment, supplier, userShipment);
@defineDocumentOperationStock(userShipment, customer, 'Склад покупателя');
@deriveDocumentOperationStock(userShipment, customer, userShipment);

@defineDocumentOperationRoleOver(userShipment, purchase);

@defineOperationProperty(createShipment, 'Поставка', createContainer);
@deriveDocumentOperationProperty(UserInvoice, createShipment);

@defineOperationProperty(checkExpiryDate, 'Проверять сроки годности', createContainer);

CONSTRAINT (CHANGED(expiryDate(UserShipmentDetail d)) OR CHANGED(operation(d)) OR CHANGED(isPosted(d))) AND checkExpiryDate(operation(d)) AND expiryDate(d) < date(d) AND isPosted(d)
        MESSAGE 'Срок годности товара должен быть больше либо равен дате документа'; 
CONSTRAINT (CHANGED(expiryDate(UserInvoiceDetail d)) OR CHANGED(operation(d)) OR CHANGED(isPosted(d))) AND checkExpiryDate(operation(d)) AND expiryDate(d) < date(d) AND isPosted(d)
        MESSAGE 'Срок годности товара должен быть больше либо равен дате документа'; 

overFillInvoice(UserShipment s, Invoice i) += ACTION {
    ASSIGN operation(s) <- operation(i);
}
operation(InvoiceShipment shipment) += operation(invoice(shipment));

// Добавляем в копирование поставок
overCopy(Shipment s, UserShipment d) += ACTION {
    ASSIGN operation(d) <- operation(s);
}
@defineOperationFilterProperty(shipment, s, shipments, nameFilterShipmentSupplier);
//------------------------------ Ограничение на выбор контрагентов -----------------------------//

CONSTRAINT supplier(UserShipment userShipment) AND NOT isSupplier(supplier(userShipment))
    CHECKED BY supplier[UserShipment] MESSAGE 'Для поставки выбрано в качестве поставщика организация, не являющаяся поставщиком: закупка';
CONSTRAINT customer(UserShipment userShipment) AND NOT isCompany(customer(userShipment))
    CHECKED BY customer[UserShipment] MESSAGE 'Для поставки выбрано в качестве покупателя организация, не являющаяся компанией: закупка';
    
CONSTRAINT filterShipmentSupplier() AND NOT isSupplier(filterShipmentSupplier())
    CHECKED BY filterShipmentSupplier[] MESSAGE 'Для фильтра в поставке выбрана в качестве поставщика организация, не являющаяся поставщиком';
CONSTRAINT filterShipmentCustomer() AND NOT isCompany(filterShipmentCustomer())
    CHECKED BY filterShipmentCustomer[] MESSAGE 'Для фильтра в поставке выбрана в качестве покупателя организация, не являющаяся компанией';   
CONSTRAINT filterShipmentCustomerStock() AND NOT isCompany(filterShipmentCustomerStock())
    CHECKED BY filterShipmentCustomerStock[] MESSAGE 'Для фильтра в поставке выбран в качестве склада покупателя склад, который не принадлежит компании';   
        
CONSTRAINT filterShipmentSupplier() AND filterShipmentSupplierStock() AND NOT in(filterShipmentSupplier(), filterShipmentSupplierStock())
    CHECKED BY filterShipmentSupplierStock[] MESSAGE 'Поставщик и склад поставщика в фильтре для поставки не имеют связи';
CONSTRAINT filterShipmentCustomer() AND filterShipmentCustomerStock() AND NOT in(filterShipmentCustomer(), filterShipmentCustomerStock())
    CHECKED BY filterShipmentCustomerStock[] MESSAGE 'Покупатель и склад покупателя в фильтре для поставки не имеют связи';     
//------------------------------ Ввод в упаковках -----------------------------//

@defineDocumentPack(shipment, s);
packQuantity[Shipment.ShipmentDetail](ShipmentDetail detail) += packQuantity(detail);
DESIGN userShipment {
    headerExtraParams {
        NEW headerPack {
            caption = 'Упаковка';
            MOVE PROPERTY(showPack(s));
        }
    }
}
@deriveDocumentOperationProperty(UserShipment, showPack);

@defineOrderShipmentPack();
@defineInvoiceShipmentPack();

//------------------------------ Автоматическое проставление свойств -----------------------------//

@deriveDocumentLegalEntityDefaultStock(UserShipment, supplier, userShipment);

@defineDocumentLegalEntityStockAccess(UserShipment, customer, company, userShipment);

//------------------------------ Расширение формы -----------------------------//

EXTEND FORM userShipment

    FILTERGROUP filter
        FILTER 'С остатком ' prevCurrentBalance(ks, s) 'F10'
        FILTER 'В документе ' quantityUserShipmentDetail(ks, s) 'F9'
    FILTERGROUP filter2
        FILTER 'С поступлением ' quantityPurchaseSupplier(supplier(s), ks) 'F8'
//        FILTER 'В прайсе ' 'F7' companyALedgerPriceListTypeSkuStockDateTime(priceListTypeUserShipmentSku(s, ks), ks, customerStockUserShipment(s), dateTimeUserShipment(s)) == supplierUserShipment(s)
;
EXTEND FORM userShipment

    FILTERGROUP filter3
        FILTER 'С остатком ' prevCurrentBalance(b, s) 'F10'
        FILTER 'В документе ' quantityUserShipmentDetail(b, s) 'F9'
    FILTERGROUP filter4
        FILTER 'С поступлением ' quantityPurchaseSupplier(supplier(s), sku(b)) 'F8'
//        FILTER 'В прайсе ' 'F7' companyALedgerPriceListTypeBatchStockDateTime(priceListTypeUserShipmentBatch(s, b), b, customerStockUserShipment(s), dateTimeUserShipment(s)) == supplierUserShipment(s)
;

// Резервы
@extendFormDocumentSkuOrderLedger(shipment, userShipment, s, customerStock);
@extendFormDocumentSkuOrderLedgerAll(userShipment, userShipment, s);

@extendFormDocumentBatchOrderLedger(userShipment, userShipment, s, customerStock);
@extendFormDocumentBatchOrderLedgerAll(userShipment, userShipment, s);

// ------------------------------- Расчет учетной цены для поставки ------------------------ //
calcShipmentPrice = ABSTRACT CASE OVERRIDE FIRST NUMERIC[16,4] (UserInvoiceDetail) PERSISTENT;
calcShipmentPrice (UserInvoiceDetail detail) += WHEN costPrice(detail) THEN costPrice(detail);

extraShipmentPrice = ABSTRACT NUMERIC[16,4] (UserInvoiceDetail) PERSISTENT;

// Цены учетные
shipmentPrice(UserInvoiceDetail detail) <- calcShipmentPrice(detail) (+) extraShipmentPrice(detail) WHEN
    CHANGED(calcShipmentPrice(detail)) OR
    CHANGED(extraShipmentPrice(detail));
price (UserShipmentDetail detail) <- shipmentPrice(invoiceDetail(detail))
    WHEN CHANGED(shipmentPrice(invoiceDetail(detail)));

// Цену записываем всегда, чтобы она проставлялась при создании поставки отдельно
//      OR
//     CHANGED(createShipmentUserInvoiceDetail(detail)))
//        AND createShipmentUserInvoiceDetail(detail);

// ------------------------------- Коды партии ----------------------------------- //

idBatch 'Код партии' = ABSTRACT VARSTRING[100] (ShipmentDetail) MINCHARWIDTH 10 PREFCHARWIDTH 15;
idBatch 'Код партии' = DATA VARSTRING[100] (UserShipmentDetail) MINCHARWIDTH 10 PREFCHARWIDTH 15;
idBatch(UserShipmentDetail detail) += idBatch(detail);

idBatch(InvoiceShipmentDetail detail) += idBatch(invoiceDetail(detail));

@defineMovementIdBatch(shipmentDetail, batch, customerStock);
@defineBalancesIdBatch(shipmentDetail, batch);
@defineMovementIdBatch(userShipmentDetail, batch, customerStock);
@defineBalancesIdBatch(userShipmentDetail, batch);

EXTEND FORM userShipment
    PROPERTIES(d) READONLYIF batch(d) SHOWIF showIDs()
                  idBatch AFTER nameBatch(d)
;
EXTEND FORM shipments
    PROPERTIES(d) READONLY SHOWIF showIDs()
                  idBatch AFTER nameBatch(d)
;

// ------------------------------- Проведение по товарному отчету ------------------------ //
@implementStockDocumentLedgerInc(Shipment, customerStock);
type(Shipment l) += 'Закупка' IF l IS Shipment;
sumItem (Shipment ledger) += sumItemShipmentDetail(ledger);
sumContainer (Shipment ledger) += sumContainerShipmentDetail(ledger);

legalEntity(Shipment ledger) += supplier(ledger);  
legalEntityStock(Shipment ledger) += supplierStock(ledger);  

operation[StockDocumentLedger](Shipment ledger) += operation(ledger);

edit[StockDocumentLedger](Shipment l) += ACTION edit(l);
close[StockDocumentLedger](Shipment l) += ACTION close(l);


overSkipStockDocumentLedger = ABSTRACT BOOLEAN (Shipment);

skip(Shipment l) += (isCommission(invoice(l)) IF excludeComission()) OR overSkipStockDocumentLedger(l);

// -------------------------------- Наименования для документов --------------------------- //
documentNameSku 'Наименование (для документов)' = ABSTRACT VARISTRING[255] (ShipmentDetail) MINCHARWIDTH 30 PREFCHARWIDTH 60;
documentNameSku 'Наименование (для документов)' = DATA VARISTRING[255] (UserShipmentDetail) MINCHARWIDTH 30 PREFCHARWIDTH 60;
documentNameSku(UserShipmentDetail detail) += documentNameSku(detail);

documentNameSku(InvoiceShipmentDetail detail) += documentNameSku(invoiceDetail(detail));

EXTEND FORM userShipment
    PROPERTIES(d) documentNameSku AFTER nameSku(d) SHOWIF useDocumentNameSku()
;
EXTEND FORM shipments
    PROPERTIES(d) documentNameSku AFTER nameSku(d) SHOWIF useDocumentNameSku()
;

// ------------------------------- Проведение по регистру остатков ------------------------ //

overCreateBatch = ABSTRACT BOOLEAN (ShipmentDetail);
createBatch (ShipmentDetail detail) = (detail IS ShipmentDetail OR overCreateBatch(detail)) AND NOT batch(detail);

// Создаем партию
CLASS ShipmentBatch 'Партия на основе закупки';
@defineAggregation(shipmentDetail, shipmentBatch, createBatch);

@defineSkuLedgerAggregation(shipmentDetail, shipmentBatch, sku, customerStock);

quantity (ShipmentBatch batch) = quantity(shipmentDetail(batch));
quantity(ShipmentBatch b) += quantity(b);
price (ShipmentBatch batch) = price(shipmentDetail(batch));
costPrice (ShipmentBatch batch) = costPrice(shipmentDetail(batch));

replace(Sku s, ShipmentBatch b) += ACTION { sku(UserShipmentDetail detail) <- s WHERE shipmentBatch(detail) == b;}
replace(Sku s, ShipmentBatch b) += ACTION { sku(UserInvoiceDetail detail) <- s WHERE detail == invoiceDetail[UserShipmentDetail](shipmentDetail(b));}

@implementBatch(ShipmentBatch, sku, stock, costPrice);
manufactureDate(ShipmentBatch batch) += manufactureDate(shipmentDetail(batch)); 
id(ShipmentBatch ledger) += idBatch(shipmentDetail(ledger));
expiryDate (ShipmentBatch ledger) += expiryDate(shipmentDetail(ledger));
sum (ShipmentBatch ledger) += sum(shipmentDetail(ledger));
series (ShipmentBatch ledger) += series(shipment(shipmentDetail(ledger)));
number (ShipmentBatch ledger) += number(shipment(shipmentDetail(ledger)));
supplier (ShipmentBatch ledger) += supplier(shipmentDetail(ledger));
supplierStock (ShipmentBatch ledger) += supplierStock(shipmentDetail(ledger));

overDocumentNameSku (ShipmentBatch ledger) += documentNameSku(shipmentDetail(ledger)); 

batch(Batch ledger) += ledger AS Batch;

stockDocumentLedger(ShipmentBatch ledger) += shipment(shipmentDetail(ledger)); 

cost(InvoiceDetail ledger, Batch batch) += cost (ledger, batch); 
in (InvoiceDetail ledger, Batch batch) += TRUE IF in(ledger, batch); 

name(ShipmentBatch batch) += VARISTRING[200](CONCAT '', STRING[10](date(shipmentDetail(batch))), '/ ' + seriesNumber(shipment(shipmentDetail(batch))),
                             '/ ' + fullNameSupplier(shipmentDetail(batch)));
  
edit[SkuLedger](ShipmentBatch batch) += ACTION edit(shipmentDetail(batch));
show[SkuLedger](ShipmentBatch batch) += ACTION show(shipmentDetail(batch));

// Проводим по регистру учетных цен
supplier (ShipmentBatch ledger) = supplier(shipmentDetail(ledger));
@implementSystemLedgerPriceListTypeBatch(account, ShipmentBatch, supplier, stock);

edit[PriceListLedger](ShipmentBatch d) += ACTION edit(shipmentDetail(d));
// Создаем просто inLIFOSkuLedger
createSkuLedger (ShipmentDetail detail) = detail IS ShipmentDetail AND NOT createBatch(detail);

CLASS ShipmentSkuLedger 'Изменение остатка на основе закупки';
TABLE shipmentSkuLedger (ShipmentSkuLedger);
@defineAggregation(shipmentDetail, shipmentSkuLedger, createSkuLedger);

@defineSkuLedgerAggregation(shipmentDetail, shipmentSkuLedger, sku, customerStock);

quantity (ShipmentSkuLedger ledger) = quantity(shipmentDetail(ledger));
price (ShipmentSkuLedger ledger) = price(shipmentDetail(ledger));
batch (ShipmentSkuLedger ledger) = batch(shipmentDetail(ledger));

quantityShipmentSkuLedger (batch) = GROUP SUM quantity (ShipmentSkuLedger ledger) 
                                                   IF NOT isCompanySupplier(shipmentDetail(ledger)) 
                                               BY batch(ledger);
extraShippedQuantity(Batch b) += quantityShipmentSkuLedger(b); 

@implementSkuLedgerInLIFO(ShipmentSkuLedger, sku, stock);
quantity (ShipmentSkuLedger ledger) += quantity (ledger);
changed(ShipmentSkuLedger ledger) += CHANGED(batch(ledger));
sum (ShipmentSkuLedger ledger) += sum(shipmentDetail(ledger));

batch(ShipmentSkuLedger ledger) += batch(ledger);

stockDocumentLedger (ShipmentSkuLedger ledger) += shipment(shipmentDetail(ledger)); 

skuLedger (ShipmentDetail detail) = IF createBatch(detail) THEN shipmentBatch(detail) ELSE shipmentSkuLedger(detail);
ledgerBatch (ShipmentDetail detail) = OVERRIDE shipmentBatch(detail), batch(detail);
@implementDocumentBatch(shipment, ledger);

cost(ShipmentDetail detail, Batch batch) += cost(skuLedger(detail), batch);

batch[Invoice.InvoiceDetail](InvoiceDetail d) += OVERRIDE batch(d), ledgerBatch(invoiceShipmentDetail(d));

edit[SkuLedger](ShipmentSkuLedger shipmentSkuLedger) += ACTION edit(shipmentDetail(shipmentSkuLedger));
show[SkuLedger](ShipmentSkuLedger shipmentSkuLedger) += ACTION show(shipmentDetail(shipmentSkuLedger));

overBatch(InvoiceDetail detail)= OVERRIDE batch(detail), ledgerBatch(invoiceShipmentDetail(detail));  
// ------------------------------- Проведение регистру учетных цен ------------------------ //

supplier (ShipmentSkuLedger ledger) = supplier(shipmentDetail(ledger));
@implementSystemLedgerPriceListType(account, ShipmentSkuLedger, supplier, stock);
in (ShipmentSkuLedger ledger, Batch batch) += batch(shipmentDetail(ledger)) == batch; 

edit[PriceListLedger](ShipmentSkuLedger d) += ACTION edit(shipmentDetail(d));
//
defaultUserShipmentDetail (sku, shipment, price) = GROUP MIN UserShipmentDetail detail IF NOT batch(detail)
    BY sku(detail), userShipment(detail), price(detail);

defaultUserShipmentDetail(UserShipmentDetail detail) = defaultUserShipmentDetail(sku(detail), userShipment(detail), price(detail));

mergeBatch 'Соединить партии'(UserShipment shipment) = ACTION {
    ASK 'Документ будет автоматически сохранен, вы действительно хотите выполнить действие "Соединить партии?"' DO {
        apply();
        FOR userShipment(UserShipmentDetail detail) == shipment
            AND NOT defaultUserShipmentDetail(detail) == detail
            AND NOT batch(detail) DO {
                batch(detail) <- shipmentBatch(defaultUserShipmentDetail(detail));

        }
    }
} TOOLBAR;

EXTEND FORM userShipment
    PROPERTIES(s) TODRAW d mergeBatch
;
//Строка накладной партии
invoiceDetail = ABSTRACT InvoiceDetail (Batch);
invoiceDetail(ShipmentBatch b) += invoiceDetail(shipmentDetail(b));

barcodePack (Batch batch) = barcodePack(invoiceDetail(batch));
captionBarcodePack 'Упаковка' (Batch batch) = caption(barcodePack(batch));
idBarcodePack 'Штрихкод упаковки' (Batch batch) = id(barcodePack(batch));
//invoiceDetailBatch 'Строка накладной партии' = invoiceDetailShipmentDetail(shipmentDetailShipmentBatch(batch));

descriptionInvoiceDetailInvoiceDetail 'Строка накладной партии' = description(invoiceDetail(Batch batch));
priceInvoiceDetail 'Цена закупки' (Batch batch) = price(invoiceDetail(batch));
invoicePriceInvoiceDetail 'Цена закупки с НДС' (Batch batch) = OVERRIDE 
    (invoiceSum(invoiceDetail(batch)) / (quantity(invoiceDetail(batch)) IF quantity(invoiceDetail(batch))!=0)),
    invoicePrice(invoiceDetail(batch));

currencyInvoiceDetail 'Валюта закупки' (Batch batch) = currency(invoiceDetail(batch));
shortNameCurrencyInvoiceDetail 'Валюта закупки' (Batch batch) = shortName(currencyInvoiceDetail(batch));
rateExchangeInvoiceDetail 'Курс' (Batch batch) = rateExchange(invoiceDetail(batch));
homePriceInvoiceDetail 'Цена закупки (кон.)' (Batch batch) = homePrice(invoiceDetail(batch));

receiveShipment (UserInvoice invoice)+= ACTION  {
    IF invoice IS UserInvoice THEN {
        createShipment(invoice) <- TRUE;           
    }
};


deleteCreate (InvoiceShipment shipment)+= WHEN invoice(shipment) IS UserInvoice THEN  ACTION  {
    createShipment(Invoice invoice) <- NULL WHERE invoice == invoice(shipment);          
};

EXTEND FORM batches 
    PROPERTIES(bt)  READONLY BEFORE cost(bt) priceInvoiceDetail 
    PROPERTIES (bt) READONLY captionBarcodePack, idBarcodePack
; 

//-- Запрет на изменение документа другим пользователем
@defineOperationChangesDocument(shipment, UserShipment, preventChangesDocument, created);

overShowEdit (Shipment i) += showEditDeleteUser(i) AND isOpened(i) AND NOT skipShowEdit(i);
overShowDelete (UserShipment i) += showEditDeleteUser(i) AND isUserOpened(i) AND NOT skipShowDelete(i); 

// --------------- Проведение по регистру закупок ------------- //
shipmentQuantity[PurchaseLedger] (InvoiceDetail ledger) += shipmentQuantity(ledger);

NAVIGATOR {
    purchaseStockNavigator {
        ADD shipments;
    }
}

EXTEND FORM invoices
    OBJECTS dsLog = DocumentDetailLog GRID
    PROPERTIES (dsLog) SHOWIF enableDocumentLog() READONLY index, idSku, nameSku, quantity, price, nameUser, date, time, note
    FILTERS document(dsLog) == invoiceShipment(i)
;

DESIGN invoices {
    documentHistory { 
        historyTabs {
             NEW detailShipmentLog{
                 caption = 'По строкам (поставка)';
                 MOVE dsLog.box;
             }
        }
    }    
} 

CONSTRAINT isPosted(ShipmentDetail d) AND isShipmentPrice(operation(d)) AND NOT price(d)
    MESSAGE 'Для документа (закупка) должна быть задана учетная цена';
    
shipmentDateTime(InvoiceDetail l) += shipmentDateTime(l);