MODULE OrderInvoiceDashboardEDI;

REQUIRE OrderInvoiceDashboard, EDI;

NAMESPACE EDI;


despatchAdvices 'Уведомления об отгрузке' = GROUP CONCAT deliveryNoteNumber(EOrderDespatchAdvice a) , ',' BY eOrder(a) MINCHARWIDTH 10 PREFCHARWIDTH 20;
 
EXTEND FORM orderInvoiceDashboard
    PROPERTIES (o) READONLY despatchAdvices BEFORE note(o)
    FILTERGROUP despatch 
        FILTER 'Уведомления об отгрузке' despatchAdvices(o); 