MODULE PurchaseOrderPriceList;

REQUIRE PurchaseOrder, PriceList;

NAMESPACE Purchase;

EXTEND FORM userOrder
    EXTEND FILTERGROUP filter1
        FILTER 'В прайсе' prevPriceA(ledgerPriceListType(priceListType(o, ks)),ks,st,supplier(o),dateTime(o)) 'F7' DEFAULT                                                                                      
        FILTER 'В прайсе склада' prevPriceA(ledgerPriceListType(priceListType(o, ks)),ks,st,supplierStock(o),dateTime(o)) 'F6' 
;
