MODULE PriceListAlcohol;

REQUIRE PriceList, ItemAlcohol;

NAMESPACE PriceList;

alcoholSupplierTypeUser = alcoholSupplierType(company(priceList(PriceListDetail detail)), sku(detail)); 
nameAlcoholSupplierTypeUser 'Тип поставщика алкоголя' = staticCaption(alcoholSupplierTypeUser(PriceListDetail detail));

showAlcoholSupplierType 'Тип поставщика алкоголя' = DATA BOOLEAN (UserPriceList);
showAlcoholSupplierTypeUser = showAlcoholSupplierType(priceList(PriceListDetail detail));

changeAlcoholSupplierType = ACTION (PriceListDetail detail) {
    REQUEST OBJECT d
        FORM alcoholSupplierTypies DIALOG SHOWDROP;
    IF formResult() == FormResult.ok THEN
        FOR LegalEntity l == company(detail) AND Sku i == sku(detail) DO {
            alcoholSupplierType(l, i) <- requestedObject();
        }
    ELSE
        IF formResult() == FormResult.drop THEN
            FOR LegalEntity l == company(detail) AND Sku i == sku(detail) DO {
                alcoholSupplierType(l, i) <- NULL;   
            }             
}   

changeWYSAlcoholSupplierType = ACTION (PriceListDetail detail) {
    REQUEST ISTRING[100] INPUT;
    FOR LegalEntity l == company(detail) AND Sku i == sku(detail) DO {
        alcoholSupplierType(l, i) <- alcoholSupplierTypeCaption(requestedString());
    }
}   

EXTEND FORM userPriceList
    PROPERTIES (p) showAlcoholSupplierType
    PROPERTIES (d) nameAlcoholSupplierTypeUser ON CHANGE changeAlcoholSupplierType(d) ON CHANGEWYS changeWYSAlcoholSupplierType(d)  
                                SHOWIF showAlcoholSupplierTypeUser(d) AFTER nameSku(d)
;

DESIGN userPriceList{
    param {
        MOVE PROPERTY(showAlcoholSupplierType(p)); 
    }    
}