MODULE SaleStatistics;

REQUIRE System, Utils, Historizable, Stock, LegalEntity, SaleLedger, Sale, Integration;

NAMESPACE Sale;

// ----------------------------------- Статистический классификатор ------------------------------------------ //
CLASS StatisticGroupType 'Тип классификатора статистических групп' : GroupType;
TABLE statisticGroupType (StatisticGroupType);

countryStatisticGroupType = DATA Country (StatisticGroupType);
nameCountryStatisticGroupType 'Страна' (type)= nameCountry(countryStatisticGroupType(type)) IN base;

nameStatisticGroupType 'Наименование' = DATA VARISTRING[100](StatisticGroupType);

idStatisticGroupType 'Идентификатор' = DATA VARSTRING[20] (StatisticGroupType) MINCHARWIDTH 3 MAXCHARWIDTH 10 PREFCHARWIDTH 7;

typeIdStatisticGroupType (string1) = GROUP AGGR type
    BY idStatisticGroupType(type) WHERE type IS StatisticGroupType;

FORM statisticGroupType 'Тип классификатора статистических групп'
    OBJECTS t = StatisticGroupType FIXED PANEL
    PROPERTIES(t) nameStatisticGroupType, idStatisticGroupType, nameCountryStatisticGroupType
    EDIT StatisticGroupType OBJECT t
;

FORM dialogStatisticGroupType 'Тип статистической группы'
    OBJECTS t = StatisticGroupType
    PROPERTIES(t) READONLY nameStatisticGroupType, idStatisticGroupType, nameCountryStatisticGroupType
    DIALOG StatisticGroupType OBJECT t
;

FORM statisticGroupTypes 'Типы статистических групп'
    OBJECTS t = StatisticGroupType
    PROPERTIES(t) READONLY nameStatisticGroupType, idStatisticGroupType, nameCountryStatisticGroupType
    PROPERTIES(t) ADDFORM, EDITFORM, DELETE
;

CLASS StatisticGroup 'Статистическая группа': Group;
TABLE statisticGroup(StatisticGroup);

nameStatisticGroup 'Наименование' = DATA VARISTRING[150](StatisticGroup);

CLASS GroupStatic 'Ед. изм.' {
    statisticLiter 'Литр',
    statisticThing 'Штука',
    statisticPounds 'Килограмм',
    statisticSum 'Валюта',
    statisticLinearMeters 'Пог. м',
    statisticPair 'Пара',
    statisticConditionalPiece 'Усл. кус.',
    statisticSquareMeters 'Квадратный м',
    statisticCubicMeters 'Кубический м'
}
FORM GroupStatics
    OBJECTS g = GroupStatic
    PROPERTIES(g) staticCaption
    DIALOG GroupStatic OBJECT g
;

TABLE groupStaticUOM (GroupStatic, UOM);
factorGroupStaticUOM 'Коэффициент перевода' = DATA NUMERIC[14,3] (GroupStatic, UOM);

FORM groupStatics 'Конвертация статистических ед. изм.'
    OBJECTS g=GroupStatic FIXED PANEL
    PROPERTIES(g) SELECTOR staticCaption

    OBJECTS u=UOM
    PROPERTIES   nameUOM(u) READONLY, shortNameUOM(u) READONLY, factorGroupStaticUOM(g,u)

    FILTERGROUP batch
        FILTER 'Ед.изм. с коэфф.' 'F11' factorGroupStaticUOM(g,u)
;

TABLE statisticGroupStatisticGroup(StatisticGroup, StatisticGroup);
@defineHierarchy(statisticGroup);

groupTypeStatisticGroup = DATA StatisticGroupType (StatisticGroup) AUTOSET;
nameGroupTypeStatisticGroup 'Тип классификатора' (group) = nameStatisticGroupType(groupTypeStatisticGroup(group));

countryStatisticGroup = countryStatisticGroupType(groupTypeStatisticGroup(group));
nameCountryStatisticGroup 'Страна' (statisticGroup)= nameCountry(countryStatisticGroup(statisticGroup)) IN base;

unitMeasureStatisticGroup 'Ед. изм. ИД' (statisticGroup) = DATA GroupStatic (StatisticGroup);
nameUOMStatisticGroup 'Ед. изм.' (statisticGroup) = staticCaption(unitMeasureStatisticGroup(statisticGroup)) MINCHARWIDTH 15 MAXCHARWIDTH 15 PREFCHARWIDTH 15;

sidStatisticGroup 'Код группы' (statisticGroup) = DATA STRING[12] (StatisticGroup)  MINCHARWIDTH 12 MAXCHARWIDTH 12 PREFCHARWIDTH 12;
canonicalNumberStatisticGroup 'Канонический код' (statisticGroup) = VARSTRING[255](
                           [GROUP CONCAT sidStatisticGroup(parent), ' / ' BY child ORDER DESC levelStatisticGroupStatisticGroup(child, parent)](statisticGroup))
                           MINCHARWIDTH 50 MAXCHARWIDTH 100 PREFCHARWIDTH 100 PERSISTENT;

canonicalNumberNameStatisticGroup 'Канонический код-название' (statisticGroup) = [FORMULA VARSTRING[100] '$1 || \' / \' || $2'](
    canonicalNumberStatisticGroup(statisticGroup), nameStatisticGroup(statisticGroup));

groupIdTypeIdGroup (string1, string2) = GROUP AGGR group
    BY idStatisticGroupType(groupTypeStatisticGroup(group)), sidStatisticGroup(group) WHERE group IS StatisticGroup;

sidParentStatisticGroup 'Код родительского объекта' (statisticGroup) = sidStatisticGroup(parentStatisticGroup(statisticGroup));

conversionFactorStatisticGroup 'Коэффициент перевода' (statisticGroup) = DATA NUMERIC[14,5] (StatisticGroup);

FORM statisticGroup 'Статистическая группа'
    OBJECTS g=StatisticGroup FIXED PANEL
    PROPERTIES(g)   nameGroupTypeStatisticGroup, nameStat=nameStatisticGroup, nameParentStatisticGroup, sidParentStatisticGroup,
                    sidStatisticGroup, nameUOMStatisticGroup,conversionFactorStatisticGroup

    EDIT StatisticGroup OBJECT g
;

addStatisticGroupType 'Добавить' = ACTION (group, type) NEWSESSION {
    FOR ADDOBJ g = StatisticGroup DO {
        ASSIGN parentStatisticGroup(g) <- group;
        ASSIGN groupTypeStatisticGroup(g) <- type;
        FORM statisticGroup OBJECTS g = g MODAL;
        IF formResult() == FormResult.ok THEN
            EXEC apply();
    };
} TOOLBAR IMAGE 'add.png' EDITKEY 'INSERT';

addStatisticGroup 'Добавить' (group)= addStatisticGroupType(group, groupTypeStatisticGroup(group)) TOOLBAR IMAGE 'add.png' EDITKEY 'INSERT';

TABLE statisticGroupTypeSku (StatisticGroupType, Sku);
statisticGroupTypeSku = ABSTRACT StatisticGroup (StatisticGroupType, Sku) PERSISTENT;
nameStatisticGroupTypeSku 'Статистическая группа' = nameStatisticGroup(statisticGroupTypeSku(type, sku));

TABLE statisticGroupSku(StatisticGroup, Sku);
isParentStatisticGroupSku (group, sku) = isParentStatisticGroupStatisticGroup(statisticGroupTypeSku(groupTypeStatisticGroup(group),sku), group) PERSISTENT;
isParentLeafStatisticGroupSku (group, sku) = isParentLeafStatisticGroupStatisticGroup(statisticGroupTypeSku(groupTypeStatisticGroup(group),sku), group) PERSISTENT;
parentStatisticGroupTypeSku (type, sku) = parentStatisticGroup(statisticGroupTypeSku(type,sku)) PERSISTENT;

residentCountryCountry 'Отечественный производитель' =  DATA BOOLEAN (Country, Country);
residentStatisticGroupSku (group, sku) = residentCountryCountry(countryStatisticGroupType(groupTypeStatisticGroup(group)), countrySku(sku));

FORM statisticGroups 'Статистические группы'

    OBJECTS ss=Country FIXED PANEL
    PROPERTIES(ss) SELECTOR nameCountry

    OBJECTS c=StatisticGroupType FIXED PANEL
    PROPERTIES(c) SELECTOR nameStatisticGroupType
    FILTERS countryStatisticGroupType(c) == ss

    TREE treeGroups g=StatisticGroup PARENT parentStatisticGroup
    PROPERTIES READONLY nameStatisticGroup(g), sidStatisticGroup(g)
    PROPERTIES(g,c)       addStatisticGroupType
    PROPERTIES(g) EDITFORM, ADDFORM
    ORDER BY sidStatisticGroup

    OBJECTS cg=StatisticGroup
    PROPERTIES(cg)     READONLY canonicalNumberNameStatisticGroup, sidStatisticGroup, nameUOMStatisticGroup,
                       conversionFactorStatisticGroup
    PROPERTIES(cg)     DELETE

    FILTERS groupTypeStatisticGroup(g) == c,
            groupTypeStatisticGroup(cg) == c

    OBJECTS s = Country

    PROPERTIES(s) READONLY nameCountry, nameOriginCountry, sidCountry, sidOrigin2Country, sidOrigin3Country,
                           nameCurrencyCountry, nameLanguageCountry
    PROPERTIES(ss,s) residentCountryCountry
    FILTERGROUP filter
        FILTER 'Страны явл. отечественными' 'F11' residentCountryCountry(ss, s) DEFAULT

    FILTERGROUP filters
        FILTER 'Все листья' 'F10' isParentLeafStatisticGroupStatisticGroup(cg, g) DEFAULT
        FILTER 'Всех потомков' 'F9' isParentStatisticGroupStatisticGroup(cg, g)
        FILTER 'Только непосредственных потомков' 'F8' parentStatisticGroup(cg) == g
;

DESIGN statisticGroups FROM DEFAULT {
    main {
        NEW header {
            type = CONTAINERH;
            ADD ss.box;
            ADD c.box;
        }
        NEW specification.box {
            type = TABBED;
            fill = 1;
            NEW topContainer{
                caption = 'Статистические группы';
                type = SPLITH;
                fill = 1;
                ADD treeGroups.tree.box;
                ADD cg.box{fill = 4;}
            }
            ADD s.box {caption = 'Страны являющиеся отечественными';}
        }
    }
    ADD functions.box;
}

FORM statisticGroupDialog 'Статистические группы'
    OBJECTS c=StatisticGroupType FIXED PANEL
    PROPERTIES(c) SELECTOR nameStatisticGroupType

    TREE treeGroups g=StatisticGroup PARENT parentStatisticGroup
    PROPERTIES(g) READONLY nameStatisticGroup, nameUOMStatisticGroup, sidStatisticGroup, canonicalNumberStatisticGroup
    PROPERTIES(g) ADDFORM, EDITFORM, DELETE
    FILTERS groupTypeStatisticGroup(g) == c
    ORDER BY canonicalNumberStatisticGroup

    DIALOG StatisticGroup OBJECT g
;

//---------------------------------------------- Отображение в форме товаров -------------------------------------//

parentGroup (statisticGroup) += parentStatisticGroup(statisticGroup);
nameGroup (statisticGroup) += nameStatisticGroup(statisticGroup);
nameGroupType (statisticGroupType) += nameStatisticGroupType (statisticGroupType);
groupTypeGroup (statisticGroup) += groupTypeStatisticGroup (statisticGroup);
groupGroupTypeSku (statisticGroupType, sku) += WHEN CLASS(statisticGroupTypeSku (statisticGroupType, sku)) THEN statisticGroupTypeSku (statisticGroupType, sku);

//---------------------------------------------- Формы стат. отчетов -------------------------------------//

//  12 ТОРГ ПРОДАЖИ

netWeightSoldSkuStockDateFromTo 'Вес проданного товара, кг' (sku, stock, dateFrom, dateTo) =
    quantitySoldSkuStockDateFromTo(sku, stock, dateFrom, dateTo) *
    (OVERRIDE 1 IF sku IS Sku, netWeightSku(sku) IF NOT isWeightSku(sku));
volumeSoldSkuStockDateFromTo 'Объем проданного товара, л' (sku, stock, dateFrom, dateTo) =
    quantitySoldSkuStockDateFromTo(sku, stock, dateFrom, dateTo) * volumeSku(sku);
// sumSoldSkuStockDateFromTo 'Продано, сумма' (sku, stock, dateFrom, dateTo)   - рубли
//quantitySoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo)                      - шт.

                            //с коэффициентом пересчета за период//
//всего
quantitySoldByStatisticGroupDateFromTo 'Продано, шт' (group, stock, dateFrom, dateTo)=
    [GROUP SUM quantitySoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    isParentStatisticGroupSku(group, sku) BY group, stock, dateFrom, dateTo](group, stock, dateFrom, dateTo)/
            (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
netWeightSoldByStatisticGroupDateFromTo 'Продано, кг' (group, stock, dateFrom, dateTo)=
    [GROUP SUM netWeightSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo](group, stock, dateFrom, dateTo)/
        (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
volumeSoldByStatisticGroupDateFromTo 'Продано, л' (group, stock, dateFrom, dateTo)=
    [GROUP SUM volumeSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo](group, stock, dateFrom, dateTo)/
        (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
retailSumSoldByStatisticGroupDateFromTo 'Продано, сум.' (group, stock, dateFrom, dateTo)=
    [GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo](group, stock, dateFrom, dateTo)/
        (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

//отечеств. пр-ва
quantitySoldResidentByStatisticGroupDateFromTo 'Продано, шт' (group, stock, dateFrom, dateTo)=
    [GROUP SUM quantitySoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    residentStatisticGroupSku (group, sku) IF isParentStatisticGroupSku(group, sku)
        BY group, stock, dateFrom, dateTo](group, stock, dateFrom, dateTo)/
            (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
netWeightSoldResidentByStatisticGroupDateFromTo 'Продано, кг' (group, stock, dateFrom, dateTo)=
    [GROUP SUM netWeightSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo](group, stock, dateFrom, dateTo)/
        (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
volumeSoldResidentByStatisticGroupDateFromTo 'Продано, л' (group, stock, dateFrom, dateTo)=
    [GROUP SUM volumeSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo](group, stock, dateFrom, dateTo)/
        (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
retailSumSoldResidentByStatisticGroupDateFromTo 'Продано, сум.' (group, stock, dateFrom, dateTo)=
    [GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo](group, stock, dateFrom, dateTo)/
        (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightBalanceASkuLedgerDate 'Вес товара на конец , кг' (sku, stock, dateTo) =
    balanceASkuStockDate (sku, stock, dateTo) * (OVERRIDE 1 IF sku IS Sku, netWeightSku(sku) IF NOT isWeightSku(sku));
volumeBalanceASkuLedgerDate 'Объем товара на конец , л' (sku, stock, dateTo) =
    balanceASkuStockDate (sku, stock, dateTo) * volumeSku(sku);

//sumASkuStockDate (sku, stock, dateTo) -  сумма на конец

//retailSumBalanceASkuLedgerDate 'Сумма товара на конец , сум.' (sku, stock, dateTo) =
//    retailPriceASkuStockDate (sku, stock, dateTo) * balanceASkuStockDate(sku, stock, dateTo);
//balanceASkuStockDate (sku, stock, dateTo)    - шт.

                                   //с коэффициентом пересчета на конец//
// всего
balanceByStatisticGroupDateTo 'Остаток на конец' (group, stock, dateTo)=
    [GROUP SUM balanceASkuStockDate (sku, stock, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    isParentStatisticGroupSku(group, sku)
        BY group, stock, dateTo](group, stock, dateTo)/
            (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
netWeightByStatisticGroupDateTo 'Вес на конец, кг' (group, stock, dateTo)=
    [GROUP SUM netWeightBalanceASkuLedgerDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo](group, stock, dateTo)/
        (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
volumeByStatisticGroupDateTo 'Объем на конец, л' (group, stock, dateTo)=
    [GROUP SUM volumeBalanceASkuLedgerDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo](group, stock, dateTo)/
        (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
retailSumByStatisticGroupDateTo 'Сумма на конец, сум.' (group, stock, dateTo)=
    [GROUP SUM sumASkuStockDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo](group, stock, dateTo)/
        (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

// отечеств. пр-ва
balanceResidentByStatisticGroupDateTo 'Остаток на конец' (group, stock, dateTo)=
    [GROUP SUM balanceASkuStockDate (sku, stock, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
        BY group, stock, dateTo](group, stock, dateTo)/
            (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
netWeightResidentByStatisticGroupDateTo 'Вес на конец, кг' (group, stock, dateTo)=
    [GROUP SUM netWeightBalanceASkuLedgerDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo](group, stock, dateTo)/
        (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
volumeResidentByStatisticGroupDateTo 'Объем на конец, л' (group, stock, dateTo)=
    [GROUP SUM volumeBalanceASkuLedgerDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo](group, stock, dateTo)/
        (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
retailSumResidentByStatisticGroupDateTo 'Сумма на конец, сум.' (group, stock, dateTo)=
    [GROUP SUM sumASkuStockDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo](group, stock, dateTo)/
        (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

valueByStatisticGroupDateFromTo 'Продано' (group, stock, dateFrom, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN quantitySoldByStatisticGroupDateFromTo(group, stock, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightSoldByStatisticGroupDateFromTo(group, stock, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeSoldByStatisticGroupDateFromTo(group, stock, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumSoldByStatisticGroupDateFromTo(group, stock, dateFrom, dateTo)
        ELSE 0 IF group IS StatisticGroup AND stock IS Stock
    ;
valueResidentByStatisticGroupDateFromTo 'Продано, бел. пр-ва' (group, stock, dateFrom, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN quantitySoldResidentByStatisticGroupDateFromTo(group, stock, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightSoldResidentByStatisticGroupDateFromTo(group, stock, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeSoldResidentByStatisticGroupDateFromTo(group, stock, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumSoldResidentByStatisticGroupDateFromTo(group, stock, dateFrom, dateTo)
        ELSE 0 IF group IS StatisticGroup AND stock IS Stock
    ;

valueByStatisticGroupDateTo 'Остаток на конец' (group, stock, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN balanceByStatisticGroupDateTo(group, stock, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightByStatisticGroupDateTo(group, stock, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeByStatisticGroupDateTo(group, stock, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumByStatisticGroupDateTo(group, stock, dateTo)
        ELSE 0 IF group IS StatisticGroup AND stock IS Stock AND dateTo IS DATE
    ;
valueResidentByStatisticGroupDateTo 'Остаток на конец, бел. пр-ва' (group, stock, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN balanceResidentByStatisticGroupDateTo(group, stock, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightResidentByStatisticGroupDateTo(group, stock, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeResidentByStatisticGroupDateTo(group, stock, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumResidentByStatisticGroupDateTo(group, stock, dateTo)
        ELSE 0 IF group IS StatisticGroup AND stock IS Stock AND dateTo IS DATE
    ;

FORM statisticalReport 'Статистика (продажи) склад/группа/sku'

    OBJECTS dates = (dFrom = DATE, dTo = DATE) FIXED PANEL
    PROPERTIES OBJVALUE(dFrom), OBJVALUE(dTo)
    OBJECTS c = StatisticGroupType FIXED PANEL
    PROPERTIES SELECTOR nameStatisticGroupType(c)

    TREE stockTree a = STRING[3], sg = StockGroup PARENT parentStockGroup, ts = Stock
    PROPERTIES READONLY OBJVALUE(a), sgTreeName = nameStockGroup(sg), nameStock(ts)
    ORDER BY sgTreeName
    FILTERS stringEqualsAll(a),
            stockGroupStock(ts) == sg

    TREE treeGroups g=StatisticGroup PARENT parentStatisticGroup
    PROPERTIES READONLY gname = nameStatisticGroup(g),  sidStatisticGroup(g), nameUOMStatisticGroup(g)
    ORDER BY gname
    FILTERS groupTypeStatisticGroup(g) ==c

    OBJECTS           sts=(st=Stock, s=Sku)
    PROPERTIES        READONLY nameS=nameSku(s), nameStock(st)
    FILTERS           st == ts AND sg IS StockGroup OR isParentStockGroupStock(sg, st) AND NOT ts OR st IS Stock AND NOT sg AND NOT ts

    ORDER BY          nameS
    FILTERGROUP filters
        FILTER 'Все листья' 'F10' isParentLeafStatisticGroupSku(g, s) DEFAULT
        FILTER 'Всех потомков' 'F9' isParentStatisticGroupSku(g, s)
        FILTER 'Только непосредственных потомков' 'F8' parentStatisticGroupTypeSku(c,s) == g

    PROPERTIES        balanceBSkuStockDate(s, st, dFrom),
                      quantitySoldSkuStockDateFromTo(s, st, dFrom, dTo),
                      balanceASkuStockDate(s, st, dTo)
    PROPERTIES  FORCE PANEL valueByStatisticGroupDateFromTo(g, ts, dFrom, dTo), valueResidentByStatisticGroupDateFromTo(g, ts, dFrom, dTo)
    PROPERTIES  FORCE PANEL valueByStatisticGroupDateTo(g, ts, dTo), valueResidentByStatisticGroupDateTo(g, ts, dTo)
;
@extendFormFilterStockAccess(Stock, st, statisticalReport);
@extendFormFilterStockAccess(Stock, ts, statisticalReport);
@extendFormFilterStockGroupAccess(StockGroup, sg, statisticalReport);

DESIGN statisticalReport FROM DEFAULT {
    main{
        NEW topContainer{
            type = SPLITH;
            fill = 1;
            NEW firstCase {
                type = SPLITV;
                fill = 1;
                ADD stockTree.tree.box { caption = 'Склады'; }
                ADD treeGroups.tree.box { caption = 'Статистические группы'; }
            }

            NEW secondCase {
                fill = 2;
                NEW wor {
                    type = CONTAINERH;
                    ADD dates.box;
                    ADD c.box {caption = 'Тип классификатора статистических групп';};
                }
                ADD sts.box {caption = 'Показатели по продажам в номинальных единицах';}
            }
        }
        NEW row {
            caption = 'Суммы';
            NEW row1 {
                type = CONTAINERH;
                caption = 'По отдел-группа, с учетом ед. изм. и коэфф. перевода';
                ADD PROPERTY(valueByStatisticGroupDateFromTo);
                ADD PROPERTY(valueResidentByStatisticGroupDateFromTo);
                ADD PROPERTY(valueByStatisticGroupDateTo);
                ADD PROPERTY(valueResidentByStatisticGroupDateTo);
            }
        }
    }
    ADD functions.box;
}

                ///////////////--------по регионам и компании----------/////////////////

                           //c коэффициентом пересчета за период//
// всего
quantitySoldByStatisticGroupRegionDateFromTo 'Продано, шт' (group, legalEntity, region, dateFrom, dateTo)=
    [GROUP SUM quantitySoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    isParentStatisticGroupSku(group, sku)
        BY group, legalEntityStock(stock), regionStock(stock), dateFrom, dateTo]
            (group, legalEntity, region, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightSoldByStatisticGroupRegionDateFromTo 'Продано, кг' (group, legalEntity, region, dateFrom, dateTo)=
    [GROUP SUM netWeightSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateFrom, dateTo]
        (group, legalEntity, region, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

volumeSoldByStatisticGroupRegionDateFromTo 'Продано, л' (group, legalEntity, region, dateFrom, dateTo)=
    [GROUP SUM volumeSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateFrom, dateTo]
        (group, legalEntity, region, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

retailSumSoldByStatisticGroupRegionDateFromTo 'Продано, руб.' (group, legalEntity, region, dateFrom, dateTo)=
    [GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateFrom, dateTo]
        (group, legalEntity, region, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

// отечест. производствава
quantitySoldResidentByStatisticGroupRegionDateFromTo 'Продано, шт' (group, legalEntity, region, dateFrom, dateTo)=
    [GROUP SUM quantitySoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
        BY group, legalEntityStock(stock), regionStock(stock), dateFrom, dateTo]
            (group, legalEntity, region, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightSoldResidentByStatisticGroupRegionDateFromTo 'Продано, кг' (group, legalEntity, region, dateFrom, dateTo)=
    [GROUP SUM netWeightSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateFrom, dateTo]
        (group, legalEntity, region, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

volumeSoldResidentByStatisticGroupRegionDateFromTo 'Продано, л' (group, legalEntity, region, dateFrom, dateTo)=
    [GROUP SUM volumeSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateFrom, dateTo]
        (group, legalEntity, region, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

retailSumSoldResidentByStatisticGroupRegionDateFromTo 'Продано, руб.' (group, legalEntity, region, dateFrom, dateTo)=
    [GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateFrom, dateTo]
        (group, legalEntity, region, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

                             //с коэффициентом пересчета на коцен//
// всего
balanceByStatisticGroupRegionDateTo 'Остаток на конец' (group, legalEntity, region, dateTo)=
    [GROUP SUM balanceASkuStockDate (sku, stock, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    isParentStatisticGroupSku(group, sku)
        BY group,legalEntityStock(stock), regionStock(stock), dateTo]
            (group, legalEntity, region, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightByStatisticGroupRegionDateTo 'Вес на конец, кг' (group, legalEntity, region, dateTo)=
    [GROUP SUM netWeightBalanceASkuLedgerDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateTo]
        (group, legalEntity, region, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

volumeByStatisticGroupRegionDateTo 'Объем на конец, л' (group, legalEntity, region, dateTo)=
    [GROUP SUM volumeBalanceASkuLedgerDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateTo]
        (group, legalEntity, region, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

retailSumByStatisticGroupRegionDateTo 'Сумма на конец, руб' (group, legalEntity, region, dateTo)=
    [GROUP SUM sumASkuStockDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateTo]
        (group, legalEntity, region, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
// белорусского производства
balanceResidentByStatisticGroupRegionDateTo 'Остаток на конец' (group, legalEntity, region, dateTo)=
    [GROUP SUM balanceASkuStockDate (sku, stock, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
        BY group, legalEntityStock(stock), regionStock(stock), dateTo]
            (group, legalEntity, region, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightResidentByStatisticGroupRegionDateTo 'Вес на конец, кг' (group, legalEntity, region, dateTo)=
    [GROUP SUM netWeightBalanceASkuLedgerDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateTo]
        (group, legalEntity, region, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

volumeResidentByStatisticGroupRegionDateTo 'Объем на конец, л' (group, legalEntity, region, dateTo)=
    [GROUP SUM volumeBalanceASkuLedgerDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateTo]
        (group, legalEntity, region, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

retailSumResidentByStatisticGroupRegionDateTo 'Сумма на конец, руб' (group, legalEntity, region, dateTo)=
    [GROUP SUM sumASkuStockDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateTo]
        (group, legalEntity, region, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

valueByStatisticGroupLegalEntityRegionDateFromTo 'Продано всего' (group, legalEntity, region, dateFrom, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN quantitySoldByStatisticGroupRegionDateFromTo(group, legalEntity, region, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightSoldByStatisticGroupRegionDateFromTo(group, legalEntity, region, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeSoldByStatisticGroupRegionDateFromTo(group, legalEntity, region, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumSoldByStatisticGroupRegionDateFromTo(group, legalEntity, region, dateFrom, dateTo)
        ELSE 0 IF group IS StatisticGroup AND legalEntity IS LegalEntity
    ;

valueByStatisticGroupLegalEntityRegionDateTo 'Остаток на конец всего' (group, legalEntity, region, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN balanceByStatisticGroupRegionDateTo(group, legalEntity, region, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightByStatisticGroupRegionDateTo(group, legalEntity, region, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeByStatisticGroupRegionDateTo(group, legalEntity, region, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumByStatisticGroupRegionDateTo(group, legalEntity, region, dateTo)
        ELSE 0 IF group IS StatisticGroup AND legalEntity IS LegalEntity AND region IS Region AND dateTo IS DATE
    ;

valueResidentByStatisticGroupLegalEntityRegionDateFromTo 'Продано отеч. пр-ва' (group, legalEntity, region, dateFrom, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN quantitySoldResidentByStatisticGroupRegionDateFromTo(group, legalEntity, region, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightSoldResidentByStatisticGroupRegionDateFromTo(group, legalEntity, region, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeSoldResidentByStatisticGroupRegionDateFromTo(group, legalEntity, region, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumSoldResidentByStatisticGroupRegionDateFromTo(group, legalEntity, region, dateFrom, dateTo)
        ELSE 0 IF group IS StatisticGroup AND legalEntity IS LegalEntity AND region IS Region
    ;

valueResidentByStatisticGroupLegalEntityRegionDateTo 'Остаток на конец отеч. пр-ва' (group, legalEntity, region, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN balanceResidentByStatisticGroupRegionDateTo(group, legalEntity, region, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightResidentByStatisticGroupRegionDateTo(group, legalEntity, region, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeResidentByStatisticGroupRegionDateTo(group, legalEntity, region, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumResidentByStatisticGroupRegionDateTo(group, legalEntity, region, dateTo)
        ELSE 0 IF group IS StatisticGroup AND legalEntity IS LegalEntity AND region IS Region AND dateTo IS DATE
    ;

totalRetailSumSoldByStatisticGroupRegionDateFromTo 'Итого продано, руб.' (group, legalEntity, region, dateFrom, dateTo)=
    GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), regionStock(stock), dateFrom, dateTo;

FORM torgSales 'Статистика (продажи) организация/регион/группа'

    OBJECTS params = (dFrom = DATE, dTo = DATE) FIXED PANEL
    PROPERTIES objFrom = OBJVALUE(dFrom), objTo = OBJVALUE(dTo)

    OBJECTS c = StatisticGroupType FIXED PANEL
    PROPERTIES SELECTOR nameStatisticGroupType(c)

    OBJECTS l=LegalEntity  FIXED PANEL
    PROPERTIES(l) SELECTOR nameLegalEntity

    OBJECTS r=Region  FIXED PANEL
    PROPERTIES(r) SELECTOR nameRegion

    TREE treeGroups g=StatisticGroup PARENT parentStatisticGroup
    PROPERTIES READONLY gname = nameStatisticGroup(g), sidStatisticGroup(g), nameUOMStatisticGroup(g)
    ORDER BY sidStatisticGroup

    FILTERS groupTypeStatisticGroup(g) == c

    PROPERTIES(g, l, r, dFrom, dTo) valueByStatisticGroupLegalEntityRegionDateFromTo, valueResidentByStatisticGroupLegalEntityRegionDateFromTo
    PROPERTIES(g, l, r, dTo) valueByStatisticGroupLegalEntityRegionDateTo, valueResidentByStatisticGroupLegalEntityRegionDateTo
    PROPERTIES(g, l, r, dFrom, dTo) totalRetailSumSoldByStatisticGroupRegionDateFromTo
;

DESIGN torgSales FROM DEFAULT {

    main{
        NEW firstCase BEFORE treeGroups.tree.box {
            caption = 'Параметры отчета';
            type = CONTAINERH;
            ADD c.box;
            NEW dateCase {
                caption = 'Даты';
                type = CONTAINERH;
                ADD PROPERTY(objFrom) {caption = 'Дата (с)';}
                ADD PROPERTY(objTo) {caption = 'Дата (по)';}
            }
            ADD l.box;
            ADD r.box;
        }
        ADD treeGroups.tree.box {caption = 'Показатели по стат. группам с учетом ед. изм. и коэфф. перевода';}
        ADD functions.box;
    }
}

//---------------------------------------------- Статотчет опта в соответствии с законодательством-----------------------------------------------------//

//------------------------------------- остатки и продажи по организациям-------------------------------------//
// всего
quantitySoldByStatisticGroupLegalEntityDateFromTo 'Продано, шт' (group, legalEntity, dateFrom, dateTo)=
    [GROUP SUM quantitySoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    isParentStatisticGroupSku(group, sku)
        BY group, legalEntityStock(stock), dateFrom, dateTo]
            (group, legalEntity, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightSoldByStatisticGroupLegalEntityDateFromTo 'Продано, кг' (group, legalEntity, dateFrom, dateTo)=
    [GROUP SUM netWeightSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateFrom, dateTo]
        (group, legalEntity, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

volumeSoldByStatisticGroupLegalEntityDateFromTo 'Продано, л' (group, legalEntity, dateFrom, dateTo)=
    [GROUP SUM volumeSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateFrom, dateTo]
        (group, legalEntity, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

retailSumSoldByStatisticGroupLegalEntityDateFromTo 'Продано, руб.' (group, legalEntity, dateFrom, dateTo)=
    [GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateFrom, dateTo]
        (group, legalEntity, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

// отечест. производствава
quantitySoldResidentByStatisticGroupLegalEntityDateFromTo 'Продано, шт' (group, legalEntity, dateFrom, dateTo)=
    [GROUP SUM quantitySoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
        BY group, legalEntityStock(stock), dateFrom, dateTo]
            (group, legalEntity, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightSoldResidentByStatisticGroupLegalEntityDateFromTo 'Продано, кг' (group, legalEntity, dateFrom, dateTo)=
    [GROUP SUM netWeightSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateFrom, dateTo]
        (group, legalEntity, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

volumeSoldResidentByStatisticGroupLegalEntityDateFromTo 'Продано, л' (group, legalEntity, dateFrom, dateTo)=
    [GROUP SUM volumeSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateFrom, dateTo]
        (group, legalEntity, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

retailSumSoldResidentByStatisticGroupLegalEntityDateFromTo 'Продано, руб.' (group, legalEntity, dateFrom, dateTo)=
    [GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateFrom, dateTo]
        (group, legalEntity, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

                             //с коэффициентом пересчета на коцен//
// всего
balanceByStatisticGroupLegalEntityDateTo 'Остаток на конец' (group, legalEntity, dateTo)=
    [GROUP SUM balanceASkuStockDate (sku, stock, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    isParentStatisticGroupSku(group, sku)
        BY group,legalEntityStock(stock), dateTo]
            (group, legalEntity, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightByStatisticGroupLegalEntityDateTo 'Вес на конец, кг' (group, legalEntity, dateTo)=
    [GROUP SUM netWeightBalanceASkuLedgerDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateTo]
        (group, legalEntity, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

volumeByStatisticGroupLegalEntityDateTo 'Объем на конец, л' (group, legalEntity, dateTo)=
    [GROUP SUM volumeBalanceASkuLedgerDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateTo]
        (group, legalEntity, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

retailSumByStatisticGroupLegalEntityDateTo 'Сумма на конец, руб' (group, legalEntity, dateTo)=
    [GROUP SUM sumASkuStockDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateTo]
        (group, legalEntity, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
// белорусского производства
balanceResidentByStatisticGroupLegalEntityDateTo 'Остаток на конец' (group, legalEntity, dateTo)=
    [GROUP SUM balanceASkuStockDate (sku, stock, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
        BY group, legalEntityStock(stock), dateTo]
            (group, legalEntity, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightResidentByStatisticGroupLegalEntityDateTo 'Вес на конец, кг' (group, legalEntity, dateTo)=
    [GROUP SUM netWeightBalanceASkuLedgerDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateTo]
        (group, legalEntity, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

volumeResidentByStatisticGroupLegalEntityDateTo 'Объем на конец, л' (group, legalEntity, dateTo)=
    [GROUP SUM volumeBalanceASkuLedgerDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateTo]
        (group, legalEntity, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

retailSumResidentByStatisticGroupLegalEntityDateTo 'Сумма на конец, руб' (group, legalEntity, dateTo)=
    [GROUP SUM sumASkuStockDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateTo]
        (group, legalEntity, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

valueByStatisticGroupLegalEntityDateFromTo 'Продано, ЕИ' (group, legalEntity, dateFrom, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN quantitySoldByStatisticGroupLegalEntityDateFromTo(group, legalEntity, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightSoldByStatisticGroupLegalEntityDateFromTo(group, legalEntity, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeSoldByStatisticGroupLegalEntityDateFromTo(group, legalEntity, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumSoldByStatisticGroupLegalEntityDateFromTo(group, legalEntity, dateFrom, dateTo)
        ELSE 0 IF group IS StatisticGroup AND legalEntity IS LegalEntity
    ;

valueByStatisticGroupLegalEntityDateFrom 'Остаток на начало, ЕИ' (group, legalEntity, dateFrom) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN balanceByStatisticGroupLegalEntityDateTo(group, legalEntity, dateFrom)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightByStatisticGroupLegalEntityDateTo(group, legalEntity, dateFrom)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeByStatisticGroupLegalEntityDateTo(group, legalEntity, dateFrom)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumByStatisticGroupLegalEntityDateTo(group, legalEntity, dateFrom)
        ELSE 0 IF group IS StatisticGroup AND legalEntity IS LegalEntity AND dateFrom IS DATE
    ;

valueResidentByStatisticGroupLegalEntityDateFrom 'В т.ч. отеч., ЕИ' (group, legalEntity, dateFrom) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN balanceResidentByStatisticGroupLegalEntityDateTo(group, legalEntity, dateFrom)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightResidentByStatisticGroupLegalEntityDateTo(group, legalEntity, dateFrom)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeResidentByStatisticGroupLegalEntityDateTo(group, legalEntity, dateFrom)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumResidentByStatisticGroupLegalEntityDateTo(group, legalEntity, dateFrom)
        ELSE 0 IF group IS StatisticGroup AND legalEntity IS LegalEntity AND dateFrom IS DATE
    ;

valueByStatisticGroupLegalEntityDateTo 'Остаток на конец, ЕИ' (group, legalEntity, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN balanceByStatisticGroupLegalEntityDateTo(group, legalEntity, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightByStatisticGroupLegalEntityDateTo(group, legalEntity, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeByStatisticGroupLegalEntityDateTo(group, legalEntity, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumByStatisticGroupLegalEntityDateTo(group, legalEntity, dateTo)
        ELSE 0 IF group IS StatisticGroup AND legalEntity IS LegalEntity AND dateTo IS DATE
    ;

valueResidentByStatisticGroupLegalEntityDateFromTo 'В т.ч. отеч., ЕИ' (group, legalEntity, dateFrom, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN quantitySoldResidentByStatisticGroupLegalEntityDateFromTo(group, legalEntity, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightSoldResidentByStatisticGroupLegalEntityDateFromTo(group, legalEntity, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeSoldResidentByStatisticGroupLegalEntityDateFromTo(group, legalEntity, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumSoldResidentByStatisticGroupLegalEntityDateFromTo(group, legalEntity, dateFrom, dateTo)
        ELSE 0 IF group IS StatisticGroup AND legalEntity IS LegalEntity
    ;

valueResidentByStatisticGroupLegalEntityDateTo 'В т.ч. отеч., ЕИ' (group, legalEntity, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN balanceResidentByStatisticGroupLegalEntityDateTo(group, legalEntity, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightResidentByStatisticGroupLegalEntityDateTo(group, legalEntity, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeResidentByStatisticGroupLegalEntityDateTo(group, legalEntity, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumResidentByStatisticGroupLegalEntityDateTo(group, legalEntity, dateTo)
        ELSE 0 IF group IS StatisticGroup AND legalEntity IS LegalEntity AND dateTo IS DATE
    ;

totalSumSoldByStatisticGroupLegalEntityDateFromTo 'Продано, руб.' (group, legalEntity, dateFrom, dateTo)=
    GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateFrom, dateTo;

totalSumResidentSoldByStatisticGroupLegalEntityDateFromTo 'В т.ч.отеч., руб.' (group, legalEntity, dateFrom, dateTo)=
    GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, legalEntityStock(stock), dateFrom, dateTo;

// суммовые показатели
sumBalanceByStatisticGroupLegalEntityDateFrom 'Сумма остатка на начало, руб.' (group, legalEntity, dateFrom) =
    GROUP SUM sumASkuStockDate (sku, stock, dateFrom) IF isParentStatisticGroupSku(group, sku)
    BY group,legalEntityStock(stock), dateFrom;

sumResidentBalanceByStatisticGroupLegalEntityDateFrom 'В т.ч.отеч., руб.' (group, legalEntity, dateFrom) =
    GROUP SUM sumASkuStockDate (sku, stock, dateFrom) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group,legalEntityStock(stock), dateFrom;

sumBalanceByStatisticGroupLegalEntityDateTo 'Сумма остатка на конец, руб.' (group, legalEntity, dateTo) =
    GROUP SUM sumASkuStockDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group,legalEntityStock(stock), dateTo;

sumResidentBalanceByStatisticGroupLegalEntityDateTo 'В т.ч.отеч., руб.' (group, legalEntity, dateTo) =
    GROUP SUM sumASkuStockDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group,legalEntityStock(stock), dateTo;


//residentStatisticGroupSku (group, sku) AND

FORM statisticalLegalEntityReport 'Статистический отчет по организации'

    OBJECTS params = (dFrom = DATE, dTo = DATE) FIXED PANEL
    PROPERTIES objFrom = OBJVALUE(dFrom), objTo = OBJVALUE(dTo)

    OBJECTS c = StatisticGroupType FIXED PANEL
    PROPERTIES SELECTOR nameStatisticGroupType(c)

    OBJECTS l=LegalEntity  FIXED PANEL
    PROPERTIES(l) SELECTOR nameLegalEntity

    TREE treeGroups g=StatisticGroup PARENT parentStatisticGroup
    PROPERTIES READONLY gname = nameStatisticGroup(g), sidStatisticGroup(g), nameUOMStatisticGroup(g)
    ORDER BY sidStatisticGroup

    FILTERS groupTypeStatisticGroup(g) == c

    PROPERTIES(g, l, dFrom) READONLY valueByStatisticGroupLegalEntityDateFrom, valueResidentByStatisticGroupLegalEntityDateFrom,
                                     sumBalanceByStatisticGroupLegalEntityDateFrom, sumResidentBalanceByStatisticGroupLegalEntityDateFrom
    PROPERTIES(g, l, dFrom, dTo) READONLY valueByStatisticGroupLegalEntityDateFromTo, valueResidentByStatisticGroupLegalEntityDateFromTo,
                                          totalSumSoldByStatisticGroupLegalEntityDateFromTo, totalSumResidentSoldByStatisticGroupLegalEntityDateFromTo
    PROPERTIES(g, l, dTo) READONLY valueByStatisticGroupLegalEntityDateTo, valueResidentByStatisticGroupLegalEntityDateTo,
                                   sumBalanceByStatisticGroupLegalEntityDateTo, sumResidentBalanceByStatisticGroupLegalEntityDateTo
;

DESIGN statisticalLegalEntityReport FROM DEFAULT {
    main{
        NEW firstCase BEFORE treeGroups.tree.box {
            caption = 'Параметры отчета';
            type = CONTAINERH;
            ADD c.box;
            NEW dateCase {
                caption = 'Даты';
                type = CONTAINERH;
                ADD PROPERTY(objFrom) {caption = 'Дата (с)';}
                ADD PROPERTY(objTo) {caption = 'Дата (по)';}
            }
            ADD l.box;
        }
        ADD functions.box;
    }
}

//------------------------------------- остатки и продажи по складу-------------------------------------//
// всего
quantitySoldByStatisticGroupStockDateFromTo 'Продано, шт' (group, stock, dateFrom, dateTo)=
    [GROUP SUM quantitySoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    isParentStatisticGroupSku(group, sku)
        BY group, stock, dateFrom, dateTo]
            (group, stock, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightSoldByStatisticGroupStockDateFromTo 'Продано, кг' (group, stock, dateFrom, dateTo)=
    [GROUP SUM netWeightSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo]
        (group, stock, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

volumeSoldByStatisticGroupStockDateFromTo 'Продано, л' (group, stock, dateFrom, dateTo)=
    [GROUP SUM volumeSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo]
        (group, stock, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

retailSumSoldByStatisticGroupStockDateFromTo 'Продано, руб.' (group, stock, dateFrom, dateTo)=
    [GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo]
        (group, stock, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

// отечест. производствава
quantitySoldResidentByStatisticGroupStockDateFromTo 'Продано, шт' (group, stock, dateFrom, dateTo)=
    [GROUP SUM quantitySoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
        BY group, stock, dateFrom, dateTo]
            (group, stock, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightSoldResidentByStatisticGroupStockDateFromTo 'Продано, кг' (group, stock, dateFrom, dateTo)=
    [GROUP SUM netWeightSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo]
        (group, stock, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

volumeSoldResidentByStatisticGroupStockDateFromTo 'Продано, л' (group, stock, dateFrom, dateTo)=
    [GROUP SUM volumeSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo]
        (group, stock, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

retailSumSoldResidentByStatisticGroupStockDateFromTo 'Продано, руб.' (group, stock, dateFrom, dateTo)=
    [GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo]
        (group, stock, dateFrom, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

                             //с коэффициентом пересчета на коцен//
// всего
balanceByStatisticGroupStockDateTo 'Остаток на конец' (group, stock, dateTo)=
    [GROUP SUM balanceASkuStockDate (sku, stock, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    isParentStatisticGroupSku(group, sku)
        BY group, stock, dateTo]
            (group, stock, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightByStatisticGroupStockDateTo 'Вес на конец, кг' (group, stock, dateTo)=
    [GROUP SUM netWeightBalanceASkuLedgerDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo]
        (group, stock, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

volumeByStatisticGroupStockDateTo 'Объем на конец, л' (group, stock, dateTo)=
    [GROUP SUM volumeBalanceASkuLedgerDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo]
        (group, stock, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

retailSumByStatisticGroupStockDateTo 'Сумма на конец, руб' (group, stock, dateTo)=
    [GROUP SUM sumASkuStockDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo]
        (group, stock, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));
// белорусского производства
balanceResidentByStatisticGroupStockDateTo 'Остаток на конец' (group, stock, dateTo)=
    [GROUP SUM balanceASkuStockDate (sku, stock, dateTo)/
    (OVERRIDE 1 IF group IS StatisticGroup AND sku IS Sku, factorGroupStaticUOM(unitMeasureStatisticGroup(group), UOMSku(sku))) IF
    residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
        BY group, stock, dateTo]
            (group, stock, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

netWeightResidentByStatisticGroupStockDateTo 'Вес на конец, кг' (group, stock, dateTo)=
    [GROUP SUM netWeightBalanceASkuLedgerDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo]
        (group, stock, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

volumeResidentByStatisticGroupStockDateTo 'Объем на конец, л' (group, stock, dateTo)=
    [GROUP SUM volumeBalanceASkuLedgerDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo]
        (group, stock, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

retailSumResidentByStatisticGroupStockDateTo 'Сумма на конец, руб' (group, stock, dateTo)=
    [GROUP SUM sumASkuStockDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo]
        (group, stock, dateTo) / (OVERRIDE 1 IF group IS StatisticGroup, conversionFactorStatisticGroup(group));

valueByStatisticGroupStockDateFromTo 'Продано, ЕИ' (group, stock, dateFrom, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN quantitySoldByStatisticGroupStockDateFromTo(group, stock, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightSoldByStatisticGroupStockDateFromTo(group, stock, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeSoldByStatisticGroupStockDateFromTo(group, stock, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumSoldByStatisticGroupStockDateFromTo(group, stock, dateFrom, dateTo)
        ELSE 0 IF group IS StatisticGroup AND stock IS Stock
    ;

valueByStatisticGroupStockDateFrom 'Остаток на начало, ЕИ' (group, stock, dateFrom) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN balanceByStatisticGroupStockDateTo(group, stock, dateFrom)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightByStatisticGroupStockDateTo(group, stock, dateFrom)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeByStatisticGroupStockDateTo(group, stock, dateFrom)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumByStatisticGroupStockDateTo(group, stock, dateFrom)
        ELSE 0 IF group IS StatisticGroup AND stock IS Stock AND dateFrom IS DATE
    ;

valueResidentByStatisticGroupStockDateFrom 'В т.ч. отеч., ЕИ' (group, stock, dateFrom) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN balanceResidentByStatisticGroupStockDateTo(group, stock, dateFrom)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightResidentByStatisticGroupStockDateTo(group, stock, dateFrom)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeResidentByStatisticGroupStockDateTo(group, stock, dateFrom)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumResidentByStatisticGroupStockDateTo(group, stock, dateFrom)
        ELSE 0 IF group IS StatisticGroup AND stock IS Stock AND dateFrom IS DATE
    ;

valueByStatisticGroupStockDateTo 'Остаток на конец, ЕИ' (group, stock, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN balanceByStatisticGroupStockDateTo(group, stock, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightByStatisticGroupStockDateTo(group, stock, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeByStatisticGroupStockDateTo(group, stock, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumByStatisticGroupStockDateTo(group, stock, dateTo)
        ELSE 0 IF group IS StatisticGroup AND stock IS Stock AND dateTo IS DATE
    ;

valueResidentByStatisticGroupStockDateFromTo 'В т.ч. отеч., ЕИ' (group, stock, dateFrom, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN quantitySoldResidentByStatisticGroupStockDateFromTo(group, stock, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightSoldResidentByStatisticGroupStockDateFromTo(group, stock, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeSoldResidentByStatisticGroupStockDateFromTo(group, stock, dateFrom, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumSoldResidentByStatisticGroupStockDateFromTo(group, stock, dateFrom, dateTo)
        ELSE 0 IF group IS StatisticGroup AND stock IS Stock
    ;

valueResidentByStatisticGroupStockDateTo 'В т.ч. отеч., ЕИ' (group, stock, dateTo) =
    CASE
        WHEN (unitMeasureStatisticGroup(group)==GroupStatic.statisticThing OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticLinearMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticPair OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticConditionalPiece OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticSquareMeters OR
             unitMeasureStatisticGroup(group)==GroupStatic.statisticCubicMeters)
            THEN balanceResidentByStatisticGroupStockDateTo(group, stock, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticPounds
            THEN netWeightResidentByStatisticGroupStockDateTo(group, stock, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticLiter
            THEN volumeResidentByStatisticGroupStockDateTo(group, stock, dateTo)
        WHEN unitMeasureStatisticGroup(group)==GroupStatic.statisticSum
            THEN retailSumResidentByStatisticGroupStockDateTo(group, stock, dateTo)
        ELSE 0 IF group IS StatisticGroup AND stock IS Stock AND dateTo IS DATE
    ;

totalSumSoldByStatisticGroupStockDateFromTo 'Продано, руб.' (group, stock, dateFrom, dateTo)=
    GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo;

totalSumResidentSoldByStatisticGroupStockDateFromTo 'В т.ч.отеч., руб.' (group, stock, dateFrom, dateTo)=
    GROUP SUM sumSoldSkuStockDateFromTo (sku, stock, dateFrom, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom, dateTo;

// суммовые показатели
sumBalanceByStatisticGroupStockDateFrom 'Сумма остатка на начало, руб.' (group, stock, dateFrom) =
    GROUP SUM sumASkuStockDate (sku, stock, dateFrom) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom;

sumResidentBalanceByStatisticGroupStockDateFrom 'В т.ч.отеч., руб.' (group, stock, dateFrom) =
    GROUP SUM sumASkuStockDate (sku, stock, dateFrom) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateFrom;

sumBalanceByStatisticGroupStockDateTo 'Сумма остатка на конец, руб.' (group, stock, dateTo) =
    GROUP SUM sumASkuStockDate (sku, stock, dateTo) IF isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo;

sumResidentBalanceByStatisticGroupStockDateTo 'В т.ч.отеч., руб.' (group, stock, dateTo) =
    GROUP SUM sumASkuStockDate (sku, stock, dateTo) IF residentStatisticGroupSku (group, sku) AND isParentStatisticGroupSku(group, sku)
    BY group, stock, dateTo;


//residentStatisticGroupSku (group, sku) AND

FORM statisticalStockReport 'Статистический отчет по складу'

    OBJECTS params = (dFrom = DATE, dTo = DATE) FIXED PANEL
    PROPERTIES objFrom = OBJVALUE(dFrom), objTo = OBJVALUE(dTo)

    OBJECTS c = StatisticGroupType FIXED PANEL
    PROPERTIES SELECTOR nameStatisticGroupType(c)

    OBJECTS s=Stock  FIXED PANEL
    PROPERTIES(s) SELECTOR nameStock

    TREE treeGroups g=StatisticGroup PARENT parentStatisticGroup
    PROPERTIES READONLY gname = nameStatisticGroup(g), sidStatisticGroup(g), nameUOMStatisticGroup(g)
    ORDER BY sidStatisticGroup

    FILTERS groupTypeStatisticGroup(g) == c

    PROPERTIES(g, s, dFrom) READONLY valueByStatisticGroupStockDateFrom, valueResidentByStatisticGroupStockDateFrom,
                                     sumBalanceByStatisticGroupStockDateFrom, sumResidentBalanceByStatisticGroupStockDateFrom
    PROPERTIES(g, s, dFrom, dTo) READONLY valueByStatisticGroupStockDateFromTo, valueResidentByStatisticGroupStockDateFromTo,
                                          totalSumSoldByStatisticGroupStockDateFromTo, totalSumResidentSoldByStatisticGroupStockDateFromTo
    PROPERTIES(g, s, dTo) READONLY valueByStatisticGroupStockDateTo, valueResidentByStatisticGroupStockDateTo,
                                   sumBalanceByStatisticGroupStockDateTo, sumResidentBalanceByStatisticGroupStockDateTo
;

DESIGN statisticalStockReport FROM DEFAULT {
    main{
        NEW firstCase BEFORE treeGroups.tree.box {
            caption = 'Параметры отчета';
            type = CONTAINERH;
            ADD c.box;
            NEW dateCase {
                caption = 'Даты';
                type = CONTAINERH;
                ADD PROPERTY(objFrom) {caption = 'Дата (с)';}
                ADD PROPERTY(objTo) {caption = 'Дата (по)';}
            }
            ADD s.box;
        }
        ADD functions.box;
    }
}


//---------------------------------------------- Автоматическое заполнение -----------------------------------------------------//

loadDefaultStatisticGroupType 'Добавить значение классификатора стат.групп' = ACTION (iname, isid, isidCountry) {
    FOR ADDOBJ t = StatisticGroupType DO {
        ASSIGN nameStatisticGroupType(t) <- iname;
        ASSIGN idStatisticGroupType (t) <- isid;
        ASSIGN countryStatisticGroupType(t) <- countrySID(isidCountry);
    }
}

loadDefaultStatisticGroup 'Добавить значение статистические группы' = ACTION (sidType, sidParent, iname, isid, groupStatic, value) {
    FOR ADDOBJ g = StatisticGroup DO {
        ASSIGN groupTypeStatisticGroup(g) <- typeIdStatisticGroupType(sidType);
        ASSIGN parentStatisticGroup(g) <- groupIdTypeIdGroup(sidType, sidParent);

        ASSIGN nameStatisticGroup(g) <- iname;
        ASSIGN sidStatisticGroup(g) <- isid;
        ASSIGN unitMeasureStatisticGroup(g) <- groupStatic;
        ASSIGN conversionFactorStatisticGroup(g) <- value;
    }
}

loadDefaultResidentCountry 'Добавить отеч. производ' = ACTION (idCountry, idCountry2)  {
    ASSIGN residentCountryCountry(a,b) <- TRUE WHERE a == countrySID(idCountry) AND b == countrySID(idCountry2);
}

loadDefaultStatisticGroups 'Загрузить стандартные статистические группы и классификатор' () = ABSTRACT ACTION LIST ()  IN loadDefaultGroup;
@implementLoadDefaultData(loadDefaultStatisticGroups);

NAVIGATOR {
    saleNavigator {
        NEW statisticsNavigator 'Статистика' BEFORE saleMasterData {
            ADD statisticGroupTypes;
            ADD statisticGroups;
            ADD groupStatics;
            ADD statisticalReport;
            ADD torgSales;
            ADD statisticalLegalEntityReport;
            ADD statisticalStockReport;
        }
    }
}