MODULE SaleStatisticsItemDescription;

REQUIRE SaleStatistics, ItemDescription;

NAMESPACE Sale;

TABLE groupStaticPackType (GroupStatic, PackType);
factor 'Коэффициент перевода (количество)' = DATA NUMERIC[14,3] (GroupStatic, PackType);

overFactor (GroupStatic groupStatic,Item sku) +=  factor(groupStatic, packType(sku));

EXTEND FORM groupStatics 
    OBJECTS p=PackType
    PROPERTIES   name(p) READONLY, factor(g,p)

    FILTERGROUP filters1
        FILTER 'Упаковка с коэфф.' factor(g,p) 'F10'
;

DESIGN groupStatics {
    MOVE BOX(g);
    NEW top {
        fill = 1;
        type = TABBED;
        MOVE BOX(u);
        MOVE BOX(p);
    }
    MOVE TOOLBARBOX;

}
