MODULE SaleStatisticsStore;

REQUIRE SaleStatistics, ZReport;

NAMESPACE Sale;

sumCard 'Продано с использованием банк. карточек' (DATE dateFrom, DATE dateTo) =
    GROUP SUM sumCard (Stock stock, DATE dateFrom, DATE dateTo) IF in(stock)
    BY dateFrom, dateTo;

sumSale 'Продано по кассе' (DATE dateFrom, DATE dateTo) =
    GROUP SUM sumSale (Stock stock, DATE dateFrom, DATE dateTo) IF in(stock)
    BY dateFrom, dateTo;

EXTEND FORM statisticalReportStockSelect
    PROPERTIES  FORCE PANEL sumCard(dFrom, dTo), sumSale(dFrom, dTo)

;

DESIGN statisticalReportStockSelect {
    bottom {
        NEW summa {
            caption = 'По выбранным складам';
            MOVE PROPERTY(sumCard(dFrom,dTo));
            MOVE PROPERTY(sumSale(dFrom,dTo));  
        } 
    }
}