MODULE StockAdjustmentOperation;

REQUIRE Operation, LegalEntity, Stock;

NAMESPACE Stock;

@defineOperation(' (изменение остатков)');

@defineOperationRole();
@extendFormFilterRole(o, dialogOperations);
//@extendFormFilterRole(o, operations);     //-- пока не нужен

DESIGN operation{
    tabContainer {
        NEW paramsContainer {
            caption = 'Параметры';
        }
    }
}
