MODULE PurchaseShipmentPriceSum;

REQUIRE PurchaseShipment;

NAMESPACE Purchase;

shipmentSum(Purchase.UserInvoiceDetail d) <- NUMERIC[18,4]((OVERRIDE costSum(d)/quantity(d), homePrice(d), price(d)) * shipmentQuantity(d))
    WHEN CHANGED(costSum(d)) OR CHANGED(quantity(d)) OR CHANGED(shipmentQuantity(d)) OR CHANGED(homePrice(d)) OR CHANGED(price(d));

shipmentPrice(Purchase.UserInvoiceDetail d) <- NUMERIC[16,4](OVERRIDE shipmentSum(d)/shipmentQuantity(d), homePrice(d), price(d))
    WHEN CHANGED(shipmentSum(d)) OR CHANGED(shipmentQuantity(d)) OR CHANGED(homePrice(d)) OR CHANGED(price(d));

