MODULE CurrencyDefaultRu;

REQUIRE CurrencyRu, CurrencyDefault;

NAMESPACE Currency;


// --------------------------------------------------- Стандартные значения ------------------------------------ //

loadDefaultCurrencyRu 'Добавить код' (BPSTRING[3] iShortName, BPSTRING[6] iExtraSID)  { 
    FOR Currency c == currencyShortName(iShortName) DO {
       extraSID(c) <- iExtraSID;
    }
}

loadDefaultCurrenciesRu 'Загрузить коды валют'()  { 
    defaultCurrency() <- currencyShortName('RUB');

    loadDefaultCurrencyRu('UAH', 'R01720');
    loadDefaultCurrencyRu('USD', 'R01235');
    loadDefaultCurrencyRu('EUR', 'R01239');
    loadDefaultCurrencyRu('PLN', 'R01565');
    loadDefaultCurrencyRu('LVL', 'R01405');
    loadDefaultCurrencyRu('LTL', 'R01435');
    loadDefaultCurrencyRu('BYN', 'R01090');
    loadDefaultCurrencyRu('GBP', 'R01035');
    loadDefaultCurrencyRu('CHF', 'R01775');
} IN loadDefault;

overLoadDefaultCurrencies() + {  loadDefaultCurrenciesRu(); }