MODULE StockDocumentWarehouse;

REQUIRE StockDocument, Warehouse;



//------------------------- Расширяем форму отдела -------------------------//

@extendStockFormStockDocumentLedger(warehouse, w) ;
EXTEND FORM warehouse
    PROPERTIES isResponsiblePersonStockEmployee(w,e) BEFORE deletee
;

DESIGN warehouse {
    headerRight {
        MOVE w.responsibility {
            type = COLUMNS;
            columns = 1;
        }
    }
}

