MODULE EquipmentCashRegister;

REQUIRE Equipment, CashRegisterPriceTransaction;

NAMESPACE Equipment;

EXTEND FORM groupCashRegister PROPERTIES(grc) nameEquipmentServer;
DESIGN groupCashRegister{
    topContainer{
        MOVE PROPERTY(nameEquipmentServer(grc)); 
    }
}
EXTEND FORM groupsCashRegister PROPERTIES(grc) READONLY nameEquipmentServer; 

//временная опция для Табака
disableSalesForClosedZReports 'Не принимать реализацию для закрытых Z-отчётов' = DATA BOOLEAN ();
EXTEND FORM options PROPERTIES() disableSalesForClosedZReports;
DESIGN options { machinery { MOVE PROPERTY(disableSalesForClosedZReports()); } }

overCopy(GroupCashRegister old, GroupCashRegister new ) + {  equipmentServer(new ) <- equipmentServer(old AS GroupCashRegister) WHERE new IS GroupCashRegister; } 

loadDefaultCashRegisterModels() + { 
    EXEC loadDefaultCashRegisterModel('Кассы Atol', 'Atol', 'equ.clt.handler.atol.AtolHandler', NULL, NULL, NULL, NULL);
    EXEC loadDefaultCashRegisterModel('Кассы Kristal', 'Kristal', 'equ.clt.handler.kristal.KristalHandler', NULL, NULL, NULL, NULL);
    EXEC loadDefaultCashRegisterModel('Кассы Kristal 10', 'Kristal10', 'equ.clt.handler.kristal10.Kristal10Handler', NULL, NULL, NULL, NULL);
    EXEC loadDefaultCashRegisterModel('Кассы Maxishop', 'Maxishop', 'equ.clt.handler.maxishop.MaxishopHandler', NULL, NULL, NULL, NULL);
    EXEC loadDefaultCashRegisterModel('Кассы UKM4', 'Ukm4', 'equ.clt.handler.ukm4.UKM4Handler', NULL, NULL, NULL, NULL);
    EXEC loadDefaultCashRegisterModel('Кассы UKM4 MySQL', 'Ukm4-mysql', 'equ.clt.handler.ukm4mysql.UKM4MySQLHandler', TRUE, NULL, NULL, NULL);
    EXEC loadDefaultCashRegisterModel('Кассы HTC', 'HTC', 'equ.clt.handler.htc.HTCHandler', NULL, NULL, NULL, NULL);
    EXEC loadDefaultCashRegisterModel('Кассы BelCoopSoyuz', 'BelCoopSoyuz', 'equ.clt.handler.belcoopsoyuz.BelCoopSoyuzHandler', TRUE, NULL, NULL, NULL);
    EXEC loadDefaultCashRegisterModel('Кассы BelCoopSoyuz SQL', 'BelCoopSoyuzSQL', 'equ.clt.handler.belcoopsoyuz.BelCoopSoyuzSQLHandler', TRUE, NULL, NULL, NULL);
    EXEC loadDefaultCashRegisterModel('Кассовый сервер Astron', 'Astron', 'equ.clt.handler.astron.AstronHandler', NULL, NULL, TRUE, NULL);
    EXEC loadDefaultCashRegisterModel('Кассовый сервер Astron (TEMP)', 'Astron', 'equ.clt.handler.astron.AstronTempHandler', NULL, NULL, TRUE, NULL); //TODO: удалить, когда закончится переход
    EXEC loadDefaultCashRegisterModel('Кассовый сервер EQS', 'EQS', 'equ.clt.handler.eqs.EQSHandler', NULL, NULL, NULL, NULL);
    EXEC loadDefaultCashRegisterModel('Кассовый сервер Artix', 'Artix', 'equ.clt.handler.artix.ArtixHandler', NULL, NULL, TRUE, TRUE );
    EXEC loadDefaultCashRegisterModel('Кассовый сервер Dreamkas', 'Dreamkas', 'equ.clt.handler.dreamkas.DreamkasHandler', NULL, NULL, TRUE, TRUE);
};

processReceiptDetailExtraFields(STRING json) {
}