MODULE PriceListLedgerItem;

REQUIRE PriceListLedger, Item;

NAMESPACE PriceList;

showPriceListLedgerStock 'Показать изменение цены товара по складу' (Sku sku) = { SHOW movementPriceSkuStock OBJECTS s = sku; }  CONTEXTMENU nameAttribute[Item];
showPriceListLedger 'Показать изменение цены товара' (Sku sku) = { SHOW movementPriceSkuStocks OBJECTS s = sku; }  CONTEXTMENU nameAttribute[Item];
