MODULE PriceListPromotion;

REQUIRE PriceListOperation;

NAMESPACE PriceList;

promotionPriceListOperation = DATA Operation();
namePromotionPriceListOperation 'Операция акции' = name(promotionPriceListOperation());

promotionPriceListTypeOperation = DATA DataPriceListType();
namePromotionPriceListTypeOperation 'Вид цены акции' = name(promotionPriceListTypeOperation());


EXTEND FORM options
    PROPERTIES() namePromotionPriceListOperation, namePromotionPriceListTypeOperation 
;
DESIGN options {
    price {
        MOVE PROPERTY(namePromotionPriceListOperation());
        MOVE PROPERTY(namePromotionPriceListTypeOperation());
    }
}   

promotionPriceListDetailA (Sku sku, Stock stock, DATETIME dateTime) =
    lastPriceListDetailA(promotionPriceListTypeOperation(), sku, stock, dateTime, promotionPriceListOperation());
    
promotionPriceListDetailA (Sku sku, Stock stock) = 
    promotionPriceListDetailA(sku, stock, currentDateTime());
    
inPromotionPriceListDetailA 'В акции' (Sku sku, Stock stock) =
    TRUE IF promotionPriceListDetailA(sku, stock);