MODULE PriceListExtraUOM;

REQUIRE PriceList, LegalEntityExtraUOM;

NAMESPACE PriceList;

shortNameExtraUOMSku 'Ед. изм. поставщика' (PriceListDetail detail)= shortName(extraUOM(company(detail), sku(detail)));

showExtraUOM(UserPriceListDetail detail) = extraUOM(company(detail), sku(detail));

EXTEND FORM userPriceList
    PROPERTIES(d) READONLY SHOWIF showExtraUOM(d) shortNameExtraUOMSku BEFORE shortNameUOMSku(d)
;

EXTEND FORM priceLists
    PROPERTIES(d) READONLY SHOWIF showExtraUOM(d) shortNameExtraUOMSku BEFORE shortNameUOMSku(d)
;