MODULE SaleOperationConsignmentBy;

REQUIRE SaleOperation, OperationConsignmentBy;

NAMESPACE Sale;

@defineOperationConsignment();
isInvoicePriceConsignmentOperation 'Печатать в качестве цены цену с НДС' = DATA BOOLEAN (Operation);

EXTEND FORM operation
    PROPERTIES isInvoicePriceConsignmentOperation(o)
;

DESIGN operation {
    consignment {
        MOVE PROPERTY(isInvoicePriceConsignmentOperation(o));
    }
}