MODULE ProductionOrderWorkshopSku;

REQUIRE ProductionOrderSku, ProductionOrderWorkshop;

NAMESPACE Production;

fillNegativeBalanceWorkshopProductDetail 'Добавить строки с отрицательным остатком' (Order o) {
    fillNegativeBalanceProductDetail(o, skuGroup(workshopStock(o)));
}

@defineOperationProperty(showFillNegativeBalance, 'Показывать кнопку добавления строк с отриц. остатком', BOOLEAN, showContainer);

EXTEND FORM order PROPERTIES fillNegativeBalanceWorkshopProductDetail(o) SHOWIF showFillNegativeBalance(operation(o)) DRAW pd TOOLBAR;