MODULE EGAISProductType;

REQUIRE EGAIS;

NAMESPACE EGAIS;

CLASS ProductType 'Вид продукции ЕГАИС';
TABLE productType (ProductType);

id 'Код' = DATA STRING[3] (ProductType);
productType = GROUP AGGR ProductType t BY id(t);

name 'Наименование' = DATA ISTRING (ProductType) CHARWIDTH 25;

FORM productType 'Вид продукции ЕГАИС'
    OBJECTS o = ProductType PANEL
    PROPERTIES(o) name, id
    
    EDIT ProductType OBJECT o
;

FORM productTypes 'Вид продукции ЕГАИС'
    OBJECTS o = ProductType
    PROPERTIES(o) READONLY name, id
    PROPERTIES(o) NEWSESSION NEW, EDIT, DELETE
;

FORM dialogProductTypes 'Вид продукции ЕГАИС'
    OBJECTS o = ProductType
    PROPERTIES(o) READONLY name, id
    
    LIST ProductType OBJECT o
;

NAVIGATOR {
    EGAISMasterData {
        NEW productTypes;
    }
}

onStarted() + {
    IF NOT GROUP SUM 1 IF t IS ProductType THEN {
        NEWSESSION {
            NEW t = ProductType { id(t) <- '10'; name(t) <- 'Спирт-сырец этиловый из пищевого сырья'; }
            NEW t = ProductType { id(t) <- '20'; name(t) <- 'Спирт этиловый ректификованный из пищевого сырья'; }
            NEW t = ProductType { id(t) <- '25'; name(t) <- 'Спирт этиловый ректификованный из непищевого растительного сырья'; }
            NEW t = ProductType { id(t) <- '30'; name(t) <- 'Спирт этиловый из ЭАФ **'; }
            NEW t = ProductType { id(t) <- '31'; name(t) <- 'Спирт этиловый из головной фракции этилового спирта'; }
            NEW t = ProductType { id(t) <- '40'; name(t) <- 'Спирт этиловый синтетический'; }
            NEW t = ProductType { id(t) <- '50'; name(t) <- 'Спирт этиловый абсолютированный'; }
            NEW t = ProductType { id(t) <- '60'; name(t) <- 'Другие спирты за исключением денатурированных (гидролизный, технический и другие)'; }
            NEW t = ProductType { id(t) <- '70'; name(t) <- 'Спирт этиловый денатурированный из пищевого сырья'; }
            NEW t = ProductType { id(t) <- '71'; name(t) <- 'Биоэтанол из пищевого сырья'; }
            NEW t = ProductType { id(t) <- '80'; name(t) <- 'Спирт этиловый денатурированный из непищевого сырья'; }
            NEW t = ProductType { id(t) <- '81'; name(t) <- 'Биоэтанол из непищевого сырья'; }
            NEW t = ProductType { id(t) <- '90'; name(t) <- 'Фракция головная этилового спирта'; }
            NEW t = ProductType { id(t) <- '91'; name(t) <- 'Фракция головных и промежуточных примесей этилового спирта'; }
            NEW t = ProductType { id(t) <- '92'; name(t) <- 'Промежуточная фракция этилового спирта из пищевого сырья'; }
            NEW t = ProductType { id(t) <- '100'; name(t) <- 'Спирт этиловый по фармакопейным статьям'; }
            NEW t = ProductType { id(t) <- '110'; name(t) <- 'Коньячный дистиллят'; }
            NEW t = ProductType { id(t) <- '120'; name(t) <- 'Кальвадосный дистиллят'; }
            NEW t = ProductType { id(t) <- '130'; name(t) <- 'Винный дистиллят'; }
            NEW t = ProductType { id(t) <- '140'; name(t) <- 'Спирт этиловый питьевой *'; }
            NEW t = ProductType { id(t) <- '150'; name(t) <- 'Виноградный дистиллят'; }
            NEW t = ProductType { id(t) <- '160'; name(t) <- 'Плодовый дистиллят **'; }
            NEW t = ProductType { id(t) <- '161'; name(t) <- 'Фруктовый (плодовый) дистиллят'; }
            NEW t = ProductType { id(t) <- '170'; name(t) <- 'Висковый дистиллят'; }
            NEW t = ProductType { id(t) <- '180'; name(t) <- 'Зерновой дистиллят'; }
            NEW t = ProductType { id(t) <- '190'; name(t) <- 'Другие дистилляты'; }
            NEW t = ProductType { id(t) <- '200'; name(t) <- 'Водка'; }
            NEW t = ProductType { id(t) <- '211'; name(t) <- 'Ликероводочные изделия с содержанием этилового спирта до 25% включительно'; }
            NEW t = ProductType { id(t) <- '212'; name(t) <- 'Ликероводочные изделия с содержанием этилового спирта свыше 25%'; }
            NEW t = ProductType { id(t) <- '229'; name(t) <- 'Коньяк и арманьяк, реализуемые в бутылках'; }
            NEW t = ProductType { id(t) <- '230'; name(t) <- 'Коньяки, реализуемые в бутылках *'; }
            NEW t = ProductType { id(t) <- '231'; name(t) <- 'Коньяки обработанные, предназначенные для отгрузки с целью розлива на других предприятиях или промпереработки'; }
            NEW t = ProductType { id(t) <- '232'; name(t) <- 'Бренди'; }
            NEW t = ProductType { id(t) <- '233'; name(t) <- 'Коньяк с защищенным географическим указанием'; }
            NEW t = ProductType { id(t) <- '234'; name(t) <- 'Коньяк с защищенным наименованием места происхождения'; }
            NEW t = ProductType { id(t) <- '235'; name(t) <- 'Коньяк коллекционный'; }
            NEW t = ProductType { id(t) <- '236'; name(t) <- 'Ромы'; }
            NEW t = ProductType { id(t) <- '237'; name(t) <- 'Виски'; }
            NEW t = ProductType { id(t) <- '238'; name(t) <- 'Напитки коньячные с содержанием этилового спирта до 25% включительно **'; }
            NEW t = ProductType { id(t) <- '239'; name(t) <- 'Напитки коньячные с содержанием этилового спирта свыше 25% **'; }
            NEW t = ProductType { id(t) <- '241'; name(t) <- 'Напитки коньячные, бренди с содержанием этилового спирта до 25% включительно *'; }
            NEW t = ProductType { id(t) <- '242'; name(t) <- 'Напитки коньячные, бренди с содержанием этилового спирта свыше 25% *'; }
            NEW t = ProductType { id(t) <- '250'; name(t) <- 'Напитки винные с содержанием этилового спирта до 25% включительно *'; }
            NEW t = ProductType { id(t) <- '251'; name(t) <- 'Напитки винные с содержанием этилового спирта свыше 25% *'; }
            NEW t = ProductType { id(t) <- '252'; name(t) <- 'Кальвадос'; }
            NEW t = ProductType { id(t) <- '260'; name(t) <- 'Слабоалкогольная продукция'; }
            NEW t = ProductType { id(t) <- '261'; name(t) <- 'Сидр'; }
            NEW t = ProductType { id(t) <- '262'; name(t) <- 'Пуаре'; }
            NEW t = ProductType { id(t) <- '263'; name(t) <- 'Медовуха (медовые напитки)'; }
            NEW t = ProductType { id(t) <- '270'; name(t) <- 'Другие спиртные напитки с содержанием этилового спирта до 25% включительно'; }
            NEW t = ProductType { id(t) <- '280'; name(t) <- 'Другие спиртные напитки с содержанием этилового спирта свыше 25%'; }
            NEW t = ProductType { id(t) <- '300'; name(t) <- 'Коньячные спирты *'; }
            NEW t = ProductType { id(t) <- '310'; name(t) <- 'Кальвадосные спирты *'; }
            NEW t = ProductType { id(t) <- '320'; name(t) <- 'Виноматериалы *'; }
            NEW t = ProductType { id(t) <- '321'; name(t) <- 'Виноматериалы виноградные'; }
            NEW t = ProductType { id(t) <- '322'; name(t) <- 'Виноматериалы фруктовые (плодовые)'; }
            NEW t = ProductType { id(t) <- '323'; name(t) <- 'Специальные виноматериалы виноградные'; }
            NEW t = ProductType { id(t) <- '324'; name(t) <- 'Специальные виноматериалы фруктовые (плодовые)'; }
            NEW t = ProductType { id(t) <- '330'; name(t) <- 'Соки спиртованные'; }
            NEW t = ProductType { id(t) <- '331'; name(t) <- 'Соки сброженно-спиртованные'; }
            NEW t = ProductType { id(t) <- '340'; name(t) <- 'Дистилляты *'; }
            NEW t = ProductType { id(t) <- '341'; name(t) <- 'Фруктовое сусло'; }
            NEW t = ProductType { id(t) <- '342'; name(t) <- 'Медовое сусло'; }
            NEW t = ProductType { id(t) <- '343'; name(t) <- 'Пивное сусло'; }
            NEW t = ProductType { id(t) <- '344'; name(t) <- 'Виноградное сусло'; }
            NEW t = ProductType { id(t) <- '345'; name(t) <- 'Спиртованное виноградное сусло (мистель)'; }
            NEW t = ProductType { id(t) <- '346'; name(t) <- 'Спиртованное фруктовое сусло'; }
            NEW t = ProductType { id(t) <- '350'; name(t) <- 'Другая спиртосодержащая пищевая продукция'; }
            NEW t = ProductType { id(t) <- '400'; name(t) <- 'Вина натуральные *'; }
            NEW t = ProductType { id(t) <- '401'; name(t) <- 'Вино (виноградное)'; }
            NEW t = ProductType { id(t) <- '402'; name(t) <- 'Вино с защищенным географическим указанием или с защищенным наименованием места происхождения **'; }
            NEW t = ProductType { id(t) <- '403'; name(t) <- 'Вино (виноградное столовое)'; }
            NEW t = ProductType { id(t) <- '404'; name(t) <- 'Вино с защищенным географическим указанием'; }
            NEW t = ProductType { id(t) <- '405'; name(t) <- 'Вино с защищенным наименованием места происхождения'; }
            NEW t = ProductType { id(t) <- '406'; name(t) <- 'Вино коллекционное виноградное'; }
            NEW t = ProductType { id(t) <- '410'; name(t) <- 'Вина (за исключением натуральных, игристых и шампанских) *'; }
            NEW t = ProductType { id(t) <- '411'; name(t) <- 'Ликерное вино'; }
            NEW t = ProductType { id(t) <- '412'; name(t) <- 'Ликерное вино с защищенным географическим указанием'; }
            NEW t = ProductType { id(t) <- '413'; name(t) <- 'Ликерное вино с защищенным наименованием места происхождения'; }
            NEW t = ProductType { id(t) <- '414'; name(t) <- 'Вино (столовое) с защищенным географическим указанием'; }
            NEW t = ProductType { id(t) <- '415'; name(t) <- 'Вино (столовое) с защищенным наименованием места происхождения'; }
            NEW t = ProductType { id(t) <- '416'; name(t) <- 'Вино (столовое) коллекционное'; }
            NEW t = ProductType { id(t) <- '420'; name(t) <- 'Вина плодовые *'; }
            NEW t = ProductType { id(t) <- '421'; name(t) <- 'Фруктовое (плодовое) вино'; }
            NEW t = ProductType { id(t) <- '422'; name(t) <- 'Вино коллекционное фруктовое'; }
            NEW t = ProductType { id(t) <- '430'; name(t) <- 'Вино специальное с защищенным географическим указанием'; }
            NEW t = ProductType { id(t) <- '431'; name(t) <- 'Вино специальное с защищенным наименованием места происхождения'; }
            NEW t = ProductType { id(t) <- '432'; name(t) <- 'Вино ароматизированное виноградное'; }
            NEW t = ProductType { id(t) <- '440'; name(t) <- 'Вина игристые'; }
            NEW t = ProductType { id(t) <- '441'; name(t) <- 'Вина игристые с защищенным географическим указанием'; }
            NEW t = ProductType { id(t) <- '442'; name(t) <- 'Вина игристые с защищенным наименованием места происхождения'; }
            NEW t = ProductType { id(t) <- '443'; name(t) <- 'Вина игристые коллекционные'; }
            NEW t = ProductType { id(t) <- '450'; name(t) <- 'Вина шампанские'; }
            NEW t = ProductType { id(t) <- '451'; name(t) <- 'Вина шампанские с защищенным географическим указанием'; }
            NEW t = ProductType { id(t) <- '452'; name(t) <- 'Вина шампанские с защищенным наименованием места происхождения'; }
            NEW t = ProductType { id(t) <- '453'; name(t) <- 'Вина шампанские коллекционные'; }
            NEW t = ProductType { id(t) <- '460'; name(t) <- 'Другие вина *'; }
            NEW t = ProductType { id(t) <- '461'; name(t) <- 'Винный напиток, произведенный без добавления этилового спирта'; }
            NEW t = ProductType { id(t) <- '462'; name(t) <- 'Винный напиток, произведенный с добавлением этилового спирта'; }
            NEW t = ProductType { id(t) <- '481'; name(t) <- 'Парфюмерно-косметическая продукция'; }
            NEW t = ProductType { id(t) <- '482'; name(t) <- 'Товары бытовой химии'; }
            NEW t = ProductType { id(t) <- '483'; name(t) <- 'Спиртосодержащие растворы'; }
            NEW t = ProductType { id(t) <- '484'; name(t) <- 'Другая спиртосодержащая непищевая продукция'; }
            NEW t = ProductType { id(t) <- '485'; name(t) <- 'Денатурированная спиртосодержащая непищевая продукция'; }
            NEW t = ProductType { id(t) <- '500'; name(t) <- 'Пиво с содержанием объемной доли этилового спирта свыше 0,5% и до 8,6% включительно'; }
            NEW t = ProductType { id(t) <- '510'; name(t) <- 'Пиво с содержанием объемной доли этилового спирта свыше 8,6%'; }
            NEW t = ProductType { id(t) <- '520'; name(t) <- 'Напитки, изготавливаемые на основе пива'; }
            APPLY;
        }
    }
}
