MODULE RepricingManufacturingPrice;

REQUIRE Repricing, PriceListLedger;

@defineDocumentInterfaceDetailPriceCustomPrefix(repricingDetail, manufacturing, ' изготовителя после');

@defineDocumentInterfaceDetailPriceCustomPrefix(repricingDetail, curManufacturing, ' изготовителя до');
//@deriveDocumentDetailPriceSystemLedgerPriceListType(userRepricing, manufacturingPriceStockPriceListType, curManufacturing, sku, departmentStore);
@deriveDocumentDetailPriceSystemLedgerPriceListTypeBatch (userRepricing, manufacturingPriceStockPriceListType, curManufacturing, sku, departmentStore);

overManagementRepricing(detail, sku, department, time) += ACTION (detail, sku, department, time) {
    manufacturingPriceUserRepricingDetail(detail) <- prevPriceBPriceListTypeSkuStockDateTime(SystemLedgerPriceListType.manufacturingPriceStockPriceListType, sku, department, time);
}

@changeDocumentDetailPricePrefix(userRepricingDetail, curManufacturing, cur, cur, curManufacturing, cur, curRetail);
@changeDocumentDetailPricePrefix(userRepricingDetail, manufacturing, newRetail, , manufacturing, , retail);

overRepricingPriceUserRepricingDetail(detail) += manufacturingPriceUserRepricingDetail(detail);
overCurRepricingPriceUserRepricingDetail(detail) += curManufacturingPriceUserRepricingDetail(detail);

EXTEND FORM userRepricing
    PROPERTIES(d) manufacturingPriceUserRepricingDetail ON CHANGE changeManufacturingPriceUserRepricingDetail(d) BEFORE priceUserRepricingDetail(d),
                  curManufacturingPriceUserRepricingDetail ON CHANGE changeCurManufacturingPriceUserRepricingDetail(d) BEFORE curPriceUserRepricingDetail(d)

;
EXTEND DESIGN userRepricing{
    PROPERTY(manufacturingPriceUserRepricingDetail(d)) { background = #FFFFCC; }
}

EXTEND FORM repricings
    PROPERTIES(d) READONLY manufacturingPriceRepricingDetail BEFORE priceRepricingDetail(d), curManufacturingPriceRepricingDetail BEFORE curPriceRepricingDetail(d)
;

overChangePriceUserRepricing(userRepricingDetail) += ACTION (userRepricingDetail) {
    ASSIGN manufacturingPriceUserRepricingDetail(userRepricingDetail) <- curManufacturingPriceUserRepricingDetail(userRepricingDetail);
}

