MODULE SalePurchaseInvoiceFuelMatch;

REQUIRE SalePurchaseInvoiceFuel, ItemFuelLtrMatch, SaleShipmentFuel, PurchaseShipment, PurchaseInvoiceFuelLtr, Store, ExtraPack;

PRIORITY Sale;

NAMESPACE SalePurchaseInvoice;

// замена товара при перемещении из опта в розницу 
overFillInvoice(Purchase.UserInvoiceDetail pd, InvoiceDetail sd) + {
    IF supplierStock(sd) IS Warehouse AND customerStock(sd) IS DepartmentStore AND isFuel(sku(sd)) THEN {
        sku(pd) <- itemFuelLtr(sku(sd));
        quantity(pd) <- round(volume(sd), roundFuelQuantityLtr());
        packQuantity(pd) <- quantity(sd) IF extraPack(supplier(sd), itemFuelLtr(sku(sd)));
        weight(pd) <- NUMERIC[11,5](round(quantity(sd) * coeffFuel(), roundFuelQuantityLtr()));
        shipmentQuantity(pd) <- round(shipmentVolume(sd), roundFuelQuantityLtr());
        sum(pd) <- sum(sd);
        price(pd) <- IF extraPack(supplier(sd), itemFuelLtr(sku(sd))) THEN price(sd) ELSE round2(sum(sd) / volume(sd));
        invoiceSum(pd) <- invoiceSum(sd);
        invoicePrice(pd) <- IF extraPack(supplier(sd), itemFuelLtr(sku(sd))) THEN invoicePrice(sd) ELSE round2(invoiceSum(sd) / volume(sd));
    }
}

setPropertiesPurchaseSale(Purchase.UserInvoiceDetail pd, InvoiceDetail sd) + {
    IF supplierStock(sd) IS Warehouse AND customerStock(sd) IS DepartmentStore AND isFuel(sku(sd)) THEN {
        sku(pd) <- itemFuelLtr(sku(sd));
        quantity(pd) <- round(volume(sd), roundFuelQuantityLtr());
        packQuantity(pd) <- quantity(sd) IF extraPack(supplier(sd), itemFuelLtr(sku(sd)));
        weight(pd) <- NUMERIC[11,5](round(quantity(sd) * coeffFuel(), roundFuelQuantityLtr()));
        shipmentQuantity(pd) <- round(shipmentVolume(sd), roundFuelQuantityLtr());
        sum(pd) <- sum(sd);
        price(pd) <- IF extraPack(supplier(sd), itemFuelLtr(sku(sd))) THEN price(sd) ELSE round2(sum(sd) / volume(sd));
        invoiceSum(pd) <- invoiceSum(sd);
        invoicePrice(pd) <- IF extraPack(supplier(sd), itemFuelLtr(sku(sd))) THEN invoicePrice(sd) ELSE round2(invoiceSum(sd) / volume(sd));
    }
}
