MODULE StockArticle;

REQUIRE Stock, ItemArticle;

NAMESPACE Stock;

balanceB 'Остаток на начало дня' (article, stock, date) = GROUP SUM balanceB(Item sku,Stock stock,DATE date) BY article(sku), stock, date;
balanceA 'Остаток на конец дня' (article, stock, date) = GROUP SUM balanceA(Item sku,Stock stock,DATE date) BY article(sku), stock, date;

defaultSku 'Товар по умолчанию' (article, stock)= GROUP MIN Item sku IF currentBalance(sku, Stock stock)
                                                                BY article(sku), stock;
                                                                
defaultSku 'Товар по умолчанию' (article)= GROUP MIN Item sku IF currentBalance(sku, Stock stock)
                                                                BY article(sku);                                                                

currentBalance 'Текущий остаток' (article, stock) = GROUP SUM currentBalance(Item sku,Stock stock) BY article(sku), stock;
prevCurrentBalance 'Текущий остаток' (Article article, Stock stock) = PREV(currentBalance(article, stock));
prevCurrentBalance 'Текущий остаток' (article) = GROUP SUM prevCurrentBalance(Article article, Stock stock) BY article;

currentBalance 'Текущий остаток' (article, color, size, stock)= GROUP SUM currentBalance(Item sku, Stock stock)
    BY article(sku), calcColor(sku), calcSize(sku), stock;
prevCurrentBalance 'Текущий остаток' (Article article, Color color, Size size, Stock stock)= PREV(currentBalance(article, color, size, stock));

currentBalance 'Текущий остаток' (skuGroup, stock) = GROUP SUM currentBalance(Sku sku,Stock stock) BY skuGroup(sku), stock;
recCurrentBalance 'Текущий остаток' (skuGroup, stock) = GROUP SUM currentBalance(SkuGroup group, Stock stock) IF isParent(group, SkuGroup parent) 
    BY parent, stock;

quantity (article, stock, date) = GROUP SUM quantity(Item sku,Stock stock,DATE date) BY article(sku), stock, date; 
signedQuantity (article, stock, date) = GROUP SUM signedQuantity(Item sku,Stock stock,DATE date) BY article(sku), stock, date; 
