MODULE ImportEuroopt;

REQUIRE System, Item, ItemDescription, ItemNutrition, ImportUserPriceList, PurchasePack;

importEurooptAction 'Импортировать' = ACTION CUSTOM 'lsfusion.erp.region.by.euroopt.ImportEurooptActionProperty' ();
importEurooptUseTor 'Использовать Tor' = DATA BOOLEAN();
importEurooptSkipKeys 'Не создавать новые товары' = DATA BOOLEAN();
importEurooptItems 'Импортировать товары' = DATA BOOLEAN();
importEurooptOnlyImages 'Только изображения' = DATA BOOLEAN();
importEurooptUserPriceLists 'Импортировать прайс-листы' = DATA BOOLEAN();

idItemGroupBarcode 'Код группы товаров' (barcode) = idSkuGroup(skuGroupSku(skuBarcode(barcode)));

EXTEND FORM integrationData
    PROPERTIES() importEurooptAction, importEurooptUseTor, importEurooptSkipKeys, importEurooptItems, importEurooptOnlyImages, importEurooptUserPriceLists
;
DESIGN integrationData {
    pane {
        NEW euroopt {
            caption = 'Евроопт';
            MOVE PROPERTY(importEurooptAction());
            MOVE PROPERTY(importEurooptUseTor());
            MOVE PROPERTY(importEurooptSkipKeys());
            MOVE PROPERTY(importEurooptItems());
            MOVE PROPERTY(importEurooptOnlyImages());
            MOVE PROPERTY(importEurooptUserPriceLists());
        }
    }
}