MODULE WMSIntegration;

REQUIRE Integration,LogTools, Item;

NAMESPACE Integration;

DESIGN  integrationData {
    pane {
        NEW wms {
            caption = 'WMS';
            fill = 1;
            type = TABBED;
        }
    }
}

GROUP wms 'Экспорт в WMS'; 

DESIGN item {
    itemDetail{
        NEW wms {
            caption = 'WMS';
        }
    }
}

@defineLogRotate(WMS, 5, weekly);