MODULE CashPaymentLedger;

REQUIRE Cash, PaymentLedger;

NAMESPACE Cash;

EXTEND CLASS Account : PaymentLedger.Account;

name(Account account) += number(account);
currency(Account account) += currency(account);
legalEntity(Account account) += legalEntity(account);

edit(Account account) += ACTION edit(account);

EXTEND FORM PaymentLedger.accounts
    PROPERTIES(a) addCashAccount = ADDFORM[Cash.Account]
;
