MODULE PriceStockGroupStore;

REQUIRE PriceListStockGroup, Store;

NAMESPACE PriceList;

//------------------------- Расширяем форму Магазина -------------------------//

priceStockGroupStore = DATA PriceStockGroup (Store);
namePriceStockGroupStore 'Ценовая группа' (store)= namePriceStockGroup(priceStockGroupStore(store));

priceStockGroupStock(stock) += priceStockGroupStore(storeDepartmentStore(stock));

EXTEND FORM store
    PROPERTIES(s)   SHOWIF isCompanyStore(s) namePriceStockGroupStore
;
DESIGN store {
    headerExtraParams{
        ADD PROPERTY(namePriceStockGroupStore(s)) BEFORE PROPERTY(nameRegionStore(s));
    }
}
