MODULE FiscalMercury;

REQUIRE System,
        POS;

fiscalMercuryPrintReceipt 'Напечатать фискальный чек' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryPrintReceiptActionProperty';
postPrintReceipt(receipt) += ACTION IF sidCashRegisterModelReceipt(receipt) == 'Mercury' THEN fiscalMercuryPrintReceipt(receipt);

fiscalMercuryAdvancePaper 'Прогон ленты' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryAdvancePaperActionProperty';
fiscalAdvancePaper() += ACTION IF sidModelCurrentCashRegister() == 'Mercury' THEN fiscalMercuryAdvancePaper();

fiscalMercuryXReport 'X-отчёт' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryXReportActionProperty';
fiscalXReport() += ACTION IF sidModelCurrentCashRegister() == 'Mercury' THEN fiscalMercuryXReport();

fiscalMercuryZReport 'Z-отчёт' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryZReportActionProperty';
fiscalZReport() += ACTION IF sidModelCurrentCashRegister() == 'Mercury' THEN fiscalMercuryZReport();

fiscalMercuryServiceCashOperation 'Перемещение денег' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryServiceInOutActionProperty';
fiscalServiceCashOperation(cashOperation) += ACTION IF sidCashRegisterModelCashOperation(cashOperation) == 'Mercury' THEN fiscalMercuryServiceCashOperation(cashOperation);

fiscalMercuryCancelReceipt 'Отменить чек' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryCancelReceiptActionProperty';
fiscalCancelReceipt(receipt) += ACTION IF sidModelCurrentCashRegister() == 'Mercury' THEN fiscalMercuryCancelReceipt(receipt);

fiscalMercuryCutReceipt 'Отрезать чек' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryCutReceiptActionProperty';
fiscalCutReceipt() += ACTION IF sidModelCurrentCashRegister() == 'Mercury' THEN fiscalMercuryCutReceipt();