MODULE FiscalVMKInvoicePayment;

REQUIRE POSInvoicePayment;

fiscalVMKPrintInvoicePayment 'Напечатать оплату' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalvmk.FiscalVMKPrintInvoicePaymentActionProperty' (Invoice.Invoice, Payment.Payment);
printReceiptPaymentInvoice(payment, invoice) += ACTION IF sidModelCurrentCashRegister() == 'VMK' THEN fiscalVMKPrintInvoicePayment(invoice, payment);

