MODULE FiscalCasbi;

REQUIRE System,
        POS;

fiscalCasbiPrintReceipt 'Напечатать фискальный чек' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalcasbi.FiscalCasbiPrintReceiptActionProperty';
postPrintReceipt(receipt) += ACTION IF sidCashRegisterModelReceipt(receipt) == 'Casbi' THEN fiscalCasbiPrintReceipt(receipt);

fiscalCasbiAdvancePaper 'Прогон ленты' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalcasbi.FiscalCasbiAdvancePaperActionProperty';
fiscalAdvancePaper() += ACTION IF sidModelCurrentCashRegister() == 'Casbi' THEN fiscalCasbiAdvancePaper();

fiscalCasbiXReport 'X-отчёт' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalcasbi.FiscalCasbiXReportActionProperty';
fiscalXReport() += ACTION IF sidModelCurrentCashRegister() == 'Casbi' THEN fiscalCasbiXReport();

fiscalCasbiZReport 'Z-отчёт' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalcasbi.FiscalCasbiZReportActionProperty';
fiscalZReport() += ACTION IF sidModelCurrentCashRegister() == 'Casbi' THEN fiscalCasbiZReport();

fiscalCasbiServiceCashOperation 'Перемещение денег' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalcasbi.FiscalCasbiServiceInOutActionProperty';
fiscalServiceCashOperation(cashOperation) += ACTION IF sidCashRegisterModelCashOperation(cashOperation) == 'Casbi' THEN fiscalCasbiServiceCashOperation(cashOperation);

fiscalCasbiCancelReceipt 'Отменить чек' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalcasbi.FiscalCasbiCancelReceiptActionProperty';
fiscalCancelReceipt() += ACTION IF sidModelCurrentCashRegister() == 'Casbi' THEN fiscalCasbiCancelReceipt();

fiscalCasbiDisplayTextReceiptDetail 'Вывести текст на дисплей' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalcasbi.FiscalCasbiDisplayTextActionProperty';
fiscalDisplayTextReceiptDetail (receiptDetail) += ACTION IF sidCashRegisterModelReceiptDetail(receiptDetail) == 'Casbi' THEN fiscalCasbiDisplayTextReceiptDetail(receiptDetail);