MODULE FiscalMercury;

REQUIRE System,
        POS;

fiscalMercuryPrint 'Напечатать фискальный чек' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryPrintReceiptActionProperty' (Receipt);
postPrint(Receipt receipt) += ACTION IF sidCashRegisterModel(receipt) == 'Mercury' THEN fiscalMercuryPrint(receipt);

fiscalMercuryAdvancePaper 'Прогон ленты' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryAdvancePaperActionProperty' ();
fiscalAdvancePaper() += ACTION IF sidModelCurrentCashRegister() == 'Mercury' THEN fiscalMercuryAdvancePaper();

fiscalMercuryXReport 'X-отчёт' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryXReportActionProperty' ();
fiscalXReport() += ACTION IF sidModelCurrentCashRegister() == 'Mercury' THEN fiscalMercuryXReport();

fiscalMercuryZReport 'Z-отчёт' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryZReportActionProperty' ();
fiscalZReport() += ACTION IF sidModelCurrentCashRegister() == 'Mercury' THEN fiscalMercuryZReport();

fiscalMercuryService 'Перемещение денег' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryServiceInOutActionProperty' (CashOperation);
fiscalService(CashOperation cashOperation) += ACTION IF sidCashRegisterModel(cashOperation) == 'Mercury' THEN fiscalMercuryService(cashOperation);

fiscalMercuryCancel 'Отменить чек' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryCancelReceiptActionProperty' (Receipt);
fiscalCancel(Receipt receipt) += ACTION IF sidModelCurrentCashRegister() == 'Mercury' THEN fiscalMercuryCancel(receipt);

fiscalMercuryCutReceipt 'Отрезать чек' = ACTION CUSTOM 'lsfusion.erp.region.by.machinery.cashregister.fiscalmercury.FiscalMercuryCutReceiptActionProperty' ();
fiscalCutReceipt() += ACTION IF sidModelCurrentCashRegister() == 'Mercury' THEN fiscalMercuryCutReceipt();