MODULE ImportFormular;

REQUIRE Import;

GROUP formular 'Formular' : public;

importDataAction 'Импортировать данные (Formular)'  INTERNAL  'lsfusion.erp.region.by.integration.formular.ImportFormularActionProperty' () IN formular;
importUrl 'URL' = DATA VARSTRING[200]() IN formular;
importLogin 'Логин' = DATA VARSTRING[200]() IN formular;
importPassword 'Пароль' = DATA VARSTRING[200]() IN formular;

EXTEND FORM integrationData
    PROPERTIES() importDataAction, importUrl, importLogin, importPassword
;
DESIGN integrationData {
    pane {
        NEW formular {
            caption = 'Formular';
            MOVE GROUP(formular);
        }
    }
}