MODULE EGAISActFixBarCodeGestori;

REQUIRE EGAISActFixBarCode, EGAISStock, EGAISLotGestori, EGAISLot, EGAISSkuLedgerLot;

NAMESPACE EGAIS;

typeOriginalDocument 'Тип документа системы' = ABSTRACT CASE BPISTRING[100] (ActFixBarCode);
numberOriginalDocument 'Номер документа системы' = ABSTRACT CASE STRING (ActFixBarCode);
dateOriginalDocument 'Дата документа системы' = ABSTRACT CASE DATE (ActFixBarCode);

META defineOriginalLastDocumentActFixBarCodeAttributes(object)
    last##object (ActFixBarCode c) = GROUP LAST ##object o ORDER o BY actFixBarCode(o);
    typeOriginalDocument(ActFixBarCode c) += WHEN last##object(c) THEN objectClassName(last##object(c));
    numberOriginalDocument(ActFixBarCode c) += WHEN last##object(c) THEN number(last##object(c));
    dateOriginalDocument(ActFixBarCode c) += WHEN last##object(c) THEN date(last##object(c));
END;

readonlyDescriptionClientActFixBarCode() += TRUE;

afterPostActFixBarCode ABSTRACT LIST (ActFixBarCode);
post 'Провести' (ActFixBarCode a)  {
    NEWSESSION { posted(a) <- TRUE; afterPostActFixBarCode(a); apply(); }
} TOOLBAR CONFIRM;

afterUnpostActFixBarCode ABSTRACT LIST (ActFixBarCode);
unpost 'Распровести' (ActFixBarCode a)  {
    NEWSESSION { posted(a) <- NULL; afterUnpostActFixBarCode(a); apply(); }
} TOOLBAR CONFIRM;

in (ActFixBarCode a, MarkCode c) = GROUP MIN TRUE BY actFixBarCode(actFixBarCodePosition(ActFixBarCodeMark m)), markCode(m);

countMarkCodeUnpostedActFixBarCodeMarkPositions 'Кол-во марок в непроведенных документах фиксации' =
    GROUP SUM 1 IF NOT posted(ActFixBarCodeMark m) BY markCode(m);

unmarkedQuantity 'Доступно к маркировке' (ActFixBarCodePosition p) =
    currentBalance(f2Reg(p)) (-) countMarkCodes(f2Reg(p));

createdBy 'Создан актом' = DATA ActFixBarCode (MarkCode);

processInputIdMarkCode(ActFixBarCode a, ActFixBarCodePosition p, STRING[200] s) {
    IF NOT s THEN RETURN;
    
    LOCAL markCode = MarkCode ();
    LOCAL position = ActFixBarCodePosition ();

    markCode() <- markCode(s);
    position() <- p;

    IF unmarkedQuantity(p) <= countMarkCodes(p) THEN {
        MESSAGE 'По выбранной справке нет доступного к маркировке количества' NOWAIT;
        RETURN;
    }

    IF NOT position() IS ActFixBarCodePosition THEN NEW pos = ActFixBarCodePosition {
        actFixBarCode(pos) <- a;
        position() <- pos;
    }
    
    IF NOT markCode() THEN {
        IF NOT length(s) == 150 THEN {
            MESSAGE 'Длина код маркировки ЕГАИС должна быть равна 150: "' + s + '"';
            RETURN;
        }
        NEW l = Lot {
            id(l) <- s;
            sku(l) <- minItem(product(position()));
            NEW m = MarkCode {
                id(m) <- s;
                createdBy(m) <- a;
                markCode() <- m;
            }
        }
    } ELSE {
        IF f2Reg(markCode()) THEN {
            MESSAGE 'Код маркировки ЕГАИС "' + s + '" уже находится на балансе организации' NOWAIT;
            RETURN;
        }
        IF in(a, markCode()) THEN {
            MESSAGE 'Код маркировки ЕГАИС "' + s + '" уже присутствует в этом документе' NOWAIT;
            RETURN;
        }
        IF countMarkCodeUnpostedActFixBarCodeMarkPositions(markCode()) THEN {
            MESSAGE 'Код маркировки ЕГАИС "' + s + '" уже находится в непроведенном акте фиксации' NOWAIT;
            RETURN;
        }
    }

    IF position() AND markCode() THEN NEW m = ActFixBarCodeMark {
        actFixBarCodePosition(m) <- position();
        markCode(m) <- markCode();
    }

    seek(position());
}

WHEN LOCAL FORMS actFixBarCode (SETCHANGED(f2Reg(actFixBarCodePosition(ActFixBarCodeMark m)))
    OR SETCHANGED(product(actFixBarCodePosition(m))) OR SETCHANGED(markCode(m)))
    AND minItem(product(actFixBarCodePosition(m))) AND lot(markCode(m)) DO {
    sku(lot(markCode(m))) <- minItem(product(actFixBarCodePosition(m)));
}

WHEN (SETCHANGED(f2Reg(actFixBarCodePosition(ActFixBarCodeMark m)))
    OR SETCHANGED(product(actFixBarCodePosition(m))) OR SETCHANGED(markCode(m)))
    AND minItem(product(actFixBarCodePosition(m))) AND lot(markCode(m)) DO {
    sku(lot(markCode(m))) <- minItem(product(actFixBarCodePosition(m)));
}

WHEN LOCAL FORMS actFixBarCode CHANGED(markCode(ActFixBarCodeMark m))
    AND createdBy(PREV(markCode(m))) == actFixBarCode(actFixBarCodePosition(m))
    AND NOT countMarkCodeUnpostedActFixBarCodeMarkPositions(PREV(markCode(m))) DO {
    DELETE Lot l WHERE id(l) == id(PREV(markCode(m)));
    DELETE MarkCode mc WHERE mc = PREV(markCode(m));
}

WHEN LOCAL FORMS actFixBarCode (DROPPED(markCode(ActFixBarCodeMark m)) OR DROPPED(actFixBarCodePosition(m)))
    AND createdBy(markCode(m)) == actFixBarCode(actFixBarCodePosition(m))
    AND NOT countMarkCodeUnpostedActFixBarCodeMarkPositions(markCode(m)) DO {
    DELETE Lot l WHERE id(l) == id(markCode(m));
    DELETE MarkCode mc WHERE mc = markCode(m);
}

WHEN (DROPPED(markCode(ActFixBarCodeMark m)) OR DROPPED(actFixBarCodePosition(m)))
    AND createdBy(markCode(m)) == actFixBarCode(actFixBarCodePosition(m))
    AND NOT countMarkCodeUnpostedActFixBarCodeMarkPositions(markCode(m)) DO {
    DELETE Lot l WHERE id(l) == id(markCode(m));
    DELETE MarkCode mc WHERE mc = markCode(m);
}

changeAddMarkCodeInputIdMarkCode(ActFixBarCodePosition p)  {
    INPUT s = STRING[200] DO {
        processInputIdMarkCode(actFixBarCode(p), p, s);
    }
};

changeAddMarkCodeInputIdMarkCode(ActFixBarCode a)  {
    INPUT s = STRING[200] DO {
        processInputIdMarkCode(a, NULL, s);
    }
};

addMarkCodeInputIdMarkCode 'Ввод кода маркировки :' (ActFixBarCodePosition p) =
    DATA LOCAL STRING[200] (ActFixBarCodePosition) TOOLBAR CHARWIDTH 50 CHANGEKEY 'F4;editing=all'
    EVENTID 'SCANNER' ON CHANGE { changeAddMarkCodeInputIdMarkCode(p); }

addMarkCodeInputIdMarkCode 'Ввод кода маркировки :' (ActFixBarCode a) =
    DATA LOCAL STRING[200] (ActFixBarCode) TOOLBAR CHARWIDTH 50 CHANGEKEY 'F4;editing=all'
    EVENTID 'SCANNER' ON CHANGE { changeAddMarkCodeInputIdMarkCode(a); }

EXTEND FORM actFixBarCode
    PROPERTIES(w) DRAW m  addMarkCodeInputIdMarkCode SHOWIF NOT minActChargeOnPosition(w)
    PROPERTIES(p) DRAW m addMarkCodeInputIdMarkCode SHOWIF minActChargeOnPosition(w)
    PROPERTIES(p) READONLY unmarkedQuantity BEFORE countMarkCodes(p)
    PROPERTIES(m) DELETE GRID
;

DESIGN actFixBarCode {
    OBJECTS {
        NEW address BEFORE pane {
            align = STRETCH;
            MOVE PROPERTY(shortNameClient(w));
            MOVE PROPERTY(descriptionClient(w)) { caption = 'Адрес'; charWidth = 100; }
        }
    }
    
}

EXTEND FORM actFixBarCodes
    PROPERTIES(d) post SHOWIF NOT posted(d), unpost SHOWIF posted(d)
;

DESIGN actFixBarCodes {
    PROPERTY(descriptionClient(d)) { caption = 'Адрес'; }
}

CONSTRAINT client(ActFixBarCode a) AND NOT isCompany(stock(client(a)))
    CHECKED BY client[ActFixBarCode]
    MESSAGE 'Для акта фиксации штрихкодов ЕГАИС доступны только организации, связанные со складами/отделами магазинов компании';

CONSTRAINT f2Reg(ActFixBarCodePosition p) AND NOT hasItemLotType(product(f2Reg(p)))
    CHECKED BY f2Reg[ActFixBarCodePosition]
    MESSAGE 'Для строки акта отмены фиксации штрихкодов ЕГАИС справка Б должна относиться к алкогольной продукции';

CONSTRAINT product(ActFixBarCodePosition p) AND NOT product(f2Reg(p)) == product(p) AND f2Reg(p)
    CHECKED BY f2Reg[ActFixBarCodePosition]
    MESSAGE 'Для строки акта фиксации штрихкодов ЕГАИС справка Б должна соответствовать продукции';

CONSTRAINT (SETCHANGED(countMarkCodes(ActFixBarCodePosition p)) OR SETCHANGED(f2Reg(p)))
    AND unmarkedQuantity(p) < countMarkCodes(p)
    MESSAGE 'Количество не должно превышать доступный остаток по справке Б';

CONSTRAINT SETCHANGED(countMarkCodeUnpostedActFixBarCodeMarkPositions(MarkCode m)) AND countMarkCodeUnpostedActFixBarCodeMarkPositions(m) > 1
    MESSAGE 'Марка может содержаться только в одном непроведенном документе фиксации штрихкодов ЕГАИС';

WHEN LOCAL FORMS actFixBarCode CHANGED(idF2Reg(ActFixBarCodePosition p)) AND NOT (product(p)) DO {
    product(p) <- product(f2Reg(p));
}