MODULE EGAISFRegLedgerGestori;

REQUIRE EGAISFRegLedger, EGAISItemGestori;

NAMESPACE EGAIS;

stock 'Склад документа системы' = ABSTRACT Stock (FRegLedger) MATERIALIZED;
idStock 'Код склада документа системы' (FRegLedger l) = id(stock(l));
nameStock 'Склад документа системы' (FRegLedger l) = name(stock(l));

hasFRegLedger 'С движением по регистру' (F2Reg r, Stock s) =
    GROUP MIN FRegLedger l IF posted(l) BY f2Reg(l), stock(l);

EXTEND FORM balanceReg
    PROPERTIES(l) READONLY nameStock AFTER objectClassName(l)
;