MODULE ComplianceSkuLedger;

REQUIRE Compliance;

NAMESPACE Compliance;

currentBalance (compliance) = GROUP SUM  currentBalance(Batch b) BY compliance(b); 

FORM complianceBatch 'Текущие остатки по сертификатам'
    
    OBJECTS c = Compliance
    PROPERTIES(c) READONLY number, series, date, time, fromDate, toDate,
                           nameLegalEntity
    FILTERGROUP filterBalanceCompliance
        FILTER 'Сертификаты с остатком' currentBalance(c) 'F11' DEFAULT    
                   
    FILTERGROUP filterCompliance
        FILTER 'Сертификаты с истекшим сроком действия' toDate(c) < currentDate() 'F7'
        FILTER 'Сертификаты со сроком действия, истекающим через 7 дней' toDate(c) < sum(currentDate(), 7) 'F6'
        FILTER 'Сертификаты со сроком действия, истекающим через 30 дней' toDate(c) < sum(currentDate(), 30) 'F5'
        FILTER 'Сертификаты со сроком действия, истекающим через 90 дней' toDate(c) < sum(currentDate(), 90) 'F4'                           

    OBJECTS b = Batch
    PROPERTIES(b) READONLY nameSku, id, name, number, series, dateTime, shippedQuantity,
                  currentBalance, expiryDate
    
    FILTERS compliance(b) == c
    
    FILTERGROUP filterBalance
        FILTER 'Партии с остатком' currentBalance(b) 'F10' DEFAULT
;

NAVIGATOR {
    customsNavigator {
        NEW FOLDER customsReports 'Отчеты' AFTER customsMasterData {
            NEW complianceBatch;    
        }
    }
}

EXTEND FORM batches
    PROPERTIES(bt) seriesNumberCompliance, fromDateCompliance, toDateCompliance
;