MODULE InventoryAccountSum;

REQUIRE Inventory, SkuLedgerSum;

NAMESPACE Inventory;

costSum[SkuLedger](InInventorySkuDetail ledger) += Stock.sum(ledger) IF ledger IS InInventorySkuDetail;
costSum[SkuLedger](OutInventorySkuDetail ledger) += Stock.sum(ledger) IF ledger IS OutInventorySkuDetail;

costSum[SkuLedger](InInventoryBatchDetail ledger) += Stock.sum(ledger) IF ledger IS InInventoryBatchDetail;
costSum[SkuLedger](OutInventoryBatchDetail ledger) += Stock.sum(ledger) IF ledger IS OutInventoryBatchDetail;