MODULE EGAISPurchaseInvoice;

REQUIRE PurchaseInvoice, PurchaseShipmentLot,
        EGAISStock, EGAISItem, EGAISWayBillProcess;

PRIORITY Purchase;

NAMESPACE EGAISPurchase;

@defineDocumentInWayBill(userInvoice, shipmentQuantity, supplierStock, customerStock, purchase, 'Накладные (закупка)');

wayBill = ABSTRACT WayBill (Invoice);
wayBill (UserInvoice i) += wayBill(i);

quantity = ABSTRACT NUMERIC[16,5] (InvoiceDetail, WayBillPosition);
quantity(UserInvoiceDetail d, WayBillPosition p) += quantity(d, p);

@defineDocumentInWayBillActProcess(invoice, shipmentQuantity);  

@defineDocumentInWayBillActForm(invoice, i);
