MODULE PricingSaleManufacturingPrice;

REQUIRE SaleManufacturingPrice, PricingSale, PricingManufacturingPrice;

NAMESPACE Sale;

overPricingPricePricingDetail(detail) += manufacturingPriceInvoiceDetail(invoiceDetailInvoicePricingDetail(detail)) IF NOT skipCalcPricingManufacturingPrice();
overPricingPriceUserInvoiceDetail(detail) += manufacturingPriceUserInvoiceDetail(detail) IF NOT skipCalcPricingManufacturingPrice();

manufacturingPricePricingDetail(detail) += manufacturingPriceInvoiceDetail(invoiceDetailInvoicePricingDetail(detail));