MODULE SaleShipmentLot;

REQUIRE SaleShipment, Lot, SkuLedgerLot;

NAMESPACE Sale;

@defineOperationProperty(useLot, 'Марки', showContainer);

@defineDocumentLotOut(userInvoice, supplierStock, shipmentQuantity, i);

// shipment detail
// пока упрощенная схема без поддержки UserShipmentDetail
quantity = ABSTRACT NUMERIC[16,5] (InvoiceDetail, Lot);
quantity(UserInvoiceDetail d, Lot l) += quantity(d, l);

quantityLot 'Кол-во марок' (InvoiceDetail d) = GROUP SUM quantity(d, Lot l);

@defineDocumentLotType(invoice);

// User Shipment
@defineDocumentLotOut(userShipment, supplierStock, quantity, s);

@defineDocumentLotType(shipment);

quantity = ABSTRACT NUMERIC[16,5] (ShipmentDetail, Lot);
quantity(InvoiceShipmentDetail d, Lot l) += quantity(invoiceDetail(d), l);
quantity(UserShipmentDetail d, Lot l) += quantity(d, l);

quantity[OutFIFOSkuLedger, Lot](ShipmentDetail sd, Lot l) += quantity(sd, l);
