MODULE ImportDocument;

REQUIRE System, Import;

CLASS ImportTypeFileExtension 'Тип файла' {
    xls 'XLS',
    xlsx 'XLSX',
    csv 'CSV',
    dbf 'DBF'
}

CLASS ImportKeyType 'Ключ товара' {
    barcode 'Штрихкод',
    batch   'Код партии',
    item    'Код товара'
}

skuBatchId (idBatch) = skuBatch(batchId(idBatch));

CLASS ImportTypeDetail 'Свойство' {
    numberDocument 'Номер накладной',
    dateDocument 'Дата накладной',
    currencyDocument 'Валюта накладной',
    idItem 'Код товара',
    barcodeItem 'Штрихкод товара',
    idBatch 'Код партии',
    captionItem 'Наименование',
    UOMItem 'Единица измерения',
    manufacturerItem 'Производитель',
    countryItem 'Страна',
    importCountryBatch 'Страна ввоза',
    idCustomerStock 'Код склада покупателя',
    pharmacyPriceGroupItem 'Тип лекарственного средства',
    quantity 'Количество',
    price 'Цена',
    manufacturingPrice 'Цена производителя',
    sum 'Сумма',
    valueVAT 'НДС, %',
    sumVAT 'Сумма НДС',
    invoiceSum 'Сумма с НДС',
    seriesPharmacy 'Серия лекарственного средства',
    compliance 'Сертификат',
    declaration 'Декларация',
    expiryDate 'Срок годности',
    idArticle 'Код артикула',
    captionArticle 'Наименование артикула',
    idColor 'Код цвета',
    nameColor 'Цвет',
    idTheme 'Код темы',
    nameTheme 'Тема',
    netWeight 'Масса нетто',
    grossWeight 'Масса брутто',
    composition 'Состав',
    idSize 'Код размера',
    nameSize 'Размер',
    idCollection 'Код коллекции',
    nameCollection 'Коллекция',
    idSeasonYear 'Год',
    idSeason 'Код сезона',
    nameSeason 'Сезон'    
}

CLASS ImportType 'Тип импорта';
TABLE importType(ImportType);

nameImportType 'Имя' =  DATA VARSTRING[100](ImportType);
startRowImportType 'Начинать со строки' = DATA INTEGER(ImportType);
separatorImportType 'Разделитель' = DATA INTEGER(ImportType);
importKeyTypeImportType 'Тип ключа' = DATA ImportKeyType(ImportType);
captionImportKeyTypeImportType 'Тип ключа' (importType) = staticCaption(importKeyTypeImportType(importType));
nameImportKeyTypeImportType 'Тип ключа' (importType) = staticName(importKeyTypeImportType(importType));

TABLE importTypeImportTypeDetail (ImportType, ImportTypeDetail);
indexImportTypeImportTypeDetail 'Поле' = DATA VARSTRING[50] (ImportType, ImportTypeDetail);

importTypeFileExtensionImportType  = DATA ImportTypeFileExtension(ImportType);
captionImportTypeFileExtensionImportType 'Тип файла' (importType) = staticCaption(importTypeFileExtensionImportType(importType));

autoImportOperationImportType =  DATA Operation.Operation(ImportType);
nameAutoImportOperationImportType 'Операция'(importType) = Operation.nameOperation(autoImportOperationImportType(importType));

autoImportSupplierImportType =  DATA LegalEntity(ImportType);
nameAutoImportSupplierImportType 'Поставщик' (importType) =  nameLegalEntity(autoImportSupplierImportType(importType));
autoImportSupplierStockImportType = DATA Stock(ImportType);
nameAutoImportSupplierStockImportType 'Склад поставщика' (importType) =  nameStock(autoImportSupplierStockImportType(importType));
autoImportCustomerImportType = DATA LegalEntity(ImportType);
nameAutoImportCustomerImportType 'Покупатель' (importType) =  nameLegalEntity(autoImportCustomerImportType(importType));
autoImportCustomerStockImportType = DATA Stock(ImportType);
nameAutoImportCustomerStockImportType 'Склад покупателя' (importType) =  nameStock(autoImportCustomerStockImportType(importType));

FORM importTypeDetails
    OBJECTS itd = ImportTypeDetail
    PROPERTIES(itd) staticCaption
    DIALOG ImportTypeDetail OBJECT itd
;

FORM importTypeFileExtensions 'Типы файлов'
    OBJECTS f=ImportTypeFileExtension
    PROPERTIES(f) READONLY staticCaption
    DIALOG ImportTypeFileExtension OBJECT f
;

FORM importKeyTypes 'Типы ключа'
    OBJECTS k=ImportKeyType
    PROPERTIES(k) READONLY staticCaption
    DIALOG ImportKeyType OBJECT k
;

showSeparator (importType) = importType==ImportTypeFileExtension.csv;

FORM importType 'Тип импорта'
    OBJECTS i=ImportType FIXED PANEL
    PROPERTIES(i) nameImportType, captionImportTypeFileExtensionImportType, startRowImportType,
                  separatorImportType SHOWIF showSeparator(i), captionImportKeyTypeImportType
    PROPERTIES(i) nameAutoImportOperationImportType FORCE PANEL, 
                  nameAutoImportSupplierImportType FORCE PANEL,
                  nameAutoImportSupplierStockImportType FORCE PANEL,
                  nameAutoImportCustomerImportType FORCE PANEL,
                  nameAutoImportCustomerStockImportType FORCE PANEL                  
    OBJECTS d = ImportTypeDetail
    PROPERTIES(d) staticCaption
    PROPERTIES(i,d) indexImportTypeImportTypeDetail                   
    EDIT ImportType OBJECT i
;

FORM importTypes 'Типы импорта'
    OBJECTS i=ImportType
    PROPERTIES(i) READONLY nameImportType, captionImportTypeFileExtensionImportType, startRowImportType,
                   separatorImportType SHOWIF showSeparator(i), captionImportKeyTypeImportType
    PROPERTIES(i) ADDFORM, EDITFORM, DELETE
    DIALOG ImportType OBJECT i
;

EXTEND DESIGN importType {
    ADD i.box;
    NEW tabbedContainer {
        fill = 1;
        type = TABBED;
        NEW columnsContainer {
            caption = 'Колонки';
            ADD d.box;
        }
        NEW invoiceParamsContainer {
            caption = 'Параметры накладной';
            ADD PROPERTY(nameAutoImportOperationImportType);
            ADD PROPERTY(nameAutoImportSupplierImportType);
            ADD PROPERTY(nameAutoImportSupplierStockImportType);
            ADD PROPERTY(nameAutoImportCustomerImportType);
            ADD PROPERTY(nameAutoImportCustomerStockImportType);
        }
    }
    ADD functions.box;
}

EXTEND FORM integrationData
    OBJECTS i=ImportType
    PROPERTIES(i) READONLY nameImportType, captionImportTypeFileExtensionImportType, startRowImportType,
                   separatorImportType SHOWIF showSeparator(i), captionImportKeyTypeImportType
    PROPERTIES(i) ADDFORM, EDITFORM, DELETE
;

EXTEND DESIGN integrationData {
    pane {
        NEW importType {
            ADD i.box;
            caption = 'Универсальный импорт';
        }
    }
}

