MODULE ImportSaleOrder;

REQUIRE System,
        ImportDocument,
        Item,
        SaleOrder;

importSaleOrderDataAction 'Импортировать заказ' = ACTION CUSTOM 'lsfusion.erp.integration.universal.ImportSaleOrderActionProperty';
importSaleOrdersDataAction 'Импортировать заказы' = ACTION CUSTOM 'lsfusion.erp.integration.universal.ImportSaleOrdersActionProperty';

importTypeOrder = DATA ImportType(Sale.Order);
nameImportTypeOrder 'Тип импорта' (order) = nameImportType(importTypeOrder(order));

autoImportImportType 'Автоматический импорт' = DATA BOOLEAN(ImportType);
autoImportDirectoryImportType 'Папка' =  DATA VARSTRING[100](ImportType);
autoImportSupplierImportType =  DATA LegalEntity(ImportType);
nameAutoImportSupplierImportType 'Поставщик' (importType) =  nameLegalEntity(autoImportSupplierImportType(importType));
autoImportSupplierStockImportType = DATA Stock(ImportType);
nameAutoImportSupplierStockImportType 'Склад поставщика' (importType) =  nameStock(autoImportSupplierStockImportType(importType));
autoImportCustomerImportType = DATA LegalEntity(ImportType);
nameAutoImportCustomerImportType 'Покупатель' (importType) =  nameLegalEntity(autoImportCustomerImportType(importType));
autoImportCustomerStockImportType = DATA Stock(ImportType);
nameAutoImportCustomerStockImportType 'Склад покупателя' (importType) =  nameStock(autoImportCustomerStockImportType(importType));

EXTEND FORM importTypes
PROPERTIES(i) READONLY autoImportImportType, autoImportDirectoryImportType SHOWIF autoImportImportType(i)
;

EXTEND FORM importType
PROPERTIES(i) autoImportImportType,
              nameAutoImportSupplierImportType FORCE PANEL SHOWIF autoImportImportType(i),
              nameAutoImportSupplierStockImportType FORCE PANEL SHOWIF autoImportImportType(i),
              nameAutoImportCustomerImportType FORCE PANEL SHOWIF autoImportImportType(i),
              nameAutoImportCustomerStockImportType FORCE PANEL SHOWIF autoImportImportType(i),
              autoImportDirectoryImportType FORCE PANEL SHOWIF autoImportImportType(i)
PROPERTIES() importSaleOrdersDataAction TODRAW i TOOLBAR SHOWIF autoImportImportType(i)
;

EXTEND FORM Sale.userOrder
PROPERTIES(o) nameImportTypeOrder
PROPERTIES(o) importSaleOrderDataAction TODRAW d TOOLBAR
;

EXTEND DESIGN Sale.userOrder{
    headerTabbedPane {
        NEW headerImportContainer {
            caption = 'Импорт';
            minimumSize = (700, -1);
            childConstraints = TO THE RIGHTBOTTOM;
            ADD PROPERTY(nameImportTypeOrder);
            ADD PROPERTY(importSaleOrderDataAction);
        }
    }
}

EXTEND DESIGN importType {
    tabbedContainer{
        NEW invoiceParamsContainer {
            caption = 'Параметры заказа';
            ADD PROPERTY(nameAutoImportSupplierImportType);
            ADD PROPERTY(nameAutoImportSupplierStockImportType);
            ADD PROPERTY(nameAutoImportCustomerImportType);
            ADD PROPERTY(nameAutoImportCustomerStockImportType);
            ADD PROPERTY(autoImportImportType);
            ADD PROPERTY(autoImportDirectoryImportType);
            ADD PROPERTY(importSaleOrdersDataAction);
        }
    }
}





