MODULE PurchaseReturnPickingOrder;

REQUIRE OrderInvoicePickingOrder, PurchaseReturnOrder, PurchaseReturnInvoice, PurchaseBin, ConsignmentBy, PurchasePickingOrder;

NAMESPACE PurchaseReturn;

@defineOrderPickingOrder(' (продажа)', supplierStock);

@defineOrderInvoicePickingOrder (' (продажа)');

@deriveDocumentOperationProperty(UserOrder, createPickingOrder);

packQuantityConsignment(d) += WHEN d IS Invoice THEN packQuantityInvoice(d);