MODULE SaleReturnCreditNoteSkuLedger;

REQUIRE SaleReturnCreditNote, SkuLedger;

NAMESPACE SaleReturn;

@fillCreditNoteShipmentQuantity ();

@defineDocumentDetailPriceCustomPrefix(userCreditNoteDetail, shipment, ' (учетная)');

@deriveDocumentDetailPriceAccountBatchDisable (userCreditNote, shipment, sku, supplierStock);

@deriveDocumentDetailSumCustomRoundPrefix(userCreditNoteDetail, shipment, currency, shipmentQuantity, homePriceRound);

@defineUserCreditNoteFormProperties ();

@implementSkuLedgerOutFIFO(UserCreditNoteDetail, sku, supplierStock);

quantity[OutFIFOSkuLedger] (UserCreditNoteDetail ledger) += shipmentQuantity(ledger);
batch[SkuLedger](UserCreditNoteDetail ledger) += batch(ledger);
@implementSkuLedgerOutFIFOBatchBalance(userCreditNoteDetail, supplierStock);

overSum = ABSTRACT NUMERIC[18,4] (UserCreditNoteDetail);
sum[OutSkuLedger](UserCreditNoteDetail ledger) += OVERRIDE overSum(ledger), shipmentSum(ledger);

show[SkuLedger](UserCreditNoteDetail d) + {  show(d); }

// ------------ Проведение по товарному отчету ----------------- //
@implementStockDocumentLedgerOut(UserCreditNote, supplierStock);

stockDocumentLedger(UserCreditNoteDetail ledger) += userCreditNote(ledger);
type(UserCreditNote l) += STRING[50]('Акт расхождения (продажа-возврат)') IF l IS UserCreditNote;
sumItem (UserCreditNote ledger) += shipmentSumItemUserCreditNoteDetail(ledger);
sumContainer (UserCreditNote ledger) += shipmentSumContainerUserCreditNoteDetail(ledger);

legalEntity(UserCreditNote ledger) += customer(ledger);
legalEntityStock(UserCreditNote ledger) += customerStock(ledger);

operation[StockDocumentLedger](UserCreditNote ledger) += operation(ledger);
close[StockDocumentLedger](UserCreditNote l) + {  close(l); }

