MODULE ComPrinter;

REQUIRE Authentication, SerialPort;

NAMESPACE Utils;

vidPrinterComPort 'VID принтера' = DATA STRING[4] (Computer);
pidPrinterComPort 'PID принтера' = DATA STRING[4] (Computer);

EXTEND FORM computer PROPERTIES(c) vidPrinterComPort, pidPrinterComPort; 

jsonPrinterComPort (Computer c) = JSON(FROM vid = vidPrinterComPort(c), pid = pidPrinterComPort(c)); 

printComPort (TEXT t) {
    serialPortSend(jsonPrinterComPort(currentComputer()), t);
}