MODULE SerialPort;

REQUIRE SystemEvents;

NAMESPACE Utils;

initSerialPortJS INTERNAL CLIENT 'serialport.js';
initSerialPortCSS INTERNAL CLIENT 'serialport.css';

openPortReader INTERNAL CLIENT 'openPortReader(info, timeout)' (JSON, INTEGER);
closePortReader INTERNAL CLIENT 'closePortReader(info)' ();

serialPortSend INTERNAL CLIENT 'serialPortSend(port,value)' (JSON, STRING);

onWebClientLoad() + {
    initSerialPortJS();
    initSerialPortCSS();
}
