MODULE NewLandBoard;

REQUIRE System, PriceChecker, Item, MachineryPriceTransaction;

hostNewLandBoard 'Хост' () = DATA STRING[100] (); 
portNewLandBoard 'Порт' () = DATA INTEGER ();        
restartNewLandBoard 'Перестартовать' INTERNAL 'lsfusion.erp.region.by.machinery.board.newland.RestartNewLandBoardAction' ();
        
EXTEND FORM options PROPERTIES() hostNewLandBoard, portNewLandBoard, restartNewLandBoard;

DESIGN options {
    machinery {
        NEW newland {
            caption = 'Настройки прайс-чекера NewLand';
            MOVE PROPERTY (hostNewLandBoard());
            MOVE PROPERTY (portNewLandBoard());
            MOVE PROPERTY (restartNewLandBoard());
        }
    }
}