MODULE SaleEinvoiceUz;

REQUIRE SaleInvoice, ConsignmentEInvoiceUz;

NAMESPACE Sale;

EXTEND FORM invoices
    PROPERTIES(i) SHOWIF eInvoice(i) AND EDIProvider(supplier(i)) sign, cancel
;

DESIGN invoices {
    actionContainer {
        NEW ediUz {
            caption = 'ЭСФ';
            horizontal = TRUE;
            MOVE PROPERTY(sign(i));
            MOVE PROPERTY(cancel(i));
        }
    }
}
